# $NetBSD$

DISTNAME=	giotto-ph-0.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
GITHUB_PROJECT=	giotto-ph
GITHUB_TAG=	refs/tags/v0.1.0
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=giotto-ai/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/giotto-ai/giotto-ph/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
