# $NetBSD$

GITHUB_PROJECT=	PeleC
GITHUB_TAG=	v0.1.5
DISTNAME=	v0.1.5
PKGNAME=	${GITHUB_PROJECT:tl}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=AMReX-Combustion/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/AMReX-Combustion/PeleC/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/PeleC-0.1.5
USE_CMAKE=	yes
USE_LANGUAGES=	c++ fortran

.include "../../mk/bsd.pkg.mk"
