# $NetBSD$

GITHUB_PROJECT=	PeleC
GITHUB_TAG=	v0.1.5
DISTNAME=	v0.1.5
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=AMReX-Combustion/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/AMReX-Combustion/PeleC/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/PeleC-0.1.5
USE_CMAKE=	yes
USE_LANGUAGES=	c++ fortran

.include "../../mk/bsd.pkg.mk"
