# $NetBSD$

DISTNAME=	go-sqlbuilder-1.10.0
GITHUB_PROJECT=	go-sqlbuilder
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=huandu/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/huandu/go-sqlbuilder/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/huandu/go-sqlbuilder

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
