# $NetBSD$

DISTNAME=	shenfun-3.0.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/fa/bb/5fb28b95d645e784d25732d07fed3854d423299722734f64adc088055e63/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/fa/bb/5fb28b95d645e784d25732d07fed3854d423299722734f64adc088055e63/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
