# $NetBSD$

DISTNAME=	imodeljs-20210204
GITHUB_PROJECT=	imodeljs
GITHUB_TAG=	a1a04545c91319b228da5b11361c1d7237ac7b5c
CATEGORIES=	cad parallel python
MASTER_SITES=	${MASTER_SITE_GITHUB:=imodeljs/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/imodeljs/imodeljs/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

WRKSRC=		${WRKDIR}/imodeljs-a1a04545c91319b228da5b11361c1d7237ac7b5c


.include "../../mk/bsd.pkg.mk"
