# $NetBSD$

GITHUB_PROJECT=	rod
GITHUB_TAG=	v0.76.3
DISTNAME=	v0.76.3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-rod/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go-rod/rod/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/rod-0.76.3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
