# $NetBSD$

GITHUB_PROJECT=	xalt
GITHUB_TAG=	xalt-2.10.2
DISTNAME=	xalt-2.10.2
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=xalt/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/xalt/xalt/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
