# $NetBSD$

GITHUB_PROJECT=	ledisdb
GITHUB_TAG=	v0.6
DISTNAME=	v0.6
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ledisdb/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ledisdb/ledisdb/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ledisdb-0.6
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
