# $NetBSD$

DISTNAME=	dufte-0.2.9
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	graphics python
MASTER_SITES=	https://files.pythonhosted.org/packages/c5/c5/9f15def3f433673635caa3b39dd8092bdd880faa0dc358d3d29bfaaf805d/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/nschloe/dufte/
COMMENT=	Clean matplotlib plots
LICENSE=	gnu-gpl-v3

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
