# $NetBSD$

DISTNAME=	dufte-0.2.14
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/9a/2d/d1b3560f2cdb1bbf7936ee548c74db7cbf1ee7696d1c4258900ad6a7ae31/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/9a/2d/d1b3560f2cdb1bbf7936ee548c74db7cbf1ee7696d1c4258900ad6a7ae31/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
