# $NetBSD$

DISTNAME=	susyai
CATEGORIES=	category
MASTER_SITES=	https://susyai.hepforge.org/downloads/
EXTRACT_SUFX=	.tar

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://susyai.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/examples
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
