# $NetBSD$

DISTNAME=	blackhawk_v1.2
CATEGORIES=	category
MASTER_SITES=	https://blackhawk.hepforge.org/downloads/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://blackhawk.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
