# $NetBSD$

DISTNAME=	go-errlog-0.0.2
GITHUB_PROJECT=	errlog
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=snwfdhmp/}
GITHUB_TAG=	${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/snwfdhmp/errlog/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=	github.com/snwfdhmp/errlog
GO_DIST_BASE=	errlog-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
