# $NetBSD$

DISTNAME=	gringo-4.5.4-source
PKGNAME=	${DISTNAME:S/-source//}
CATEGORIES=	category
MASTER_SITES=	https://master.dl.sourceforge.net/project/potassco/gringo/4.5.4/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://master.dl.sourceforge.net/project/potassco/gringo/4.5.4/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
