# $NetBSD$

DISTNAME=	gringo-4.5.4-source
PKGNAME=	${DISTNAME:S/-source//}
CATEGORIES=	category
MASTER_SITES=	https://master.dl.sourceforge.net/project/potassco/gringo/4.5.4/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://master.dl.sourceforge.net/project/potassco/gringo/4.5.4/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
