# $NetBSD$

DISTNAME=	go-httprouter-1.3.0
GITHUB_PROJECT=	httprouter
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=julienschmidt/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/julienschmidt/httprouter/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/httprouter-1.3.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
