# $NetBSD$

GITHUB_PROJECT=	mux
GITHUB_TAG=	v1.8.0
DISTNAME=	v1.8.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gorilla/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gorilla/mux/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/mux-1.8.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
