jobs:
 - kira2math:
    target:
    - [topo7x,seeds7x]
    - [topo7,seeds7]
 - kira2math:
    target:
     - {topologies: [topo7], sectors: [b111111100], r: 7, s: 2, d: 0}
     - {topologies: [topo7], sectors: [b111111100], r: 8, s: 1, d: 1}
     - {topologies: [topo7x], sectors: [b001111111], r: 7, s: 2, d: 0}
     - {topologies: [topo7x], sectors: [b001111111], r: 8, s: 1, d: 1}
#    alt_dir: "/home/usovitsch/Documents/1401Kira/kira/examples/topo7/new2"
 - kira2form:
    target:
     - [topo7,seeds7]
     - [topo7x,seeds7x]
    reconstruct_mass: true
#    alt_dir: "/home/usovitsch/Documents/1401Kira/kira/examples/topo7/new"
