# $NetBSD$

DISTNAME=	optlang-1.4.4
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/13/e4/f755f3cd8371a3cdc620bb8460f8afcd7e0a13b894067cdf12b4740fa740/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/13/e4/f755f3cd8371a3cdc620bb8460f8afcd7e0a13b894067cdf12b4740fa740/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
