# $NetBSD$

GITHUB_PROJECT=	go-jsonerror
GITHUB_TAG=	v0.1.2
DISTNAME=	v0.1.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ddymko/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ddymko/go-jsonerror/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-jsonerror-0.1.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
