# $NetBSD$

DISTNAME=	uniseg-0.7.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/5d/31/c70a45f83f10af81666de047caa3219ff221024a9d3ff5e1dd9511750fcb/
EXTRACT_SUFX=	.zip

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://bitbucket.org/emptypage/uniseg-python
COMMENT=	A pure Python library to determine Unicode text segmentations
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
