# $NetBSD$

GITHUB_PROJECT=	ukui-panel
DISTNAME=	ukui-panel_3.0.0.orig
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
GITHUB_RELEASE=	v3.0.0

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/ukui-panel/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ukui-panel
USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
