# $NetBSD$

DISTNAME=	go-pointer-0.0.1
GITHUB_PROJECT=	go-pointer
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=mattn/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/mattn/go-pointer/
COMMENT=	Utility for cgo
LICENSE=	mit

GO_SRCPATH=	github.com/mattn/go-pointer
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
