# $NetBSD$

DISTNAME=	Lusifer-1.0
CATEGORIES=	category
MASTER_SITES=	https://lusifer.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://lusifer.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	fortran

.include "../../mk/bsd.pkg.mk"
