# $NetBSD$

DISTNAME=	notify_events-1.0.4
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/16/20/ace4347be54edca69b61ac3e69b7e991f4fb4b89a173ba07729614658be8/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/notify-events/python
COMMENT=	Extension to integrate your project with Notify.Events service
LICENSE=	mit

DEPENDS+=	py-requests>=0:../../devel/py-requests

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
