# $NetBSD$

GITHUB_PROJECT=	tauri
GITHUB_TAG=	tauri.js-v0.13.0
DISTNAME=	tauri.js-v0.13.0
PKGNAME=	${DISTNAME:S,-v,-,}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=tauri-apps/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/tauri-apps/tauri/
COMMENT=	Build smaller, faster, and more secure desktop applications with a web frontend
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/tauri-tauri.js-v0.13.0

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
