# $NetBSD$

DISTNAME=	kproperty-3.0.0.tar.xz
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_KDE:=kproperty/src/}
EXTRACT_SUFX=	.mirrorlist

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://download.kde.org/stable/kproperty/src/ # TODO: check
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
