# $NetBSD$

GITHUB_PROJECT=	cbraid
GITHUB_TAG=	move-to-github
DISTNAME=	move-to-github
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/cbraid/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/cbraid-move-to-github
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
