# $NetBSD$

DISTNAME=	pytocs
PKGNAME=	pytocs-1.2.0
GITHUB_PROJECT=	pytocs
GITHUB_TAG=	refs/tags/v1.2.0
DISTNAME=	v1.2.0
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=uxmal/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/uxmal/pytocs/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/pytocs-1.2.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
