# $NetBSD$

DISTNAME=	pyviz-0.10.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/py//}
CATEGORIES=	graphics python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pyviz/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/cb/91/64ab550165269ed81573f8bdf185ad4b9832831afe7b8207f15506201512/
COMMENT=	TODO: Short description of the package
LICENSE=	modified-bsd

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
