# $NetBSD$

DISTNAME=	pyviz-0.10.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/py//}
CATEGORIES=	graphics python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pyviz/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://pyviz.org/
COMMENT=	How to solve visualization problems with Python tools
LICENSE=	modified-bsd

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
