# $NetBSD$

DISTNAME=	pigo-1.4.3
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	pigo
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=esimov/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/esimov/pigo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../mk/bsd.pkg.mk"
