# $NetBSD$

DISTNAME=	pigo-1.4.3
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	pigo
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=esimov/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/esimov/pigo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/esimov/pigo

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
