# $NetBSD$

GITHUB_PROJECT=	hero
GITHUB_TAG=	v0.0.2
DISTNAME=	v0.0.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=shiyanhui/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/shiyanhui/hero/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/hero-0.0.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
