# $NetBSD$

DISTNAME=	go-pio-0.0.10
GITHUB_PROJECT=	pio
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kataras/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kataras/pio/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/pio-0.0.10
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
