# $NetBSD$

DISTNAME=	gast-0.4.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/83/4a/07c7e59cef23fb147454663c3271c21da68ba2ab141427c20548ae5a8a4d/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/serge-sans-paille/gast/
COMMENT=	Python AST that abstracts the underlying Python version
#LICENSE=	BSD 3-Clause # TODO: from setup.py; needs to be adjusted

TEST_DEPENDS+=	# TODO: astunparse>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
