# $NetBSD$

DISTNAME=	go-python-0.1.0
GITHUB_PROJECT=	go-python
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=sbinet/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/sbinet/go-python/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
