# $NetBSD$

DISTNAME=	pydata-google-auth-1.1.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/8d/b8/5e9b616e6748e6578abd4b484e3c92cdd54ca9d32131c5e3cc46b1929705/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/8d/b8/5e9b616e6748e6578abd4b484e3c92cdd54ca9d32131c5e3cc46b1929705/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
