# $NetBSD$

DISTNAME=	hiq-circuit-0.0.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/45/c1/39453dd9e61db6e14cb5116f86788b18ca15c9794593fee46fc258715283/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/45/c1/39453dd9e61db6e14cb5116f86788b18ca15c9794593fee46fc258715283/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
