y# $NetBSD$

GITHUB_PROJECT=	confluent-kafka-go
GITHUB_TAG=	v1.4.2
DISTNAME=	v1.4.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=confluentinc/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/confluentinc/confluent-kafka-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/confluent-kafka-go-1.4.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
