# $NetBSD$

DISTNAME=	gorgonia-20210121
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	gorgonia
GITHUB_TAG=	12e31c4befd99d1c0844d0d7555b102c3aa11639
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gorgonia/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gorgonia/gorgonia/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=	${WRKDIR}/gorgonia-12e31c4befd99d1c0844d0d7555b102c3aa11639

.include "../../mk/bsd.pkg.mk"
