# $NetBSD$

DISTNAME=	go-gonum-0.8.2
GITHUB_PROJECT=	gonum
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=gonum/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/gonum/gonum/
COMMENT=	TODO: Short description of the package
LICENSE=	apache-2.0

GO_DIST_BASE=   ${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=     github.com/gonum/gonum

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
