# $NetBSD$

DISTNAME=	gdxpds-1.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=   ${MASTER_SITE_PYPI:=g/gdxpds/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/NREL/gdx-pandas
COMMENT=	Python package to translate between gdx (GAMS data) and pandas
#LICENSE=	# TODO: (see mk/license.mk)


DEPENDS+=	# TODO: p>=0
DEPENDS+=	# TODO: y>=0
DEPENDS+=	# TODO: =>=0
DEPENDS+=	# TODO: 1>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 7>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
