# $NetBSD$

DISTNAME=	gdxpds-1.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=   ${MASTER_SITE_PYPI:=g/gdxpds/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/NREL/gdx-pandas
COMMENT=	Python package to translate between gdx (GAMS data) and pandas
#LICENSE=	# TODO: (see mk/license.mk)


DEPENDS+=	# TODO: p>=0
DEPENDS+=	# TODO: y>=0
DEPENDS+=	# TODO: =>=0
DEPENDS+=	# TODO: 1>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 7>=0

USE_LANGUAGES=	# none

.include "../../math/py-numpy/buildlink3.mk"
.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
