# $NetBSD$

DISTNAME=	kronometer-2.2.3
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_KDE:=kronometer/2.2.3/src/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=     kamelderouiche@yahoo.com
HOMEPAGE=       https://userbase.kde.org/Kronometer
COMMENT=        Stopwatch application by KDE
LICENSE=        gnu-gpl-v2

USE_CMAKE=		yes
USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		c++

.include "../../mk/bsd.pkg.mk"
