# $NetBSD$

DISTNAME=	go-sdl2-0.4.0
GITHUB_PROJECT=	go-sdl2
GITHUB_TAG=	v0.4.0
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=veandco/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/veandco/go-sdl2/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../mk/bsd.pkg.mk"
