# $NetBSD$

DISTNAME=	truffleHog3-2.0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	${MASTER_SITE_PYPI:=m/${DISTNAME:S/${VERS}//}/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/feeltheajf/truffleHog3
COMMENT=	Find secrets in your codebase
#LICENSE=	GNU # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: GitPython==3.1.0>=0
DEPENDS+=	# TODO: jinja2==2.11.1>=0
DEPENDS+=	# TODO: PyYAML==5.3.1>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
