# $NetBSD$

DISTNAME=	pyarmadillo-0.500.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/py//}
CATEGORIES=	category
MASTER_SITES=	https://sourceforge.net/projects/pyarma/files/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://sourceforge.net/projects/pyarma/files/
COMMENT=	Linear algebra library for Python, with emphasis on ease of use
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
