# $NetBSD$

DISTNAME=	olga-1.2.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/fc/30/8a31bba722eb66ad08092471ddeb043e3c5b9ce59b1e05e8e9919371fbb0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/zsethna/OLGA
COMMENT=	Compute generation probability of CDR3 sequences
#LICENSE=	GPLv3 # TODO: from setup.py; needs to be adjusted

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
