# $NetBSD$

DISTNAME=	olga-1.2.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	biology python
MASTER_SITES=	${MASTER_SITE_PYPI:=o/olga/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/zsethna/OLGA
COMMENT=	Compute generation probability of CDR3 sequences
LICENSE=	gnu-gpl-v3


.include "../../math/py-numpy/buildlink3.mk"
.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
