# $NetBSD$

DISTNAME=	swh.core-0.10.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/bc/48/875d9c86fc19ad1349b70a775683df21cd39e01846c6da7de4443a1f7a7d/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://forge.softwareheritage.org/diffusion/DCORE/
COMMENT=	Software Heritage core utilities
#LICENSE=	# TODO: (see mk/license.mk)

BUILD_DEPENDS+=	# TODO: setuptools-scm>=0
DEPENDS+=	# TODO: Click>=0
DEPENDS+=	py-Deprecated>=0:../../devel/py-Deprecated
DEPENDS+=	# TODO: PyYAML>=0
DEPENDS+=	py-sentry-sdk>=0:../../wip/py-sentry-sdk

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
