# $NetBSD$

GITHUB_PROJECT=	gobot
GITHUB_TAG=	v1.14.0
DISTNAME=	v1.14.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=hybridgroup/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/hybridgroup/gobot/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gobot-1.14.0
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
