# $NetBSD$

BUILDLINK_TREE+=	go-log15

.if !defined(GO_LOG15_BUILDLINK3_MK)
GO_LOG15_BUILDLINK3_MK:=

BUILDLINK_CONTENTS_FILTER.go-log15=	${EGREP} gopkg/
BUILDLINK_DEPMETHOD.go-log15?=		build

BUILDLINK_API_DEPENDS.go-log15+=	go-log15>=2.15
BUILDLINK_PKGSRCDIR.go-log15?=	../../wip/go-log15
.endif	# GO_LOG15_BUILDLINK3_MK

BUILDLINK_TREE+=	-go-log15
