# Module dependencies
amp5.o: mtopo5.o
amp5.lo: mtopo5.lo
amp5.obj: mtopo5.obj
mtopo5.o: vars.o
mtopo5.lo: vars.lo
mtopo5.obj: vars.obj
process.o: amp5.o rambo.o vars.o
process.lo: amp5.lo rambo.lo vars.lo
process.obj: amp5.obj rambo.obj vars.obj
