# $NetBSD$

DISTNAME=	asmai-0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/e3/ba/99efc20677b0d3634e547052afde5f051b0c2d95626dde3ac109c37affe5/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://asmai.sourceforge.net/
COMMENT=	Asmai: (Al'asma'i) Arabic semantic analysis library for Python
LICENSE=	gnu-gpl-v1 OR gnu-gpl-v2 OR gnu-gpl-v3

DEPENDS+=	# TODO: pyarabic>=0.6.2

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
