# $NetBSD$

DISTNAME=	asmai-0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	${MASTER_SITE_PYPI:=a/asmai/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://asmai.sourceforge.net/
COMMENT=	Asmai: (Al'asma'i) Arabic semantic analysis library for Python
LICENSE=	gnu-gpl-v1 OR gnu-gpl-v2 OR gnu-gpl-v3

DEPENDS+=	# TODO: pyarabic>=0.6.2

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
