# $NetBSD$

DISTNAME=	nano-20170107
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	nano
GITHUB_TAG=	ed4c74a4eccaf152432035f0a2e03a4a897638d9
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/nano/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/nano-ed4c74a4eccaf152432035f0a2e03a4a897638d9
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
