# $NetBSD$

DISTNAME=	tox-DEBIAN-0.3.linux-x86_64
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/dd/7a/688b73d4150b475766e2f5db6c41cf9d6bd4525930bad7df456ec89f93c0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/dd/7a/688b73d4150b475766e2f5db6c41cf9d6bd4525930bad7df456ec89f93c0/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/usr
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
