# $NetBSD$

DISTNAME=	negroni-20201114
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	negroni
GITHUB_TAG=	7915ed3d6bdb7d071a72f9f1e15ace4c78e97636
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=urfave/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/urfave/negroni/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/negroni-7915ed3d6bdb7d071a72f9f1e15ace4c78e97636
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
