# $NetBSD$

DISTNAME=	boost-histogram-0.11.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=b/boost-histogram/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/41/74/452f5d854d0dff178b81ddca6e94067e2f214a59a3a3debea1f0cbc3beee/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)


.include "../../math/py-numpy/buildlink3.mk"
.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
