# $NetBSD$

DISTNAME=	go-httpexpect-1.1.3
GITHUB_PROJECT=	httpexpect
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=gavv/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/gavv/httpexpect/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=   ${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=     github.com/gavv/httpexpect

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
