# $NetBSD$

DISTNAME=	go-httpexpect-1.1.3
GITHUB_PROJECT=	httpexpect
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gavv/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gavv/httpexpect/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/httpexpect-1.1.3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
