# $NetBSD$

GITHUB_PROJECT=	httpexpect
GITHUB_TAG=	v2.1.0
DISTNAME=	v2.1.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gavv/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gavv/httpexpect/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/httpexpect-2.1.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
