# $NetBSD$

DISTNAME=	go-gosl-1.2.8
GITHUB_PROJECT=	gosl
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=cpmech/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/cpmech/gosl/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gosl-1.2.8
USE_LANGUAGES=	c fortran

.include "../../mk/bsd.pkg.mk"
