# $NetBSD$

DISTNAME=	teamcity-messages-1.28
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/df/c2/4ac5824fa5cc5739a63cfbd38b530c2fb0d19e26faa52779629048f8d0fe/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/df/c2/4ac5824fa5cc5739a63cfbd38b530c2fb0d19e26faa52779629048f8d0fe/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
