# $NetBSD$

DISTNAME=	zerolog-0.0.0.20200806
PKGNAME=	go-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=rs/}
GITHUB_PROJECT=	zerolog
GITHUB_TAG=	72acd6cfe8bbbf5c52bfc805a3889c6941499c95

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/rs/zerolog/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

GO_DIST_BASE=	zerolog-${GITHUB_TAG}
GO_SRCPATH=	github.com/rs/zerolog/


.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
