# $NetBSD$

DISTNAME=	zerolog-0.0.0.20200806
PKGNAME=	go-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=rs/}
GITHUB_PROJECT=	zerolog
GITHUB_TAG=	72acd6cfe8bbbf5c52bfc805a3889c6941499c95

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/rs/zerolog/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/zerolog-72acd6cfe8bbbf5c52bfc805a3889c6941499c95
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
