# $NetBSD$

DISTNAME=	Chani-1.0.0
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	math
MASTER_SITES=	http://www.hepforge.org/archive/chani/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://chani.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
