# $NetBSD$

DISTNAME=	mozdevice-4.0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/23/7c/16999dcf92689a73932f218cc8a711b7b1aa9f8055f70d62c634b1e32a52/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://wiki.mozilla.org/Auto-tools/Projects/Mozbase
COMMENT=	Mozilla-authored device management
#LICENSE=	MPL # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: mozlog>=6.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
