# $NetBSD$

DISTNAME=	django-sympycharfield-0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/3b/f1/4a9fcd296161b810884ff32573c65dc090b68d4dc167f3d7c7bbe2ee7e9c/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/3b/f1/4a9fcd296161b810884ff32573c65dc090b68d4dc167f3d7c7bbe2ee7e9c/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
