# $NetBSD$

DISTNAME=	pandas-bokeh-0.5.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/d9/00/c071450b7d7b1797f22e469c892aab8538a090326ccd81d2e3d397a8c4bd/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/d9/00/c071450b7d7b1797f22e469c892aab8538a090326ccd81d2e3d397a8c4bd/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
