# $NetBSD$

DISTNAME=	murmurhash2-0.2.7
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	security devel
MASTER_SITES=	${MASTER_SITE_PYPI:=m/murmurhash2/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/d0/aa/1fe972b9c65aa0e5257f751d83f768eb2d1d7c0961a2661415a755931bed/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
