# $NetBSD$

DISTNAME=	deep_merge-0.0.4
PKGNAME=	${PYPKGPREFIX}-deep-merge-0.0.4
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/a5/25/aa35c20acd8a4f515f9e4c8dee4c7731446234101a6dae0c34cf498bb342/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/halfak/deep_merge
COMMENT=	A simple utility for merging python dictionaries
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
