# $NetBSD$

DISTNAME=	makezero-20201207
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	makezero
GITHUB_TAG=	7b7cdbb3025a82245521007c82a66e9b1a347ca2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=ashanbrown/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/ashanbrown/makezero/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/makezero-7b7cdbb3025a82245521007c82a66e9b1a347ca2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
