# $NetBSD$

DISTNAME=	bw_migrations-0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/e2/b1/8c46d0cd0d552cffee729ff7b18c70adbb029e60c52dff750218050e9d6b/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/brightway-lca/bw_migrations
COMMENT=	Migration data and utilities for Brightway IO and LCA in general
#LICENSE=	NewBSD 3-clause; LICENSE # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: stats_arrays>=0
TEST_DEPENDS+=	# TODO: stats_arrays>=0
TEST_DEPENDS+=	# TODO: pytest>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
