# $NetBSD$

DISTNAME=	bw_migrations-0.1
PKGNAME=	${PYPKGPREFIX}-bw-migrations-0.1
CATEGORIES=	databases python
MASTER_SITES=	${MASTER_SITE_PYPI:=b/bw_migrations/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/brightway-lca/bw_migrations
COMMENT=	Migration data and utilities for Brightway IO and LCA in general
LICENSE=	modified-bsd

#DEPENDS+=	${PYPKGPREFIX}-stats-arrays>=0.6.4:../../wip/py-stats-arrays
#TEST_DEPENDS+=	${PYPKGPREFIX}-test>=0.6.4:../../wip/py-test

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
