# $NetBSD$

DISTNAME=	figure-20200609
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	go-figure
GITHUB_TAG=	c4b36f9
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/go-figure/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-figure-c4b36f998cf220420b4263c614faaf2872770fb3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
