# $NetBSD$

DISTNAME=	stats_arrays-0.6.4
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/e8/44/cf6446d34b148086a7b20f7569a5efc0c56c19425ac784805b52636fe83c/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://bitbucket.org/cmutel/stats_arrays
COMMENT=	Standard NumPy array interface for defining uncertain parameters
#LICENSE=	BSD 3-Clause License # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: numpy>=0
DEPENDS+=	# TODO: scipy>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
