# $NetBSD$

DISTNAME=	releases-1.6.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/01/a3/b86ac00f808e4e4487d9ad668985d1e15bdd03816923183836c0f606005a/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/bitprophet/releases
COMMENT=	A Sphinx extension for changelog manipulation
#LICENSE=	# TODO: (see mk/license.mk)

DEPENDS+=	# TODO: semantic_version<2.7>=0
DEPENDS+=	py-sphinx>=1.3:../../textproc/py-sphinx

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
