# $NetBSD$

DISTNAME=	ukui-kwin-20210105
GITHUB_PROJECT=	ukui-kwin
GITHUB_TAG=	3b80ff04d66193e015d56e41d05a22b4fcdca41f
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/ukui-kwin/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
