# $NetBSD$

DISTNAME=	humanfriendly-8.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/6c/19/8e3b4c6fa7cca4788817db398c05274d98ecc6a35e0eaad2846fde90c863/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://humanfriendly.readthedocs.io
COMMENT=	Human friendly output for text interfaces using Python
LICENSE=	mit

TEST_DEPENDS+=	# TODO: capturer>=2.1
TEST_DEPENDS+=	# TODO: coloredlogs>=2.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
