# $NetBSD$

DISTNAME=	go-flogo-0.5.6
GITHUB_PROJECT=	flogo
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=TIBCOSoftware/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/TIBCOSoftware/flogo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	flogo-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/TIBCOSoftware/flogo/

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
