# $NetBSD$

DISTNAME=	go-flogo-0.5.6
GITHUB_PROJECT=	flogo
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=TIBCOSoftware/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.flogo.io/
COMMENT=	TODO: Short description of the package
LICENSE=	3-clause-bsd

GO_DIST_BASE=	flogo-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/TIBCOSoftware/flogo/

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
