# This file was autogenerated in base/version_git.sh
struct GitVersionInfo
    commit::AbstractString
    commit_short::AbstractString
    branch::AbstractString
    build_number::Int
    date_string::AbstractString
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
end

const GIT_VERSION_INFO = GitVersionInfo(
    "697e782ab86bfcdd7fd15550241fe162c51d9f98",
    "697e782ab8*",
    "HEAD",
    0,
    "2020-08-25 20:08 UTC",
    true,
    128,
    1588882331.
)
