# $NetBSD$

DISTNAME=	kira-2.0
CATEGORIES=	category
MASTER_SITES=	https://kira.hepforge.org/downloads?f=releases/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://kira.hepforge.org/downloads?f=releases/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++

.include "../../devel/meson/build.mk"
.include "../../mk/bsd.pkg.mk"
