# $NetBSD$

DISTNAME=	kira-2.0
CATEGORIES=	math
MASTER_SITES=	https://kira.hepforge.org/downloads?f=releases/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://kira.hepforge.org/
COMMENT=	Feynman integral reduction program
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++

.include "../../devel/meson/build.mk"
.include "../../mk/bsd.pkg.mk"
