# $NetBSD$

DISTNAME=	meshio-4.2.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ab/04/402ffdedeb03667977f9c3fea8963f7d208057e201e34062f3aeb18ba99e/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ab/04/402ffdedeb03667977f9c3fea8963f7d208057e201e34062f3aeb18ba99e/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
