# $NetBSD$

DISTNAME=	circonusllhist-20190922
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	circonusllhist
GITHUB_TAG=	ec08cde75a2939392fe7ef109066ae2078ca6b1e
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=circonus-labs/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/circonus-labs/circonusllhist/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/circonusllhist-ec08cde75a2939392fe7ef109066ae2078ca6b1e
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
