# $NetBSD$

DISTNAME=	lemma-0.1.dev0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/5f/e9/8092f4713eb8d3d0e220b5a486bf276832a958f9ca3715f6bb92b8d46990/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/5f/e9/8092f4713eb8d3d0e220b5a486bf276832a958f9ca3715f6bb92b8d46990/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
