# $NetBSD$

DISTNAME=	pyfuse3-3.1.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/af/3a/94f4cdf85ffcb03c80036b427f5797e2b70ed0413fcc632a284bd1703fd4/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/af/3a/94f4cdf85ffcb03c80036b427f5797e2b70ed0413fcc632a284bd1703fd4/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
