# $NetBSD$

DISTNAME=	threadpoolctl-2.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://files.pythonhosted.org/packages/78/e8/e39dc842f512ab5be11efe83160ddb7ad3c0cc1b8d42ce8c0469a0d2b926/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/joblib/threadpoolctl
COMMENT=	threadpoolctl
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
