# $NetBSD$

DISTNAME=	molmass-2020.6.10
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	biology python
MASTER_SITES=	${MASTER_SITE_PYPI:=m/molmass/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://www.lfd.uci.edu/~gohlke/
COMMENT=	Molecular Mass Calculations
LICENSE=	modified-bsd

PYTHON_VERSIONS_INCOMPATIBLE+=	27

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
