integralfamilies:
  - name: "topo7"
    loop_momenta: [k1,k2]
    top_level_sectors: [127]
    propagators:
      - [ "-k1", 0]         #1
      - [ "k2", 0]          #2
      - [ "-k1+k2", 0]      #3
      - [ "k1+q2", "m22"]   #4 
      - [ "k2-p2", 0]       #5
      - [ "-k1+p1+p2", 0]   #6
      - [ "k2-p1-p2", 0]    #7
      - [ "k1-p2", 0]       #8
      - [ "k2-q2", 0]       #9
#    cut_propagators: [3,4] #uncomment to use the option cut_propagators
