kinematics:
  incoming_momenta: [q1,q2,p1,p2]
  outgoing_momenta: []
  momentum_conservation: [q1,-p1-p2-q2]
  kinematic_invariants:
     - [s,  2]
     - [t,  2]
     - [m22, 2]
     - [m12, 2]
  scalarproduct_rules:
     - [[p1,p1],  0]
     - [[p2,p2],  0]
     - [[q2,q2],  0]
     - [[p1+p2, p1+p2], s]
     - [[p2-q2, p2-q2], t]
     - [[p1-q2, p1-q2], s-t-m12]
  symbol_to_replace_by_one: m12
