# $NetBSD$

GITHUB_PROJECT=	MailingListStats
GITHUB_TAG=	0.4.1
DISTNAME=	0.4.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=MetricsGrimoire/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/MetricsGrimoire/MailingListStats/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
