# $NetBSD$

DISTNAME=	go-graphql-20200928
GITHUB_PROJECT=	graphql
GITHUB_TAG=	18c5c31
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/graphql/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/graphql-18c5c3165e3af7c70ca625593f8066462ad684cc
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
