# $NetBSD$

DISTNAME=	gdxcc-7.28.20
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/cb/60/f8431ee5f0a8b9a260dbbd80565fa24674bffc48f655b40c2d382524a35b/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kavvkon/gams-api
COMMENT=	Python library to access and modify gdx files
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
