# $NetBSD$

GITHUB_PROJECT=	htmlquery
GITHUB_TAG=	v1.2.3
DISTNAME=	v1.2.3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=antchfx/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/antchfx/htmlquery/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/htmlquery-1.2.3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
