# $NetBSD$

DISTNAME=	spacy-legacy-3.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/74/e7/72a1e40cb44c7b9e9a978820b20ca9c3d0e9abf222e00fdfa4e650d1a0be/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/74/e7/72a1e40cb44c7b9e9a978820b20ca9c3d0e9abf222e00fdfa4e650d1a0be/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
