# $NetBSD$

DISTNAME=	textX-2.3.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	parallel python
MASTER_SITES=	${MASTER_SITE_PYPI:=t/textX/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/e3/6e/775e86f7d6ef22bf32999a73479d55cc93869b80af8088b8225c2d8a2cd0/
COMMENT=	Meta-language for DSL implementation inspired by Xtext
#LICENSE=	# TODO: (see mk/license.mk)

TEST_DEPEND= ${PYPKGPREFIX}-flake8>=:../../devel/py-flake8

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
