# $NetBSD$

DISTNAME=	qt-creator-opensource-src-4.12.4
CATEGORIES=	category
MASTER_SITES=	http://qtproject.mirror.liquidtelecom.com/official_releases/qtcreator/4.12/4.12.4/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://qtproject.mirror.liquidtelecom.com/official_releases/qtcreator/4.12/4.12.4/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
