# $NetBSD$

GITHUB_PROJECT=	ukui-keyring
GITHUB_TAG=	v2020.04.25
DISTNAME=	v2020.04.25
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/ukui/ukui-keyring/
COMMENT=	Keyring for the UKUI repository
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ukui-keyring-2020.04.25

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
