# $NetBSD$

DISTNAME=	nulike-1.0.9
CATEGORIES=	category
MASTER_SITES=	https://nulike.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://nulike.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	fortran

.include "../../mk/bsd.pkg.mk"
