# $NetBSD$

DISTNAME=	kreport-3.0.0.tar.xz
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_KDE:=kreport/src/}
EXTRACT_SUFX=	.mirrorlist

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://www.kexi-project.org/
COMMENT=	Framework for creation of reports in multiple formats
LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
