# $NetBSD$

DISTNAME=	cado-nfs-2.3.0
CATEGORIES=	category
MASTER_SITES=	https://gforge.inria.fr/frs/download.php/file/37058/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://gforge.inria.fr/frs/download.php/file/37058/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
