# $NetBSD$

DISTNAME=	repr-0.3.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/cf/d9/891955bf9e29cd6ab1000b9c66cee157070ac74e172a738d3388719fb49a/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/svetlyak40wt/python-repr
COMMENT=	A shortcut to generate __repr__ methods for python classes
#LICENSE=	BSD # TODO: from setup.py; needs to be adjusted

DEPENDS+=	py-six>=0:../../lang/py-six

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
