# $NetBSD$

DISTNAME=	porttree-1.1.r114
CATEGORIES=	category
MASTER_SITES=	https://ayera.dl.sourceforge.net/project/porttree/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ayera.dl.sourceforge.net/project/porttree/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
