# $NetBSD$

GITHUB_PROJECT=	go-sqlmock
GITHUB_TAG=	v1.5.0
DISTNAME=	v1.5.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=DATA-DOG/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/DATA-DOG/go-sqlmock/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-sqlmock-1.5.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
