# $NetBSD$

DISTNAME=	aruudy-0.5.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	${MASTER_SITE_PYPI:=a/aruudy/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/kariminf/aruudy
COMMENT=	Arabic poetry package
LICENSE=	apache-2.0

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
