# $NetBSD$

DISTNAME=	go-amqp-1.0.0
GITHUB_PROJECT=	amqp
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_GITHUB:=streadway/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/streadway/amqp/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/amqp-1.0.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
