# $NetBSD$

GITHUB_PROJECT=	go-datastructures
GITHUB_TAG=	v1.0.52
DISTNAME=	v1.0.52
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=Workiva/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Workiva/go-datastructures/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-datastructures-1.0.52
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
