# $NetBSD$

GITHUB_PROJECT=	wuzz
GITHUB_TAG=	v0.4.0
DISTNAME=	v0.4.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=asciimoo/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/asciimoo/wuzz/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/wuzz-0.4.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
