# $NetBSD$

GITHUB_PROJECT=	svgo
GITHUB_TAG=	go.weekly.2012-01-27
DISTNAME=	go.weekly.2012-01-27
PKGNAME=	go-svgo-20120127
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_GITHUB:=ajstarks/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/ajstarks/svgo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/svgo-go.weekly.2012-01-27

USE_LANGUAGES=	# none


.include "../../mk/bsd.pkg.mk"
