# $NetBSD$

DISTNAME=	qcodes-0.17.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ba/ec/7117dc57310c6d0aea697e0682ef14bfa2ae6535b85bb8d4b8449de05270/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ba/ec/7117dc57310c6d0aea697e0682ef14bfa2ae6535b85bb8d4b8449de05270/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
