# $NetBSD$

DISTNAME=	sdnotify-0.3.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	sysutils python
MASTER_SITES=	https://files.pythonhosted.org/packages/ce/d8/9fdc36b2a912bf78106de4b3f0de3891ff8f369e7a6f80be842b8b0b6bd5/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/bb4242/sdnotify
COMMENT=	Python implementation of systemd service notification protocol
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
