# $NetBSD$

DISTNAME=	x2j-20131220
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	x2j
GITHUB_TAG=	a0352aa
CATEGORIES=	textproc
MASTER_SITES=	${MASTER_SITE_GITHUB:=beego/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/beego/x2j
COMMENT=	Unmarshal an anonymous XML doc and extract values
LICENSE=	2-clause-bsd

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}*
GO_SRCPATH=	github.com/beego/${GITHUB_PROJECT}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
