# $NetBSD$

DISTNAME=	boost-histogram-0.11.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/41/74/452f5d854d0dff178b81ddca6e94067e2f214a59a3a3debea1f0cbc3beee/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/41/74/452f5d854d0dff178b81ddca6e94067e2f214a59a3a3debea1f0cbc3beee/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
