# $NetBSD$

DISTNAME=	bw2calc-1.8.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	${MASTER_SITE_PYPI:=b/bw2calc/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://bitbucket.org/cmutel/brightway2-calc
COMMENT=	TODO: Short description of the package
#LICENSE=	NewBSD 3-clause; LICENSE.txt # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: eight>=0
DEPENDS+=	# TODO: numpy>=0
DEPENDS+=	# TODO: scipy>=0
DEPENDS+=	# TODO: stats_arrays>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
