# $NetBSD$

DISTNAME=	v0.16
PKGNAME=	${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=asticode/go-astilectron/releases/tag/}
EXTRACT_SUFX=	.0

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/asticode/go-astilectron/releases/tag/ # TODO: check
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
