# $NetBSD$

GITHUB_PROJECT=	circuitbreaker
GITHUB_TAG=	v2.2.1
DISTNAME=	v2.2.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=rubyist/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/rubyist/circuitbreaker/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/circuitbreaker-2.2.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
