# $NetBSD$

GITHUB_PROJECT=	taskctl
DISTNAME=	taskctl-1.2.2
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=taskctl/}
GITHUB_RELEASE=	v1.2.2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/taskctl/taskctl/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
