# $NetBSD$

VERSION=	5.15.2
DISTNAME=	pyside-setup-opensource-src-5.15.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAMES:/-setup-opensource-src//}
CATEGORIES=	devel
MASTER_SITES=	https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.15.2-src/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	rumko@netbsd.org
HOMEPAGE=	Pyside Qt bindings for Python
COMMENT=	TODO: Short description of the package
LICENSE=	gnu-gpl-v2

#https://svnweb.freebsd.org/ports/head/devel/pyside2/Makefile?revision=557444&view=markup 
# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
