# $NetBSD$

DISTNAME=	diver-1.0.5
GITHUB_PROJECT=	Diver
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=patscott/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/patscott/Diver/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/Diver-1.0.5
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
