# $NetBSD$

DISTNAME=	diver-1.0.5
GITHUB_PROJECT=	Diver
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=patscott/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://diver.hepforge.org/
COMMENT=	Public Package for Differential Evolution 
LICENSE=	modified-bsd

WRKSRC=		${WRKDIR}/Diver-1.0.5

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
