# $NetBSD$

DISTNAME=	SusHi-1.7.0
CATEGORIES=	category
MASTER_SITES=	https://sushi.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://sushi.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LANGUAGES=	fortran
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
