# $NetBSD$

DISTNAME=	SusHi-1.7.0
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	category
MASTER_SITES=	https://sushi.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://sushi.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LANGUAGES=	fortran
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
