# $NetBSD$

GITHUB_PROJECT=	zap
GITHUB_TAG=	v1.16.0
DISTNAME=	v1.16.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=uber-go/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/uber-go/zap/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/zap-1.16.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
