# $NetBSD$

DISTNAME=	mathopt-0.1.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/03/5c/65462624451004dccc4118c198e1802a8ce6c32792d36be84fe0bf69e40e/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/CalebBell/mathopt
COMMENT=	Library for mathematical optimization for sympy
LICENSE=	mit

DEPENDS+=	py-sympy>=0:../../math/py-sympy

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
