# $NetBSD$

DISTNAME=	mathlink
CATEGORIES=	math
MASTER_SITES=	http://www.feynarts.de/mathlink/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://www.feynarts.de/mathlink/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	fortran

.include "../../mk/bsd.pkg.mk"
