# $NetBSD$

DISTNAME=	native-image-installable-svm-java11-linux-aarch64-20.2.0
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/}
EXTRACT_SUFX=	.jar

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/ # TODO: check
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
