# $NetBSD$

DISTNAME=	T3PS-1.0.2
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	parallel
MASTER_SITES=	https://t3ps.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://t3ps.hepforge.org/
COMMENT=	Tool for Parallel Processing in Parameter Scans
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
