# $NetBSD$

DISTNAME=	go-copier-0.1.0
GITHUB_PROJECT=	copier
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=jinzhu/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/jinzhu/copier/
COMMENT=	Copier for golang, copy value from struct to struct and more
LICENSE=	mit

WRKSRC=		${WRKDIR}/copier-0.1.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
