# $NetBSD$

DISTNAME=	fermilibpluginpyscf-0.1a0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/b4/7e/7287bd88f93325faa4c5e8c2a490d9bf7f75bc5aea236399bc5581e468b6/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.projectq.ch
COMMENT=	A plugin allowing FermiLib to interface with PySCF
LICENSE=	apache-2.0

DEPENDS+=	# TODO: fermilib>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
