# The first propagator is the result of applying the Feynman trick to 
# 1 / ( (k1^2 - m2)^2 ) / ( (k1 + p1)^2 ). 
# The 4th propagator k1^2 is an auxiliary propagator.
integralfamilies:
  - name: "box"
    loop_momenta: [k1]
    top_level_sectors: [7]
    propagators:
      - [ "k1^2 + 2*k1*p1 + p1^2 + (-m2 - 2*k1*p1 - p1^2)*x", 0] #1
      - [ "(k1+p1+p2)^2-m2", 0]     #2
      - [ "(k1+p1+p2+p3)^2", 0]     #3
      - [ "k1^2", 0]                #4
