integralfamilies:
  - name: "topbox"
    loop_momenta: [k1, k2]
    top_level_sectors: [93]
    magic_relations: true
    propagators:
      - [ "k1+p2",    "m2" ]
      - [ "k1",       "m2" ]
      - [ "k1+p2+p1", "m2" ]
      - [ "k1+k2",    "m2" ]
      - [ "k2",          0 ]
      - [ "k2+p3+p4",    0 ]
      - [ "k2+p3",    "m2" ]
      - [ "k1+p2-p3", "m2" ]
      - [ "k2-p2+p3",    0 ]
