kinematics :
  incoming_momenta: []
  outgoing_momenta: [p1, p2, p3,p4]
  momentum_conservation: [p4,-p1-p2-p3]
  kinematic_invariants:
    - [m2, 2]
    - [s,  2]
    - [t,  2]
  scalarproduct_rules:
    - [[p1,p1],  0]
    - [[p2,p2],  0]
    - [[p3,p3],  m2]
    - [[p1+p2,p1+p2],  s]
    - [[p2+p3,p2+p3],  t]
    - [[p1+p3,p1+p3],  -s-t+2*m2]
  symbol_to_replace_by_one: m2
