# $NetBSD$

DISTNAME=	parver-0.3.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/dd/7d/5e4ad784f4cdabab244487f543876a8887f28f162bbb925f8b73b4411dfb/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/RazerM/parver
COMMENT=	Parse and manipulate version numbers
LICENSE=	mit

DEPENDS+=	# TODO: arpeggio~=1.7>=0
DEPENDS+=	py-attrs>=19.2:../../devel/py-attrs
DEPENDS+=	# TODO: six~=1.13>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
