# $NetBSD$

DISTNAME=	starlette-0.13.8
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	www python
MASTER_SITES=	https://files.pythonhosted.org/packages/86/f5/2713195e0d2f449554f3e0b749cc9d8ec5d00035279d6dfa02d4410adcbd/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/encode/starlette
COMMENT=	The little ASGI library that shines
LICENSE=	modified-bsd

PYTHON_VERSIONS_INCOMPATIBLE=	27

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
