# $NetBSD$

DISTNAME=	geopandas-0.8.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/c7/b2/ba3c57affe4acf1a8b39ee4fc0d281b4a0c8dd51466af8326bcd5f07108a/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/c7/b2/ba3c57affe4acf1a8b39ee4fc0d281b4a0c8dd51466af8326bcd5f07108a/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
