# $NetBSD$

DISTNAME=	datastructures-20200309
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	go-datastructures
GITHUB_TAG=	0819bcaf26091e7c33585441f8961854c2400faa
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=Workiva/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Workiva/go-datastructures/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-datastructures-0819bcaf26091e7c33585441f8961854c2400faa
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
