# $NetBSD$

DISTNAME=	fermilibpluginpsi4-0.1a1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/1e/13/2d9ac1a1bf645a82005bab72d877a66415559e58ab635c2cf52fbe1327af/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.projectq.ch
COMMENT=	A plugin allowing FermiLib to interface with Psi4
#LICENSE=	GNU Lesser General Public License (LGPL), Version 3 or any later version # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: fermilib>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
