# $NetBSD$

DISTNAME=	code-1.47.3-1595520197.el7.x86_64
CATEGORIES=	editor
MASTER_SITES=	https://az764295.vo.msecnd.net/stable/91899dcef7b8110878ea59626991a18c8a6a1b3e/
EXTRACT_SUFX=	.rpm

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://az764295.vo.msecnd.net/stable/91899dcef7b8110878ea59626991a18c8a6a1b3e/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/usr
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
