# $NetBSD$

DISTNAME=	pymanopt-0.2.5
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/54/62/8d674b68e5034ec5cb343dde3d5afeb7a667ff77f64f130c9c6200e0f919/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/54/62/8d674b68e5034ec5cb343dde3d5afeb7a667ff77f64f130c9c6200e0f919/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
