# $NetBSD$

DISTNAME=	taskctl-1.2.2                                                               
MASTER_SITES=   ${MASTER_SITE_GITHUB:=taskctl/}                                              
CATEGORIES=     databases                                                                   
GITHUB_TAG=     v${PKGVERSION_NOREV}                                                        

MAINTAINER=     kamelderouiche@yahoo.com
HOMEPAGE=       https://github.com/taskctl/taskctl/
COMMENT=        TODO: Short description of the package
#LICENSE=       # TODO: (see mk/license.mk)

GO_DIST_BASE=   ${DISTNAME}                                                                 
GO_SRCPATH=     github.com/taskctl/taskctl/

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
