# $NetBSD$

GITHUB_PROJECT=	taskctl
DISTNAME=	taskctl-1.3.0
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=taskctl/}
GITHUB_RELEASE=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/taskctl/taskctl/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR} # TODO: one of autocomplete cmd docs internal pkg, or leave it as-is
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
