# $NetBSD$

GITHUB_PROJECT=	sh
GITHUB_TAG=	v3.1.2
DISTNAME=	v3.1.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=mvdan/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/mvdan/sh/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/sh-3.1.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
