# $NetBSD$

DISTNAME=	susyai
CATEGORIES=	category
MASTER_SITES=	https://susyai.hepforge.org/downloads/
EXTRACT_SUFX=	.tar

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://susyai.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/examples

VERSION=	1.1.5
USE_LANGUAGES=	# none

.include "../../lang/python/application.mk"
.include "../../mk/bsd.pkg.mk"
