# $NetBSD$

DISTNAME=	TemplateOverlap-1.0.3
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	math
MASTER_SITES=	http://www.hepforge.org/archive/tom/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://tom.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++

.include "../../wip/fastjet/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
