# $NetBSD$

DISTNAME=	TemplateOverlap-1.0.3
CATEGORIES=	category
MASTER_SITES=	http://www.hepforge.org/archive/tom/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.hepforge.org/archive/tom/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
