# $NetBSD$

DISTNAME=	go-fyne-1.4.2
GITHUB_PROJECT=	fyne
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_GITHUB:=fyne-io/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://fyne.io/
COMMENT=	Cross platform GUI in Go based on Material Design
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=	github.com/fyne-io/fyne/
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
