# $NetBSD$

DISTNAME=	vmprof-0.4.15
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/db/f7/f07e859a0239690668e9a39d699b32f9d683563b16317e6c86c49a32fb92/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://vmprof.readthedocs.io/en/latest/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
