# Module dependencies
amp3.o: mtopo3.o
amp3.lo: mtopo3.lo
amp3.obj: mtopo3.obj
mtopo3.o: vars.o
mtopo3.lo: vars.lo
mtopo3.obj: vars.obj
process.o: amp3.o rambo.o vars.o
process.lo: amp3.lo rambo.lo vars.lo
process.obj: amp3.obj rambo.obj vars.obj
