# $NetBSD$

GITHUB_PROJECT=	docopt.go
GITHUB_TAG=	0.6.2
DISTNAME=	0.6.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=docopt/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/docopt/docopt.go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/docopt.go-0.6.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
