# $NetBSD$

DISTNAME=	docopt-20180112
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	docopt.go
GITHUB_TAG=	ee0de3bc6815ee19d4a46c7eb90f829db0e014b1
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=docopt/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/docopt/docopt.go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=   ${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=     github.com/docopt/${GITHUB_PROJECT}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
