# $NetBSD$

DISTNAME=	go-docopt-0.6.2
GITHUB_PROJECT=	docopt.go
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=docopt/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/docopt/docopt.go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
