# $NetBSD$

DISTNAME=	ukui-paste-20201225
GITHUB_PROJECT=	ukui-paste
GITHUB_TAG=	f74de1e407f5993d689e641aa027a5c91d6a0d37
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/ukui-paste
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ukui-paste-f74de1e407f5993d689e641aa027a5c91d6a0d37

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
