# $NetBSD$

DISTNAME=	pygalmesh-0.7.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/f5/34/fd64302fe0432c794aae7b3d213001cdd0acd5392b96a7be7c22647db8ea/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/f5/34/fd64302fe0432c794aae7b3d213001cdd0acd5392b96a7be7c22647db8ea/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c++

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
