# $NetBSD$

DISTNAME=	go-aws-sdk-go-20210112
GITHUB_PROJECT=	aws-sdk-go
GITHUB_TAG=	c2934dc12c9504f4661a84aa2fb84c5a8b1f5f31
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=aws/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/aws/aws-sdk-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
