# $NetBSD$

DISTNAME=	proVBFH-1.2.1
CATEGORIES=	category
MASTER_SITES=	https://provbfh.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://provbfh.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

HAS_CONFIGURE=	yes
USE_LANGUAGES=	c++ fortran
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
