# $NetBSD$

DISTNAME=	proVBFH-1.2.1
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	math
MASTER_SITES=	https://provbfh.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://provbfh.hepforge.org/
COMMENT=	Monte Carlo program for the calculation of differential distributions
#LICENSE=	# TODO: (see mk/license.mk)

HAS_CONFIGURE=	yes
USE_LANGUAGES=	c++ fortran
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
