# $NetBSD$

DISTNAME=	go-unipdf-3.17.0
GITHUB_PROJECT=	unipdf
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=unidoc/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/unidoc/unipdf/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/unipdf-3.17.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
