# $NetBSD$

GITHUB_PROJECT=	unipdf
GITHUB_TAG=	v3.12.1
DISTNAME=	v3.12.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=unidoc/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/unidoc/unipdf/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/unipdf-3.12.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
