# $NetBSD$

DISTNAME=	PythonQwt-0.8.3
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/56/ba/36b5a31dc89cc634ec11a50bb2f555c384efbfdf0e801f2314d28337d323/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/56/ba/36b5a31dc89cc634ec11a50bb2f555c384efbfdf0e801f2314d28337d323/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
