# $NetBSD$

GITHUB_PROJECT=	wails
GITHUB_TAG=	v1.7.2-pre3
DISTNAME=	v1.7.2-pre3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=wailsapp/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/wailsapp/wails/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/wails-1.7.2-pre3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
