# $NetBSD$

DISTNAME=	scitrack-2020.6.5
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=s/scitrack/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/HuttleyLab/scitrack
COMMENT=	One of the critical challenges in scientific analysis is to track all the elements involved
#LICENSE=	# TODO: (see mk/license.mk)


.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
