integralfamilies:
  - name: "topo7"
    loop_momenta: [k1,k2]
    top_level_sectors: [b111111100] # same as sector 127
    propagators:
      - [ "-k1", 0]         #1
      - [ "k2", 0]          #2
      - [ "-k1+k2", 0]      #3
      - [ "k1+q2", "m22"]   #4
      - [ "k2-p2", 0]       #5
      - [ "-k1+p1+p2", 0]   #6
      - [ "k2-p1-p2", 0]    #7
      - [ "k1-p2", 0]       #8
      - [ "k2-q2", 0]       #9
    #cut_propagators: [3,4] #uncomment to use the option cut_propagators
  - name: "topo7x"
    # This is the same topology as topo7, just with the propagators permuted
    # to demonstrate that the symmetry finder will map all sectors of topo7x on topo7.
    loop_momenta: [k1,k2]
    top_level_sectors: [b001111111] # same as sector 508
    propagators:
      - [ "k1-p2", 0]       #8->1
      - [ "k2-q2", 0]       #9->2
      - [ "-k1", 0]         #1->3
      - [ "k2", 0]          #2->4
      - [ "k1+q2", "m22"]   #4->5
      - [ "k2-p2", 0]       #5->6
      - [ "-k1+k2", 0]      #3->7
      - [ "k2-p1-p2", 0]    #7->8
      - [ "-k1+p1+p2", 0]   #6->9
    #cut_propagators: [5,7] #uncomment to use the option cut_propagators
