# $NetBSD$

VERSION=	1.14.2
DISTNAME=	brackets
PKGNAME=	${DISTNAME}-${VERSION}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=adobe/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/adobe/brackets/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

WRKSRC=		${WRKDIR}/brackets-release-1.14.2

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
