# $NetBSD$

VERSION=	1.14.2
DISTNAME=	brackets
PKGNAME=	${DISTNAME}-${VERSION}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=adobe/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://brackets.io/
COMMENT=	Editor for the web, written in JavaScript, HTML and CSS
LICENSE=	mit

WRKSRC=		${WRKDIR}/brackets-release-1.14.2

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
