# $NetBSD$

DISTNAME=	go-mpb-5.4.0
GITHUB_PROJECT=	mpb
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	multimedia
MASTER_SITES=	${MASTER_SITE_GITHUB:=vbauerster/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/vbauerster/mpb/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=	github.com/vbauerster/mpbvbauerster
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
