# $NetBSD$

DISTNAME=	go-mpb-5.4.0
GITHUB_PROJECT=	mpb
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=vbauerster/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/vbauerster/mpb/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/mpb-5.4.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
