# $NetBSD$

GITHUB_PROJECT=	seed
GITHUB_TAG=	v0.2.2
DISTNAME=	v0.2.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=qlova/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/qlova/seed/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/seed-0.2.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
