# $NetBSD$

DISTNAME=	python-qnotifications-2.0.5
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/python-//}
CATEGORIES=	sysutils x11 python
MASTER_SITES=   ${MASTER_SITE_PYPI:=p/python-qnotifications/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/open-cogsci/QNotifications
COMMENT=	Pretty in-app notifications for PyQt
LICENSE=	gnu-lgpl-v3

#DEPENDS+=	${PYPKGPREFIX}-qtpy>=1.1.1:../../wip/py-qtpy

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
