# $NetBSD$

DISTNAME=	python-debianbts-3.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/c9/44/6b7870385d66d4f8676c205b5e2d0e0e366b8a667538243e706aaa2ee25c/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/venthur/python-debianbts
COMMENT=	Python interface to Debian's Bug Tracking System
LICENSE=	mit

BUILD_DEPENDS+=	# TODO: pytest>=0
BUILD_DEPENDS+=	# TODO: pytest-cov>=0
BUILD_DEPENDS+=	py-flake8>=0:../../devel/py-flake8
DEPENDS+=	# TODO: pysimplesoap>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
