# $NetBSD$

DISTNAME=	go-plot-0.8.1
GITHUB_PROJECT=	plot
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gonum/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gonum/plot/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
