# $NetBSD$

DISTNAME=	gsettings-desktop-schemas-3.37.92
CATEGORIES=	# TODO: add primary category
MASTER_SITES=	${MASTER_SITE_GNOME:=sources/gsettings-desktop-schemas/3.37/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=     pkgsrc-users@NetBSD.org
HOMEPAGE=       https://www.gnome.org/
COMMENT=        Collection of GSettings schemas for the GNOME desktop
LICENSE=	

USE_TOOLS+=             msgfmt pkg-config

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
