# $NetBSD$

DISTNAME=	ArabicOcr-1.1.6
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/b2/01/794501bd1c5903540763225b142f1a6b94cccd3583cb776c7324b4a952f4/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://iraqprogrammer.wordpress.com/
COMMENT=	Python package to convert Arabic images to text by OCR technique detection
#LICENSE=	# TODO: (see mk/license.mk)

DEPENDS+=	# TODO: easyocr>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
