# $NetBSD$

DISTNAME=	holoviz-0.11.6
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/a2/90/a1d1e3ed32c6ec1d52b5adb9effeb0b706dfe734b5306e30c1e055d05d01/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/a2/90/a1d1e3ed32c6ec1d52b5adb9effeb0b706dfe734b5306e30c1e055d05d01/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
