# $NetBSD$

DISTNAME=	go-dkron-3.1.1
GITHUB_PROJECT=	dkron
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=distribworks/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/distribworks/dkron/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/dkron-3.1.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
