# $NetBSD$

GITHUB_PROJECT=	dkron
GITHUB_TAG=	v3.0.5
DISTNAME=	v3.0.5
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=distribworks/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/distribworks/dkron/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/dkron-3.0.5
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
