# $NetBSD$

DISTNAME=	mrio_common_metadata-0.1.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/e0/39/f5790f76e3c5c83e842f2d262968cd7f694a455b563ca6cd81305713f077/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/brightway-lca/mrio_common_metadata
COMMENT=	Common Datapackage schema and utilities for MRIO tables
#LICENSE=	BSD 3-clause # TODO: from setup.py; needs to be adjusted

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
