# $NetBSD$

DISTNAME=	go-streamquote-1.0.0
GITHUB_PROJECT=	streamquote
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=nkovacs/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/nkovacs/streamquote/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/streamquote-1.0.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
