# $NetBSD$

DISTNAME=	STRINGS-2.00
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	category
MASTER_SITES=	https://strings.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://strings.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
