# $NetBSD$

DISTNAME=	weblate_fedora_messaging-0.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/91/db/e4272c6d43c6da6d065a51391918d8d6d2be18de63c8373bc690ee8e2dd2/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/91/db/e4272c6d43c6da6d065a51391918d8d6d2be18de63c8373bc690ee8e2dd2/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
