# $NetBSD$

DISTNAME=	python-json-logger-2.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/python-json-logger/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://github.com/madzak/python-json-logger
COMMENT=	Python library adding a json log formatter
LICENSE=	modified-bsd


.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
