# $NetBSD$

DISTNAME=	python-json-logger-2.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/bd/95/ccbae460a4db2610b8d2635b5f1e7ed146fb771f4ef47ef20a1f216f9b78/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/madzak/python-json-logger
COMMENT=	A python library adding a json log formatter
#LICENSE=	BSD # TODO: from setup.py; needs to be adjusted

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
