# $NetBSD$

DISTNAME=	factory_boy-3.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/b5/b8/595a6447eed1f9fecdc490c9dca3e1b376700f1bbfc33ab1aa748397e9a5/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/b5/b8/595a6447eed1f9fecdc490c9dca3e1b376700f1bbfc33ab1aa748397e9a5/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
