# $NetBSD$

DISTNAME=	go-vtclean-20201209
GITHUB_PROJECT=	vtclean
GITHUB_TAG=	54bb1ba73a3e731f867d4aafb0a145959c7d4e4f
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=lunixbochs/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/lunixbochs/vtclean/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/vtclean-54bb1ba73a3e731f867d4aafb0a145959c7d4e4f
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
