# $NetBSD$

DISTNAME=	go-vtclean-20201209
GITHUB_PROJECT=	vtclean
GITHUB_TAG=	54bb1ba73a3e731f867d4aafb0a145959c7d4e4f
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=lunixbochs/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/lunixbochs/vtclean/
COMMENT=	Strips terminal escapes from text can preserve color
LICENSE=	mit

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=	https://github.com/lunixbochs/vtclean

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
