# $NetBSD$

DISTNAME=	pipenv-setup-3.1.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/f4/e3/ca526f475aac45eaa2d0e55370a498ed4a277aef0185553016e5d69b4aaa/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Madoshakalaka/pipenv-setup
COMMENT=	sync Pipfile/Pipfile.lock to setup.py
LICENSE=	mit

BUILD_DEPENDS+=	# TODO: pytest~=5.2;python_version>='3.6'
BUILD_DEPENDS+=	# TODO: pytest-mypy~=0.3;python_version>='3.5'
BUILD_DEPENDS+=	# TODO: pytest-cov~=2.7>=0
BUILD_DEPENDS+=	# TODO: pytest-datadir~=1.3>=0
BUILD_DEPENDS+=	# TODO: pytest-xdist~=1.29>=0
BUILD_DEPENDS+=	# TODO: tox~=3.14>=0
BUILD_DEPENDS+=	# TODO: autopep8~=1.4>=0
DEPENDS+=	# TODO: pipfile~=0.0>=0
DEPENDS+=	# TODO: black==19.10b0;python_version>='3.6'
DEPENDS+=	# TODO: colorama~=0.4>=0
DEPENDS+=	# TODO: packaging~=20.0>=0
DEPENDS+=	# TODO: requirementslib~=1.5>=0
DEPENDS+=	# TODO: vistir~=0.4>=0
DEPENDS+=	# TODO: autopep8~=1.4;python_version<'3.6'>=0
DEPENDS+=	# TODO: six~=1.12>=0
DEPENDS+=	# TODO: typing~=3.7;python_version<'3.7'>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
