# $NetBSD$

DISTNAME=	murmurhash2-0.2.7
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	security devel
MASTER_SITES=	${MASTER_SITE_PYPI:=m/murmurhash2/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://pypi.org/project/murmurhash2/
COMMENT=	Murmurhash2 for Python
LICENSE=	mit

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
