integralfamilies:
  - name: higgs3l7_00mm0000m
    top_level_sectors: [511]
    loop_momenta: [ l1, l2, l3 ]
    propagators:
      - [ "l1", 0 ]
      - [ "l2", 0 ]
      - [ "l3", "m^2" ]
      - [ "l3 - q1 - q2", "m^2" ]
      - [ "l2 - q1 - q2", 0 ]
      - [ "l1 - q1", 0 ]
      - [ "-l1 + l2", 0 ]
      - [ "l1 - l2 + q2", 0 ]
      - [ "l2 - l3", "m^2" ]
      - { bilinear: [ [ "l1", "l3" ], 0 ] }
      - { bilinear: [ [ "l2", "q1" ], 0 ] }
      - { bilinear: [ [ "l3", "q1" ], 0 ] }
  - name: higgs3l11_00mm0000m
    top_level_sectors: [511]
    loop_momenta: [ l1, l2, l3 ]
    propagators:
      - [ "l1", 0 ]
      - [ "l2", 0 ]
      - [ "l3", "m^2" ]
      - [ "l3 - q1 - q2", "m^2" ]
      - [ "l2 - q1 - q2", 0 ]
      - [ "l1 - q1 - q2", 0 ]
      - [ "l1 - q1", 0 ]
      - [ "l1 - l2", 0 ]
      - [ "l2 - l3", "m^2" ]
      - { bilinear: [ [ "l1", "l3" ], 0 ] }
      - { bilinear: [ [ "l2", "q1" ], 0 ] }
      - { bilinear: [ [ "l3", "q1" ], 0 ] }
