# $NetBSD$

DISTNAME=	sympyle-0.0.12-py3-none-any
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/fc/e0/da188863dcf199abb9813b0a9c162e7555462a40b1dfb9f9520669fc2519/
EXTRACT_SUFX=	.whl

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/fc/e0/da188863dcf199abb9813b0a9c162e7555462a40b1dfb9f9520669fc2519/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
