# $NetBSD$

DISTNAME=	flint-2.6.3
CATEGORIES=	math
MASTER_SITES=	http://www.flintlib.org/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://www.flintlib.org/
COMMENT=	TODO: Short description of the package
LICENSE=	gnu-lgpl-v2.1

HAS_CONFIGURE=	yes
USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../devel/gmp/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
