# $NetBSD$

DISTNAME=	cashocs-1.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/de/a3/426e89b193cebe513ebf9efde63f56a9590ab391779a898a2f4d3ef9b452/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/sblauth/cashocs
COMMENT=	Computational Adjoint-Based Shape Optimization and Optimal Control Software
#LICENSE=	# TODO: (see mk/license.mk)

DEPENDS+=	# TODO: pytest>=6.0.0
DEPENDS+=	# TODO: meshio>=4.1.0
DEPENDS+=	py-matplotlib>=0:../../graphics/py-matplotlib

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
