# $NetBSD$

DISTNAME=	beebeep-5.8.2-qt5-amd64
PKGNAME=	${DISTNAME:S/-qt5-amd64//}-bin
CATEGORIES=	chat
MASTER_SITES=	https://deac-ams.dl.sourceforge.net/project/beebeep/Linux/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.beebeep.net/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
