# $NetBSD$

DISTNAME=	go-xurls-2.2.0
GITHUB_PROJECT=	xurls
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=mvdan/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/mvdan/xurls/
COMMENT=	Extract urls from text
LICENSE=	2-clause-bsd

GO_DIST_BASE=	xurls-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/mvdan/xurls

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
