# $NetBSD$

DISTNAME=	pyptex-1.0.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/03/a9/69448ed93c993c9752d5d31ce5e8918b13dd0fc685bbe474a3f9b2411a13/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/03/a9/69448ed93c993c9752d5d31ce5e8918b13dd0fc685bbe474a3f9b2411a13/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
