# $NetBSD$

DISTNAME=	qtmodern-0.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	x11 python
MASTER_SITES=	https://files.pythonhosted.org/packages/e3/17/bc8a3882571e852e96d79b8c5a6989f72e2b7eda22998cd6018bfc5644fb/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.github.com/gmarull/qtmodern
COMMENT=	Qt Widgets Modern User Interface
LICENSE=	mit

DEPENDS+=	${PYPKGPREFIX}-qtpy>=1.3.1:../../wip/py-qtpy

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
