# $NetBSD$

DISTNAME=	go-gg-1.3.0
GITHUB_PROJECT=	gg
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_GITHUB:=fogleman/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/fogleman/gg/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gg-1.3.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
