# $NetBSD$

DISTNAME=	aiohttp-jinja2-1.4.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc www
MASTER_SITES=	https://files.pythonhosted.org/packages/be/cf/2fecf127b910d3ae2a6d1e744b814d3e8bc4985888da78b6350a02d429c4/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://aiohttp-jinja2.readthedocs.io/en/stable/
COMMENT=	Jinja2 template renderer for aiohttp.web
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
