integralfamilies:
  - name: "box"
    loop_momenta: [k1]
    top_level_sectors: [15]
    propagators:
      - [ "k1",       m2] #1
      - [ "k1+p1",     0] #2
      - [ "k1+p1+p2", m2] #3
      - [ "k1+p1+p2+p3",     0] #4
    #cut_propagators: [3,4] # uncomment to use the option cut_propagators
