# $NetBSD$

DISTNAME=	ortools-8.1
GITHUB_PROJECT=	or-tools
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=google/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/google/or-tools/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/or-tools-8.1
USE_CMAKE=	yes
USE_LANGUAGES=	c++
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
