# $NetBSD$

DISTNAME=	SecretStorage-3.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:tl}
CATEGORIES=	security python
MASTER_SITES=	${MASTER_SITE_PYPI:=s/SecretStorage/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

jeepney-0.5.0
cryptography

do-test:
 ${RUN}

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
