# $NetBSD$

DISTNAME=	tdelibs-trinity-14.0.8
CATEGORIES=	category
MASTER_SITES=	http://mirror.ppa.trinitydesktop.org/trinity/releases/R14.0.8/main/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://mirror.ppa.trinitydesktop.org/trinity/releases/R14.0.8/main/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../devel/libltdl/convenience.mk"
.include "../../mk/bsd.pkg.mk"
