# $NetBSD$

DISTNAME=	go-cascadia-1.0.0
GITHUB_PROJECT=	cascadia
GITHUB_TAG=	v1.6.0
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=andybalholm/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/andybalholm/cascadia/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/cascadia-1.0.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
