# $NetBSD$

DISTNAME=	go-svu-1.2.0
GITHUB_PROJECT=	svu
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=caarlos0/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/caarlos0/svu/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=   ${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=     github.com/caarlos0/svu/

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
