# $NetBSD$

GITHUB_PROJECT=	kit
GITHUB_TAG=	v0.10.0
DISTNAME=	v0.10.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-kit/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go-kit/kit/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/kit-0.10.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
