# $NetBSD$

DISTNAME=	ninja-1.1.0
CATEGORIES=	category
MASTER_SITES=	http://www.hepforge.org/archive/ninja/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ninja.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
