# $NetBSD$

DISTNAME=	nusigma-1.19-pyr
PKGNAME=	nusigma-pyr-1.19
CATEGORIES=	math
MASTER_SITES=	http://wimpsim.astroparticle.se/code/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://wimpsim.astroparticle.se/
COMMENT=	Neutrino-nucleon Monte Carlo
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_TOOLS+=	gmake perl
USE_LANGUAGES=	c c++ fortran
MAKE_FILE=	makefile

.include "../../mk/bsd.pkg.mk"
