# $NetBSD$

DISTNAME=	HiggsSignals-2.2.3beta
PKGNAME=	${DISTNAME:tl:S/beta//}
CATEGORIES=	math
MASTER_SITES=	https://higgsbounds.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://higgsbounds.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

HAS_CONFIGURE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
