# $NetBSD$

DISTNAME=	wasserplan-0.1.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/d7/de/7ee348e72d3fcf82a328d7d24e523426dac437c31672fdaf296e10bda480/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/vrdi/geometry-of-graph-partitions
COMMENT=	1-Wasserstein distances between districting plans
#LICENSE=	# TODO: (see mk/license.mk)

DEPENDS+=	# TODO: gerrychain>=0
DEPENDS+=	${PYPKGPREFIX}-cvxpy>=0:../../wip/py-cvxpy

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
