# $NetBSD$

DISTNAME=	mpi4py-fft-2.0.3
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/d4/59/5079ab912dbc67d348e4702c2fdd28226cc7cf32687ae3212557057715b5/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/d4/59/5079ab912dbc67d348e4702c2fdd28226cc7cf32687ae3212557057715b5/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
