# $NetBSD$

DISTNAME=	changelog-go-v1.2.1
PKGNAME=	${DISTNAME:S,-v,-,}
CATEGORIES=	category
MASTER_SITES=	https://gitlab.com/l0nax/changelog-go/-/archive/v1.2.1/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://gitlab.com/l0nax/changelog-go/-/archive/v1.2.1/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
