# $NetBSD$

DISTNAME=	webcam-20200313
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	webcam
GITHUB_TAG=	10ed912a85397a1102d3a21887d5c66054431ffa
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=blackjack/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/blackjack/webcam/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/webcam-10ed912a85397a1102d3a21887d5c66054431ffa
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
