# $NetBSD$

DISTNAME=	go-ole-1.2.0
GITHUB_PROJECT=	go-ole
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-ole/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go-ole/go-ole/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
