# $NetBSD$

DISTNAME=	iris-20210125
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	iris
GITHUB_TAG=	197df1ef64f9d7cc34e7e6d6681148edd5186572
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kataras/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kataras/iris/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=	github.com/kataras/${GITHUB_PROJECT}

.include "../../mk/bsd.pkg.mk"
