# $NetBSD$

DISTNAME=	iris-20200913
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	iris
PKGREVISION=	1
GITHUB_TAG=	a917ef68fc401f5ca8f421fba50db4e129966b52
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kataras/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kataras/iris/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=	github.com/kataras/${GITHUB_PROJECT}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
