# $NetBSD$

DISTNAME=	bw2parameters-0.6.6
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/0e/00/20eb83c0844a47b844ec036397bc54a3b35c781b08817865e18c4075e375/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://bitbucket.org/cmutel/brightway2-parameters
COMMENT=	TODO: Short description of the package
#LICENSE=	Copyright (c) 2016, Chris Mutel and Paul Scherrer Institut.

DEPENDS+=	py-asteval>=0:../../math/py-asteval
DEPENDS+=	py-astunparse>=0:../../wip/py-astunparse
DEPENDS+=	# TODO: numpy>=0
DEPENDS+=	# TODO: stats_arrays>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
