# $NetBSD$

GITHUB_PROJECT=	npefix
GITHUB_TAG=	v0.5
DISTNAME=	v0.5
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=SpoonLabs/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/SpoonLabs/npefix/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/npefix-0.5
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
