d # $NetBSD$

GITHUB_PROJECT=	npefix
GITHUB_TAG=	v0.5
DISTNAME=	${GITHUB_TAG}
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=SpoonLabs/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/SpoonLabs/npefix/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/npefix-0.5

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
