# $NetBSD$

DISTNAME=	go-opencensus-0.22.5
GITHUB_PROJECT=	opencensus-go
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=census-instrumentation/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/census-instrumentation/opencensus-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/opencensus-go-0.22.5
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
