# $NetBSD$

DISTNAME=	go-jet-6.0.2
GITHUB_PROJECT=	jet
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=CloudyKit/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/CloudyKit/jet/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=   ${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=     github.com/CloudyKit/${GITHUB_PROJECT}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
