# $NetBSD$

DISTNAME=	krakend-1.2.0
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	krakend
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=devopsfaith/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.krakend.io/
COMMENT=	Ultra performant API Gateway with middlewares
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
