# $NetBSD$

DISTNAME=	tebata-20180602
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	tebata
GITHUB_TAG=	b283fe4bc5baae2724724077b1ca027b0dd9f0cc
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=syossan27/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/syossan27/tebata
COMMENT=	Simple linux signal handler for golang
LICENSE=	mit

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=	github.com/syossan27/tebata

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
