# $NetBSD$

DISTNAME=	go-email-4.0.0
GITHUB_PROJECT=	email
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=jordan-wright/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/jordan-wright/email/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/email-4.0.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
