# $NetBSD$

DISTNAME=	Yandex
CATEGORIES=	category
MASTER_SITES=	https://cache-man01i.cdn.yandex.net/download.cdn.yandex.net/browser/beta-public/20_4_3_268_12047/
EXTRACT_SUFX=	.rpm

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://cache-man01i.cdn.yandex.net/download.cdn.yandex.net/browser/beta-public/20_4_3_268_12047/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR} # TODO: one of etc opt usr, or leave it as-is
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
