# $NetBSD$

DISTNAME=	GrTiPy-0.1.0
PKGNAME=	${PYPKGPREFIX}-grtipy-0.1.0
CATEGORIES=	math
MASTER_SITES=	https://files.pythonhosted.org/packages/e3/1d/1eb17b9945fbc16c414983d8dd920b8fd2e7266df332b054922de762c801/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/e3/1d/1eb17b9945fbc16c414983d8dd920b8fd2e7266df332b054922de762c801/
COMMENT=	General Relativity toolbox in python
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
