# $NetBSD$

DISTNAME=	cover-thumbnailer_0.8.3_src
CATEGORIES=	category
MASTER_SITES=	https://launchpad.net/cover-thumbnailer/v0.8/v0.8.3/+download/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://launchpad.net/cover-thumbnailer/v0.8/v0.8.3/+download/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		# none

.include "../../mk/bsd.pkg.mk"
