# $NetBSD$

GITHUB_PROJECT=	mediadevices
GITHUB_TAG=	v0.1.5
DISTNAME=	v0.1.5
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	multimedia
MASTER_SITES=	${MASTER_SITE_GITHUB:=pion/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/pion/mediadevices/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

WRKSRC=		${WRKDIR}/mediadevices-0.1.5

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
