# $NetBSD$

GITHUB_PROJECT=	mediadevices
GITHUB_TAG=	v0.1.5
DISTNAME=	v0.1.5
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=pion/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/pion/mediadevices/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/mediadevices-0.1.5
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
