# $NetBSD$

DISTNAME=	qt_thread_updater-1.1.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/b5/2c/072bca49689ec2a4d225bb0a14c8d0a626721e0036c2b1ff14aad19da373/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/justengel/qt_thread_updater
COMMENT=	Python Qt thread updater to update GUI items using a separate thread
LICENSE=	mit

DEPENDS+=	# TODO: QtPy>=1.9.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
