# $NetBSD$

DISTNAME=	ghw
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=jaypipes/}
EXTRACT_SUFX=	# none

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/jaypipes/ # TODO: check
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
