# $NetBSD$

DISTNAME=	go-ghw-0.6.1
GITHUB_PROJECT=	ghw
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=jaypipes/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/jaypipes/ghw/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=     github.com/jaypipes/ghw
GO_DIST_BASE=   ${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../mk/bsd.pkg.mk"
