# $NetBSD$

DISTNAME=	httpie-jwt-auth-0.4.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	www
MASTER_SITES=	https://files.pythonhosted.org/packages/ee/f8/8a7c5169c042e83d1fc22bc3cdafe993e5b94e0c0918cb9ebd6fcce2269c/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/ee/f8/8a7c5169c042e83d1fc22bc3cdafe993e5b94e0c0918cb9ebd6fcce2269c/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
