# $NetBSD$

DISTNAME=	SymEnergy-1.0.7
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/47/20/5af6911dbd914cf9d4e507e6f209f7e03aad22db0f74a48a7185b6a34f5b/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/47/20/5af6911dbd914cf9d4e507e6f209f7e03aad22db0f74a48a7185b6a34f5b/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
