# $NetBSD$

GITHUB_PROJECT=	uilive
GITHUB_TAG=	v0.0.4
DISTNAME=	v0.0.4
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gosuri/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gosuri/uilive/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/uilive-0.0.4
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
