# $NetBSD$

GITHUB_PROJECT=	mock
GITHUB_TAG=	v1.4.4
DISTNAME=	v1.4.4
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=golang/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/golang/mock/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/mock-1.4.4
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
