# $NetBSD$

GITHUB_PROJECT=	speed
GITHUB_TAG=	v3.0.1
DISTNAME=	v3.0.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=performancecopilot/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/performancecopilot/speed/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/speed-3.0.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
