# $NetBSD$

DISTNAME=	gerrychain-0.2.12
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	https://files.pythonhosted.org/packages/79/76/0ad276d1eda834f6a9e42f62488cf394548b88a25f44a1b57b386acb6b86/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/79/76/0ad276d1eda834f6a9e42f62488cf394548b88a25f44a1b57b386acb6b86/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
