# $NetBSD$

DISTNAME=	gerrychain-0.2.12
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/79/76/0ad276d1eda834f6a9e42f62488cf394548b88a25f44a1b57b386acb6b86/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/79/76/0ad276d1eda834f6a9e42f62488cf394548b88a25f44a1b57b386acb6b86/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
