# $NetBSD$

DISTNAME=	go-context-20190109
GITHUB_PROJECT=	context
GITHUB_TAG=	c447772
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/context/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/context-c447772a6520c1a3ae6294a7df725ee08230f14e
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
