package:
  name: exceltogdx-dev
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch_python: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - appdirs
    - pandas
    - numpy
    - pytest
    - docopt
    - gdxpds
    - openpyxl
    - xlrd

test:
  imports:
    - exceltogdx

about:
  home: https://github.com/diw-berlin/exceltogdx
  license: MIT License
  summary: 'By providing a configuration table, this tool is able to read sets and parameter from an excel file and generate a gdx file as input for GAMS models'
license_family: MIT
