# $NetBSD$

DISTNAME=	pytket-0.5.6-cp38-cp38-manylinux2014_x86_64
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/99/9e/bba38b25ef30034c73985c10f78cbc6456e2ceb1ca0afc9cd8c13af039bf/
EXTRACT_SUFX=	.whl

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/99/9e/bba38b25ef30034c73985c10f78cbc6456e2ceb1ca0afc9cd8c13af039bf/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
