# $NetBSD$

DISTNAME=	loky-2.8.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ac/02/815e43e69592a8a0eabc3d3d99f3e83eb6e401bc248046767f33417d9f08/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ac/02/815e43e69592a8a0eabc3d3d99f3e83eb6e401bc248046767f33417d9f08/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
