# $NetBSD$

DISTNAME=	arabic-text-quote-0.0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/2c/d6/3eb27fb46176689793bf6719a6efc4e09870ae98858df2bd9ed66859cbbe/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/abdullh-alidrous/arabic-text-quotation
COMMENT=	A package to discover texts extracted from Arabic books
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
