# $NetBSD$

DISTNAME=	goreferrer-20181106
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	goreferrer
GITHUB_TAG=	ec9c9a553398739f0dcf817e0ad5e01c4e7dcd08
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=Shopify/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/goreferrer/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/goreferrer-ec9c9a553398739f0dcf817e0ad5e01c4e7dcd08
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
