# $NetBSD$

DISTNAME=	e6tensors_full-1.0.0
PKGNAME=	${DISTNAME:S/_full//}
CATEGORIES=	category
MASTER_SITES=	https://e6tensors.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://e6tensors.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/e6tensors_full

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
