# $NetBSD$

DISTNAME=	lrslib-071a
CATEGORIES=	math
MASTER_SITES=	http://cgm.cs.mcgill.ca/~avis/C/lrslib/archive/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://cgm.cs.mcgill.ca/~avis/C/lrs.html
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_TOOLS+=	gmake
MAKE_FILE=	makefile

.include "../../devel/gmp/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
