# $NetBSD$

DISTNAME=	msedge-selenium-tools-3.141.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/63/a1/c3ddd9b9ee7be2e7bf6cd49238244618f00d72c65f9d35d70f26c362926a/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/microsoft/edge-selenium-tools
COMMENT=	An updated EdgeDriver implementation for Selenium 3 with newly-added support for Microsoft Edge (Chromium)
LICENSE=	apache-2.0

DEPENDS+=	# TODO: selenium==3.141>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
