# $NetBSD$

DISTNAME=	rtp-1.6.2
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	rtp
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=pion/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/pion/rtp/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/pion/rtp

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
