# $NetBSD$

GITHUB_PROJECT=	ukui-system-monitor
DISTNAME=	ukui-system-monitor_1.0.4.orig
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
GITHUB_RELEASE=	v1.0.4

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/ukui-system-monitor/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ukui-system-monitor
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
