# $NetBSD$

DISTNAME=	qiskit-0.20.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/1f/60/542761fb70fa8039a546512b870c99e467df2151ab42b5327ef7b26d2f0f/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Qiskit/qiskit
COMMENT=	Software for developing quantum computing programs
LICENSE=	apache-2.0

DEPENDS+=	# TODO: qiskit-terra==0.15.2>=0
DEPENDS+=	# TODO: qiskit-aer==0.6.1>=0
DEPENDS+=	# TODO: qiskit-ibmq-provider==0.8.0>=0
DEPENDS+=	# TODO: qiskit-ignis==0.4.0>=0
DEPENDS+=	# TODO: qiskit-aqua==0.7.5>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
