# $NetBSD$

DISTNAME=	gods-20201118
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	gods
GITHUB_TAG=	79df803e554cab06f835fb729064282b2fd4cc99
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=emirpasic/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/emirpasic/gods/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=	github.com/google/${GITHUB_PROJECT}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
