# $NetBSD$

DISTNAME=	mysam-tagmanager-0.3.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/81/27/7b9b868335c9c90042a46640e325488a7e2a2719e5ae1d857a6afeca08a0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://pypi.python.com/projects/mysam-tagmanager/
COMMENT=	Mysam: Arabic tags manager
LICENSE=	gnu-gpl-v1 OR gnu-gpl-v2 OR gnu-gpl-v3

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
