# $NetBSD$

DISTNAME=	T3PS-1.0
CATEGORIES=	category
MASTER_SITES=	https://t3ps.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://t3ps.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
