# $NetBSD$

DISTNAME=	cogent3-2020.12.21a0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/d8/a3/0d29b5d46bf1b9f74546c21c7957162e3b69955bdf11085520bf8183fad3/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/d8/a3/0d29b5d46bf1b9f74546c21c7957162e3b69955bdf11085520bf8183fad3/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
