# $NetBSD$

DISTNAME=	cogent3-2020.12.21a0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	biology python
MASTER_SITES=	${MASTER_SITE_PYPI:=c/cogent3/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/cogent3/cogent3
COMMENT=	TODO: Short description of the package
LICENSE=	2-clause-bsd


DEPENDS+=               ${PYPKGPREFIX}-boto3>=1.12.43:../../net/py-boto3
DEPENDS+=               ${PYPKGPREFIX}-boto3>=1.12.43:../../net/py-boto3
DEPENDS+=               ${PYPKGPREFIX}-boto3>=1.12.43:../../net/py-boto3
DEPENDS+=               ${PYPKGPREFIX}-boto3>=1.12.43:../../net/py-boto3

 .include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
