# $NetBSD$

DISTNAME=	gopencils-20161103
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	gopencils
GITHUB_TAG=	22e283ad76118c1e1f3812b4a3553809cd434e6a
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/gopencils/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)


.include "../../mk/bsd.pkg.mk"
