# $NetBSD$

GITHUB_PROJECT=	machineid
GITHUB_TAG=	v1.0.1
DISTNAME=	v1.0.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=denisbrodbeck/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/denisbrodbeck/machineid/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

WRKSRC=		${WRKDIR}/machineid-1.0.1

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
