# $NetBSD$

GITHUB_PROJECT=	go-elasticsearch
GITHUB_TAG=	v7.10.0
DISTNAME=	v7.10.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=elastic/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/elastic/go-elasticsearch/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-elasticsearch-7.10.0
USE_LANGUAGES=	# none
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
