# $NetBSD$

DISTNAME=	go-dh-make-golang-0.4.0
GITHUB_PROJECT=	dh-make-golang
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=Debian/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Debian/dh-make-golang/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/dh-make-golang-0.4.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
