# $NetBSD$

DISTNAME=	docker_ssh-0.0.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/95/51/e8648fc0c11dbaff6558d71fa2e4966a43b3e9749c44e152d4be339f17e1/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/andreycizov/python-docker_ssh
COMMENT=	Python docker SSH tunnel
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
