# $NetBSD$

DISTNAME=	pytket-qiskit-0.4.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/5d/19/84ee6294fd65e972279479b655b58d39c9478f490f67d8bfbcc33200b498/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/CQCL/pytket
COMMENT=	Extension for pytket, providing translation to and from the Qiskit framework
#LICENSE=	CQC Non-Commercial Use Software Licence # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: pytket~=0.5>=0
DEPENDS+=	# TODO: qiskit==0.19>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
