# $NetBSD$

DISTNAME=	reactive-platform-0.3.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/32/7f/8d253e6c6810826f30b5b22d0e16d79e683170e37bd8ba99eadd7bb5f68a/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/32/7f/8d253e6c6810826f30b5b22d0e16d79e683170e37bd8ba99eadd7bb5f68a/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
