# $NetBSD$

DISTNAME=	pytest-docker-0.7.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/d6/2b/318d447ffa67c34005ec7120de29b2b13c42146a6b22c27b9b8a433379eb/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/d6/2b/318d447ffa67c34005ec7120de29b2b13c42146a6b22c27b9b8a433379eb/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

BUILD_DEPENDS+=	py-wheel>=0.32:../../devel/py-wheel
BUILD_DEPENDS+=	# TODO: pytest-runner>=5.0,<6.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
