# $NetBSD$

DISTNAME=	Arpeggio-1.10.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:tl}
CATEGORIES=	devel python
MASTER_SITES=	https://files.pythonhosted.org/packages/bb/39/7eb97aadd4901f9985158a63f907e818ad47627d28e8f9f6fcff9f6bbecf/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/textX/Arpeggio
COMMENT=	Packrat parser interpreter
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
