# $NetBSD$

GITHUB_PROJECT=	traefik
DISTNAME=	traefik-v2.3.1.src
PKGNAME=	${DISTNAME:S,-v,-,}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=traefik/}
GITHUB_RELEASE=	v2.3.1

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/traefik/traefik/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

WRKSRC=		${WRKDIR}

USE_LANGUAGES=	# none

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
