# $NetBSD$

DISTNAME=	scorep-3.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/69/81/3103a2354e56c7a9a0fc9803c8c2d1fc5ec578c609a73cda17d88f9e64fc/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/69/81/3103a2354e56c7a9a0fc9803c8c2d1fc5ec578c609a73cda17d88f9e64fc/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
