# $NetBSD$

DISTNAME=	guietta-0.6.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/06/4e/a724d09a723a7e3251e7e1c044f570c92cd3b665d06741b8528b4984f580/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/alfiopuglisi/guietta
COMMENT=	Simple GUI for Python
LICENSE=	mit

DEPENDS+=	# TODO: PySide2>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
