# $NetBSD$

DISTNAME=	guietta-0.6.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	x11 python
MASTER_SITES=	${MASTER_SITE_PYPI:=g/guietta/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/alfiopuglisi/guietta
COMMENT=	Simple GUI for Python
LICENSE=	mit

DEPENDS+=	# TODO: PySide2>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
