# $NetBSD$

GITHUB_PROJECT=	kregexpeditor
GITHUB_TAG=	v3.3.2
DISTNAME=	v3.3.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=KDE/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/KDE/kregexpeditor/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/kregexpeditor-3.3.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
