# $NetBSD$

GITHUB_PROJECT=	rpcx
GITHUB_TAG=	v5.7.8
DISTNAME=	v5.7.8
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=smallnest/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/smallnest/rpcx/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/rpcx-5.7.8
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
