# $NetBSD$

DISTNAME=	pyfvm-0.3.2
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	https://files.pythonhosted.org/packages/79/50/a4622fa9ce90a6b86dd1a21574ce27503d15f2269f13d03555737a178345/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/nschloe/pyfvm
COMMENT=	Finite volume discretizations for Python
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
