# $NetBSD$

DISTNAME=	pyfvm-0.3.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/79/50/a4622fa9ce90a6b86dd1a21574ce27503d15f2269f13d03555737a178345/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/79/50/a4622fa9ce90a6b86dd1a21574ce27503d15f2269f13d03555737a178345/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
