# $NetBSD$

DISTNAME=	periph-20210101
GITHUB_PROJECT=	periph
GITHUB_TAG=	688e66ebfa5a498d3cf9b55f2233db0edd90754d
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=google/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/google/periph/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/periph-688e66ebfa5a498d3cf9b55f2233db0edd90754d
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
