# $NetBSD$

DISTNAME=	elf-dissector-master
CATEGORIES=	category
MASTER_SITES=	https://invent.kde.org/sdk/elf-dissector/-/archive/master/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://kde.org/applications/en/elf-dissector
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
