# $NetBSD$

DISTNAME=	libform-4.2.1	
GITHUB_PROJECT=	form
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=vermaseren/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/vermaseren/form/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/form-4.2.1
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
