# $NetBSD$

GITHUB_TAG=	v${PKGVERSION_NOREV}
DISTNAME=	go-errwrap-1.0.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=hashicorp/}
GITHUB_PROJECT=	errwrap

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/hashicorp/errwrap/
COMMENT=	TODO: Short description of the package
LICENSE=	mpl-2.0

GO_SRCPATH=	github.com/hashicorp/errwrap/
GO_DIST_BASE=	errwrap-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
