# $NetBSD$

DISTNAME=	figure-20200609
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	go-figure
GITHUB_TAG=	c4b36f9
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/common-nighthawk/go-figure/
COMMENT=	Prints ASCII art from text
LICENSE=	mit

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}*
GO_SRCPATH=	github.com/common-nighthawk/go-figure

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
