# $NetBSD$

DISTNAME=	go-pongo2-0.0.1
GITHUB_PROJECT=	pongo2
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=iris-contrib/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/iris-contrib/pongo2/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/pongo2-0.0.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
