# $NetBSD$

GITHUB_PROJECT=	pongo2
GITHUB_TAG=	v4.0.0
DISTNAME=	v4.0.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=flosch/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/flosch/pongo2/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/pongo2-4.0.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
