# $NetBSD$

GITHUB_PROJECT=	ukui-sidebar
DISTNAME=	ukui-sidebar_1.1.2.orig
PKGNAME=	ukui-sidebar-1.1.2
CATEGORIES=	wm
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
GITHUB_RELEASE=	v1.1.2

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/ukui/ukui-sidebar/
COMMENT=	TODO: Short description of the package
LICENSE=	gnu-gpl-v3

WRKSRC=		${WRKDIR}/ukui-sidebar

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
