# $NetBSD$

DISTNAME=	clazy-master
CATEGORIES=	category
MASTER_SITES=	https://invent.kde.org/sdk/clazy/-/archive/master/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	kamelderouiche@yahoo.comive/master/
HOMEPAGE=	https://invent.kde.org/sdk/clazy/-/arch
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
