# $NetBSD$

DISTNAME=	go-gotk3-0.5.2
GITHUB_PROJECT=	gotk3
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gotk3/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gotk3/gotk3/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gotk3-0.5.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
