# $NetBSD$

DISTNAME=	geomstats-2.2.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/98/97/11cb16d2ac4449db3ac353c5544b1bdb0838fc16fd4cc4b180c42e891955/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/98/97/11cb16d2ac4449db3ac353c5544b1bdb0838fc16fd4cc4b180c42e891955/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
