# $NetBSD$

DISTNAME=	go-errorx-1.0.3
GITHUB_PROJECT=	errorx
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=joomcode/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/joomcode/errorx/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/errorx-1.0.3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
