# $NetBSD$

DISTNAME=	go-errorx-1.0.3
GITHUB_PROJECT=	errorx
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=joomcode/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/joomcode/errorx/
COMMENT=	TODO: Short description of the package
LICENSE=	mit


.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
