# $NetBSD$

DISTNAME=	smplayer-themes-18.6.0
CATEGORIES=	category
MASTER_SITES=	https://netix.dl.sourceforge.net/project/smplayer/SMPlayer-themes/18.6.0/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://netix.dl.sourceforge.net/project/smplayer/SMPlayer-themes/18.6.0/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
