# $NetBSD$

DISTNAME=	go-wav-1.0.0
GITHUB_PROJECT=	wav
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-audio/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go-audio/wav/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/wav-1.0.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
