# $NetBSD$

DISTNAME=	flask_simplelogin-0.0.7
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/23/fb/732df9ec0725c35d7759d797428c768992ad8ba7c906595d02330b42735c/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/cuducos/flask_simplelogin/
COMMENT=	Flask Simple Login - Login Extension for Flask
LICENSE=	mit

DEPENDS+=	# TODO: Flask>=0.12
DEPENDS+=	py-click>=0:../../devel/py-click
DEPENDS+=	# TODO: flask_wtf>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
