# $NetBSD$

DISTNAME=	go-hex-20190517
GITHUB_PROJECT=	hex
GITHUB_TAG=	c6586a6
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/hex/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/hex-c6586a6fe0b7c95eef767657ab1031cbcfc7af66
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
