# $NetBSD$

DISTNAME=	opencv-contrib-python-4.5.1.48
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/42/02/7b2fb0b81266aa3243dd8f392d48db1a206cc9a1856a14228e75c515616e/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/42/02/7b2fb0b81266aa3243dd8f392d48db1a206cc9a1856a14228e75c515616e/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
