# $NetBSD$

GITHUB_PROJECT=	websocket
GITHUB_TAG=	v1.4.2
DISTNAME=	v1.4.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gorilla/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gorilla/websocket/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/websocket-1.4.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
