# $NetBSD$

DISTNAME=	mauikit-v1.1.1
PKGNAME=	${DISTNAME:S,-v,-,}
CATEGORIES=	category
MASTER_SITES=	https://invent.kde.org/maui/mauikit/-/archive/v1.1.1/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://invent.kde.org/maui/mauikit/-/archive/v1.1.1/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
