# $NetBSD$

DISTNAME=	crossbar-20.8.1
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=d/crossbar/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://crossbar.io/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
