# $NetBSD$

DISTNAME=	lanq-0.6.3
CATEGORIES=	category
MASTER_SITES=	https://svwh.dl.sourceforge.net/project/lanq/LanQ/0.6.3/
EXTRACT_SUFX=	.jar

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://svwh.dl.sourceforge.net/project/lanq/LanQ/0.6.3/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
