# $NetBSD$

GITHUB_PROJECT=	reactive-pg-client
GITHUB_TAG=	0.11.4
DISTNAME=	0.11.4
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=vietj/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/vietj/reactive-pg-client/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/reactive-pg-client-0.11.4
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
