# $NetBSD$

DISTNAME=	timemory-3.2.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ef/fd/61a179c2fcfa4019d2b7caf4093864a2795cc1d6b6fed9e7768affb04de0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ef/fd/61a179c2fcfa4019d2b7caf4093864a2795cc1d6b6fed9e7768affb04de0/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
