# $NetBSD$

DISTNAME=	timemory-3.2.0
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=t/timemory/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/ef/fd/61a179c2fcfa4019d2b7caf4093864a2795cc1d6b6fed9e7768affb04de0/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

PYTHON_VERSIONS_INCOMPATIBLE+=	36

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
