# $NetBSD$

GITHUB_PROJECT=	libinput-touch-translator
DISTNAME=	libinput-touch-translator_1.0.0.orig
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
GITHUB_RELEASE=	v1.0.0

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/libinput-touch-translator/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/libinput-touch-translator
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
