# $NetBSD$

DISTNAME=	go-snappy-0.0.2
GITHUB_PROJECT=	snappy
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=golang/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/golang/snappy/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/smallnest/rpcx

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
