# $NetBSD$

DISTNAME=	imtoolkit-0.8-py3-none-any
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/99/92/82203c0d53e43ba90cbe310e96b9eb878f67fb6d510414d841c4c03f4888/
EXTRACT_SUFX=	.whl

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/99/92/82203c0d53e43ba90cbe310e96b9eb878f67fb6d510414d841c4c03f4888/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
