# $NetBSD$

DISTNAME=	cashocs-1.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://files.pythonhosted.org/packages/de/a3/426e89b193cebe513ebf9efde63f56a9590ab391779a898a2f4d3ef9b452/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/sblauth/cashocs
COMMENT=	Adjoint-Based Shape Optimization and Optimal Control Software
#LICENSE=	# TODO: (see mk/license.mk)

DEPENDS+=	# TODO: pytest>=6.0.0
DEPENDS+=	# TODO: meshio>=4.1.0
#DEPENDS+=	${PYPKGPREFIX}-matplotlib>=0:../../graphics/py-matplotlib

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
