# $NetBSD$

DISTNAME=	libpysal-4.4.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_PYPI:=l/libpysal/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://pysal.org/libpysal
COMMENT=	Core components of PySAL A library of spatial analysis functions
LICENSE=	modified-bsd

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
