# $NetBSD$

DISTNAME=	julia-1.0.4
PKGNAME=	julia-1.0.410
DISTVERSIONSUFFIX=	-full
PORTREVISION=	5
CATEGORIES=	lang math
MASTER_SITES=	https://github.com/JuliaLang/julia/releases/download/v${PORTVERSION}/

MAINTAINER=	kamelderouiche@yahoo.com
