# $NetBSD$

DISTNAME=	PharoLauncher-linux-2.2-x64
PKGNAME=	pharo-2.2
CATEGORIES=	lang
MASTER_SITES=	https://files.pharo.org/pharo-launcher/2.2/
EXTRACT_SUFX=	.zip

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pharo.org/pharo-launcher/2.2/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/pharolauncher

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
