# $NetBSD$

DISTNAME=	dask-2020.12.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=d/dask/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/d5/06/9024cb52239b2d0294e5683d3a0847fdb8a05b5e1e43a182a075a461df70/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
