# $NetBSD$

DISTNAME=	dask-2020.12.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/d5/06/9024cb52239b2d0294e5683d3a0847fdb8a05b5e1e43a182a075a461df70/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/d5/06/9024cb52239b2d0294e5683d3a0847fdb8a05b5e1e43a182a075a461df70/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
