# $NetBSD$

DISTNAME=	tupu-0.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://files.pythonhosted.org/packages/76/f8/36c0cc7994f93a75c53ada950176b69563049eb46225db88cc5a0552048f/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/sergiocorreia/tupu
COMMENT=	Fast geodesic distances between sets
LICENSE=	mit

PYTHON_VERSIONS_INCOMPATIBLE= 27

DEPENDS+=	# TODO: pyproj>=0
DEPENDS+=	# TODO: rtree>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
