# $NetBSD$

GITHUB_PROJECT=	goquery
GITHUB_TAG=	v1.5.1
DISTNAME=	v1.5.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=PuerkitoBio/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/PuerkitoBio/goquery/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/goquery-1.5.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
