# $NetBSD$

DISTNAME=	circleci-1.2.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/37/03/1b061fa1d05f19ba696153f004b1662ff1a0bdefbd3f8e08e14bf21c4849/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/37/03/1b061fa1d05f19ba696153f004b1662ff1a0bdefbd3f8e08e14bf21c4849/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
