# $NetBSD$

DISTNAME=	sleepy-20170915
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	sleepy
GITHUB_TAG=	eb7a30b
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/sleepy/
COMMENT=	Rest for go 
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/sleepy-eb7a30b37c5bb7b35d8158979524cdcda56b457e
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
