# $NetBSD$

GITHUB_PROJECT=	selenoid
GITHUB_TAG=	1.10.0
DISTNAME=	1.10.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=aerokube/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/aerokube/selenoid/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/selenoid-1.10.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
