# $NetBSD$

DISTNAME=	FormFlavor-1.1.0
CATEGORIES=	category
MASTER_SITES=	https://formflavor.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://formflavor.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
