# $NetBSD$

DISTNAME=	autoflake-1.4
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/11/2e/0a7618eb5e69483d62b0f86c8d1eb7fdca2c2781f6f0cd5f3a3286398475/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/myint/autoflake
COMMENT=	Removes unused imports and unused variables
#LICENSE=	Expat License # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: pyflakes>=1.1.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
