# $NetBSD$

DISTNAME=	orthopy-0.8.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://files.pythonhosted.org/packages/79/d6/3197aa1e689fe22dd8b1d43d628d5ad9cf841ac656646cda597b0396ba95/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/79/d6/3197aa1e689fe22dd8b1d43d628d5ad9cf841ac656646cda597b0396ba95/
COMMENT=	Tools for orthogonal polynomials
LICENSE=	gnu-gpl-v3

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
