# $NetBSD$

DISTNAME=	orthopy-0.8.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/75/0e/76e7283932a9194abd3476749752a9c1f8495ee008ef0f27348b3c804a11/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/75/0e/76e7283932a9194abd3476749752a9c1f8495ee008ef0f27348b3c804a11/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
