# $NetBSD$

DISTNAME=	go-graphql-graph-gohpers-20201113
GITHUB_PROJECT=	graphql-go
GITHUB_TAG=	beb923fada293249384c7a9fa0c5078ea92466f3
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=graph-gophers/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/graph-gophers/graphql-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/graphql-go-beb923fada293249384c7a9fa0c5078ea92466f3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
