# $NetBSD$

DISTNAME=	go-graphql-graph-gohpers-20201113
GITHUB_PROJECT=	graphql-go
GITHUB_TAG=	beb923fada293249384c7a9fa0c5078ea92466f3
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=graph-gophers/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/graph-gophers/graphql-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=	github.com/https://github.com/graph-gophers/graphql-go

.include "../../wip/go-opentracing/buildlink3.mk"
.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
