# $NetBSD$

DISTNAME=	go-neffos-0.0.18
GITHUB_PROJECT=	neffos
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=kataras/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/kataras/neffos/
COMMENT=	Lightweight real-time framework based on WebSockets for Go
LICENSE=	mit

GO_SRCPATH=	github.com/kataras/neffos
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
