# $NetBSD$

GITHUB_PROJECT=	realize
GITHUB_TAG=	v2.0.2
DISTNAME=	v2.0.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=oxequa/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/oxequa/realize/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/realize-2.0.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
