# $NetBSD$

DISTNAME=	libqutrub-1.2.4.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/b3/09/3291c40b40862c1031c310f8ac9afcfdcefdaf46b7a8dae9f6c6fdbfb76c/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/b3/09/3291c40b40862c1031c310f8ac9afcfdcefdaf46b7a8dae9f6c6fdbfb76c/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
