# $NetBSD$

DISTNAME=	go-multierr-1.6.0
GITHUB_PROJECT=	multierr
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=uber-go/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://go.uber.org/multierr
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/multierr-1.6.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
