# $NetBSD$

DISTNAME=	LQ_NLO-0.0.1
CATEGORIES=	category
MASTER_SITES=	https://lqnlo.hepforge.org/downloads/
EXTRACT_SUFX=	.zip

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://lqnlo.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR} # TODO: one of Leptokvark LQ_R2 __MACOSX LQ_R2~ LQ_S1 LQ_S1~ LQ_S3 Vector_LQ, or leave it as-is
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
