# $NetBSD$

DISTNAME=	LQ_NLO-0.0.1
PKGNAME=	lqnlo-0.0.1
CATEGORIES=	math
MASTER_SITES=	https://lqnlo.hepforge.org/downloads/
EXTRACT_SUFX=	.zip

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://lqnlo.hepforge.org/
COMMENT=	LQ_NLO is a leptoquark toolbox for precision collider studies
LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
