# $NetBSD$

GITHUB_PROJECT=	ksuid
GITHUB_TAG=	v1.0.3
DISTNAME=	v1.0.3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=segmentio/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/segmentio/ksuid/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ksuid-1.0.3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
