# $NetBSD$

GITHUB_PROJECT=	IAMR
GITHUB_TAG=	20.10
DISTNAME=	20.10
PKGNAME=	${GITHUB_PROJECT:tl}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=AMReX-Codes/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/AMReX-Codes/IAMR/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/IAMR-20.10

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
