# $NetBSD$

DISTNAME=	sospin-1.0.0
CATEGORIES=	math
MASTER_SITES=	https://sospin.hepforge.org/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://sospin.hepforge.org/
COMMENT=	C++ library for Yukawa decomposition in SO(2N) models
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_TOOLS+=	perl
USE_LANGUAGES=	c c++

#https://sospin.hepforge.org/readme.html

.include "../../mk/bsd.pkg.mk"
