# $NetBSD$

GITHUB_PROJECT=	FHDeX
GITHUB_TAG=	pre-GPU
DISTNAME=	pre-GPU
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=AMReX-FHD/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/AMReX-FHD/FHDeX/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/FHDeX-pre-GPU
USE_LANGUAGES=	c++ fortran

.include "../../mk/bsd.pkg.mk"
