# $NetBSD$

DISTNAME=	geometry-utils-0.1.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	https://files.pythonhosted.org/packages/05/f4/0ca9d716fd937996a61377c9094b390601355cc56a781c70dcac3e3f30db/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/ihavenonickname/geometry-utils
COMMENT=	TODO: Short description of the package
LICENSE=	mit

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
