# $NetBSD$

DISTNAME=	geometry-utils-0.1.3
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/05/f4/0ca9d716fd937996a61377c9094b390601355cc56a781c70dcac3e3f30db/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/05/f4/0ca9d716fd937996a61377c9094b390601355cc56a781c70dcac3e3f30db/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
