# $NetBSD$

DISTNAME=	go-gotest-tools-3.0.3
GITHUB_PROJECT=	gotest.tools
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=gotestyourself/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/gotestyourself/gotest.tools/
COMMENT=	TODO: Short description of the package
LICENSE=	apache-2.0

GO_SRCPATH=	github.com/gotestyourself/gotest.tools
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
