# $NetBSD$

DISTNAME=	go-gotest-tools-3.0.3
GITHUB_PROJECT=	gotest.tools
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gotestyourself/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gotestyourself/gotest.tools/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gotest.tools-3.0.3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
