# $NetBSD$

DISTNAME=	json-iterator-20200608
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	go
GITHUB_TAG=	a1ca0830781e007c66b225121d2cdb3a649421f6
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=json-iterator/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/json-iterator/go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-a1ca0830781e007c66b225121d2cdb3a649421f6
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
