# $NetBSD$

DISTNAME=	quipper-0.9.0.0
CATEGORIES=	lang
MASTER_SITES=	https://www.mathstat.dal.ca/~selinger/quipper/downloads/
EXTRACT_SUFX=	.tgz

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://www.mathstat.dal.ca/~selinger/quipper/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
