# $NetBSD$

DISTNAME=	go-ffmpeg-0.5.0
GITHUB_PROJECT=	goffmpeg
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=xfrr/}
GITHUB_TAG=	${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/xfrr/goffmpeg/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/goffmpeg-0.5.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
