# $NetBSD$

DISTNAME=	Cbc-2.10.5
CATEGORIES=	category
MASTER_SITES=	https://www.coin-or.org/download/source/Cbc/
EXTRACT_SUFX=	.tgz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.coin-or.org/download/source/Cbc/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
