# $NetBSD$

DISTNAME=	qsymm-1.2.7
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	https://files.pythonhosted.org/packages/ec/a1/e8f8cfdf69b64fefb509258fba4ccac59a9e16bba5e7d838db0ef57ff327/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://gitlab.kwant-project.org/qt/qsymm
COMMENT=	Symmetry finder and symmetric Hamiltonian generator
LICENSE=	2-claused-bsd

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
