# $NetBSD$

DISTNAME=	qsymm-1.2.7
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ec/a1/e8f8cfdf69b64fefb509258fba4ccac59a9e16bba5e7d838db0ef57ff327/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ec/a1/e8f8cfdf69b64fefb509258fba4ccac59a9e16bba5e7d838db0ef57ff327/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
