# $NetBSD$

DISTNAME=	httpunix-20191212
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	httpunix
GITHUB_TAG=	2ba4b9c3382c77e7b9ea89d00746e6111d142a22
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/httpunix/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/httpunix-2ba4b9c3382c77e7b9ea89d00746e6111d142a22
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
