jobs:
 - reduce_sectors:
    reduce:
     - { r: 7, s: 2 } # simple example
    select_integrals:
      select_mandatory_recursively:
       - { r: 7, s: 2, d: 0}
    run_initiate: true
    run_triangular: true
    run_back_substitution: true
 - kira2math:
    target:
     - {sectors: [191, 247, 253, 431], r: 7, s: 2, d: 0}
