# $NetBSD$

DISTNAME=	pybuilder-0.12.10
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ce/39/25bdab736be24981fd8f7a234d9376740dcb324692d969b0659ce3343488/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ce/39/25bdab736be24981fd8f7a234d9376740dcb324692d969b0659ce3343488/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
