# $NetBSD$

DISTNAME=	kexi-3.2.0
CATEGORIES=	databases
MASTER_SITES=	http://ftp.is.co.za/mirror/ftp.kde.org/stable/kexi/src/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=     kamelderouiche@yahoo.com
HOMEPAGE=       http://kexi-project.org/
COMMENT=        Visual database applications creator, a long-awaited competitor
LICENSE=        gnu-gpl-v2

USE_CMAKE=		yes
USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		c c++

.include "../../mk/bsd.pkg.mk"
