# $NetBSD$

DISTNAME=	scitrack-2020.6.5
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=c//}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/72/33/ad9c5271d769215acbc39fbf17e60352415eca9f40c72ce0256633010543/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
