# $NetBSD$

DISTNAME=	scitrack-2020.6.5
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=s/scitrack/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/72/33/ad9c5271d769215acbc39fbf17e60352415eca9f40c72ce0256633010543/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)


.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
