# $NetBSD$

DISTNAME=	junit-xml-2-1.9
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=j/junit-xml/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/returntocorp/python-junit-xml
COMMENT=	Fork of https://github.com/kyrus/python-junit-xml that has tarball published to pypi
LICENSE=	mit

DEPENDS+=	py-six>=0:../../lang/py-six

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
