# $NetBSD$

DISTNAME=	go-pongo2-0.0.1
GITHUB_PROJECT=	pongo2
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=iris-contrib/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/iris-contrib/pongo2/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=	github.com/iris-contrib/pongo2
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
