# $NetBSD$

DISTNAME=	scorep-6.0
CATEGORIES=	category
MASTER_SITES=	https://www.vi-hps.org/cms/upload/packages/scorep/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.vi-hps.org/cms/upload/packages/scorep/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++ fortran

.include "../../mk/bsd.pkg.mk"
