# $NetBSD$

DISTNAME=	scorep-6.0
CATEGORIES=	math
MASTER_SITES=	https://www.vi-hps.org/cms/upload/packages/scorep/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://www.vi-hps.org/cms/upload/packages/scorep/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++ fortran

.include "../../mk/bsd.pkg.mk"
