# $NetBSD$

DISTNAME=	alterbbn_v2.2
CATEGORIES=	category
MASTER_SITES=	https://alterbbn.hepforge.org/downloads/
EXTRACT_SUFX=	.tgz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://alterbbn.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../mk/bsd.pkg.mk"
