# $NetBSD$

DISTNAME=	alterbbn_v2.2
PKGNAME=	alterbbn-2.2
CATEGORIES=	math
MASTER_SITES=	https://alterbbn.hepforge.org/downloads/
EXTRACT_SUFX=	.tgz

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://alterbbn.hepforge.org/
COMMENT=	Calculation of BBN abundances in alternative cosmologies
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../mk/bsd.pkg.mk"
