# $NetBSD$

DISTNAME=	qiskit-ignis-0.4.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/c0/69/27467e0cbed1de7509fca1d8bc1e4ef3eb8a3b6eb50fc51694c1559602a3/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/c0/69/27467e0cbed1de7509fca1d8bc1e4ef3eb8a3b6eb50fc51694c1559602a3/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
