# $NetBSD$

DISTNAME=	go-conntrack-20190716
GITHUB_PROJECT=	go-conntrack
GITHUB_TAG=	2f06839
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_GITHUB:=mwitkow/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/mwitkow/go-conntrack
COMMENT=	Go middleware for net.Conn tracking 
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-conntrack-2f068394615f73e460c2f3d2c158b0ad9321cadb
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
