# $NetBSD$

DISTNAME=	tsil-1.45
CATEGORIES=	category
MASTER_SITES=	http://www.niu.edu/spmartin/TSIL/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.niu.edu/spmartin/TSIL/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
