# $NetBSD$

DISTNAME=	tsil-1.45
CATEGORIES=	math
MASTER_SITES=	http://www.niu.edu/spmartin/TSIL/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://www.niu.edu/spmartin/TSIL/
COMMENT=	Two-loop Self-energy Integral Library
LICENSE=	gnu-gpl-v2

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
