# $NetBSD$

DISTNAME=	go-${GITHUB_PROJECT}-0.2.1
GITHUB_PROJECT=	klangsynthese
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_GITHUB:=200sc/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/200sc/klangsynthese/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/klangsynthese-0.2.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
