# $NetBSD$

DISTNAME=	vistir-0.5.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=b/bpytop/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/4f/82/aea5cb3f4153a66c24437290b06a0dd16acf56b49075f8381b136aba716b/
COMMENT=	Miscellaneous utilities for dealing with filesystems, paths, projects, subprocesses, and more.
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
