# $NetBSD$

DISTNAME=	selenium-base-1.49.23
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	www python
MASTER_SITES=	https://files.pythonhosted.org/packages/a7/86/6783ab822a18296a3baeaf186c6361c6d9e4f9b18bd2b57097a83ce3e2ac/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/seleniumbase/SeleniumBase
COMMENT=	Complete framework for Web-UI testing
LICENSE=	mit

DEPENDS+=       ${PYPKGPREFIX}-chardet>=3.0.4:../../converters/py-chardet
DEPENDS+=       ${PYPKGPREFIX}-packaging>=20.4:../../devel/py-packaging
DEPENDS+=       ${PYPKGPREFIX}-parso>=0.8.0:../../lang/py-parso
DEPENDS+=       ${PYPKGPREFIX}-six>=1.15.1:../../lang/py-six
DEPENDS+=	${PYPKGPREFIX}-cssselect>=1.1.0:../../textproc/py-cssselect
DEPENDS+=       ${PYPKGPREFIX}-wheel>=:../../devel/py-wheel
DEPENDS+=       ${PYPKGPREFIX}-test-html>=:../../wip/py-test-html
DEPENDS+=       ${PYPKGPREFIX}-soupsieve>=:../../www/py-soupsieve
DEPENDS+=       ${PYPKGPREFIX}-boto-[0-9]*:../../net/py-boto
DEPENDS+=       ${PYPKGPREFIX}-otp>=2.4.0:../../wip/py-otp
DEPENDS+=       ${PYPKGPREFIX}-otp>=2.4.0:../../wip/py-otp
DEPENDS+=       ${PYPKGPREFIX}-otp>=2.4.0:../../wip/py-otp
DEPENDS+=       ${PYPKGPREFIX}-otp>=2.4.0:../../wip/py-otp
DEPENDS+=       ${PYPKGPREFIX}-otp>=2.4.0:../../wip/py-otp
DEPENDS+=       ${PYPKGPREFIX}-otp>=2.4.0:../../wip/py-otp
DEPENDS+=       ${PYPKGPREFIX}-otp>=2.4.0:../../wip/py-otp
DEPENDS+=       ${PYPKGPREFIX}-otp>=2.4.0:../../wip/py-otp
DEPENDS+=       ${PYPKGPREFIX}-jedi>=0.17.2:../../editors/py-jedi
DEPENDS+=       ${PYPKGPREFIX}-pip>=2.4.0:../../devel/py-pip
DEPENDS+=       ${PYPKGPREFIX}-urllib3>=1.25.10:../../www/py-urllib3
DEPENDS+=       ${PYPKGPREFIX}-requests>=2.24.0:../../devel/py-requests
DEPENDS+=       ${PYPKGPREFIX}-more-itertools>=8.5.0:../../wip/py-more-itertools
DEPENDS+=       ${PYPKGPREFIX}-parameterized>=0.7.4:../../devel/py-parameterized
DEPENDS+=       ${PYPKGPREFIX}-selenium>=3.141.0:../../www/py-selenium



USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
