# $NetBSD$

DISTNAME=	selenium-base-1.49.23
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/a7/86/6783ab822a18296a3baeaf186c6361c6d9e4f9b18bd2b57097a83ce3e2ac/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/seleniumbase/SeleniumBase
COMMENT=	A complete framework for Web-UI testing | seleniumbase.io
LICENSE=	mit

DEPENDS+=	# TODO: seleniumbase>=1.49.23

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
