# $NetBSD$

DISTNAME=	spade-3.1.6
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/4f/3b/94e1239bbf40805c5d4640d1099ed05ccb8b2d499b59d93ab3c5498a07fd/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/javipalanca/spade
COMMENT=	Smart Python Agent Development Environment
LICENSE=	mit

BUILD_DEPENDS+=	# TODO: pytest-runner>=0
DEPENDS+=	# TODO: multidict==4.5.2>=0
DEPENDS+=	# TODO: pyasn1-modules==0.2.7>=0
DEPENDS+=	# TODO: pyasn1==0.4.7>=0
DEPENDS+=	py-aioxmpp>=0.10:../../wip/py-aioxmpp
DEPENDS+=	# TODO: aiohttp==3.5.4>=0
DEPENDS+=	# TODO: aiohttp_jinja2>=0.14.0
DEPENDS+=	py-jinja2>=2.9.6:../../textproc/py-jinja2
DEPENDS+=	# TODO: jinja2-time==0.2.0>=0
DEPENDS+=	# TODO: timeago==1.0.8>=0
DEPENDS+=	# TODO: singletonify==0.2.3>=0
TEST_DEPENDS+=	# TODO: pip==10.0.1>=0
TEST_DEPENDS+=	# TODO: bumpversion==0.5.3>=0
TEST_DEPENDS+=	# TODO: wheel==0.29.0>=0
TEST_DEPENDS+=	# TODO: watchdog==0.8.3>=0
TEST_DEPENDS+=	# TODO: flake8==2.6.0>=0
TEST_DEPENDS+=	# TODO: pyflakes==1.6.0>=0
TEST_DEPENDS+=	py-tox>2.3.1:../../devel/py-tox
TEST_DEPENDS+=	# TODO: coverage==4.0.3>=0
TEST_DEPENDS+=	# TODO: Sphinx==1.4.8>=0
TEST_DEPENDS+=	# TODO: pyyaml>=4.2b1
TEST_DEPENDS+=	# TODO: pytest==3.6.1>=0
TEST_DEPENDS+=	# TODO: pytest-runner==2.11.1>=0
TEST_DEPENDS+=	# TODO: asynctest==0.13.0>=0
TEST_DEPENDS+=	# TODO: pytest-asyncio==0.8.0>=0
TEST_DEPENDS+=	# TODO: pytest-cov==2.5.1>=0
TEST_DEPENDS+=	# TODO: pytest-mock==1.10.0>=0
TEST_DEPENDS+=	# TODO: pluggy<0.7,>=0.5
TEST_DEPENDS+=	# TODO: python-coveralls==2.9.1>=0
TEST_DEPENDS+=	py-requests>=2.20.0:../../devel/py-requests
TEST_DEPENDS+=	# TODO: parsel==1.4.0>=0
TEST_DEPENDS+=	# TODO: sphinx_rtd_theme==0.4.0>=0
TEST_DEPENDS+=	# TODO: testfixtures==6.3.0>=0
TEST_DEPENDS+=	# TODO: pytest-aiohttp==0.3.0>=0
TEST_DEPENDS+=	# TODO: docutils==0.12>=0
TEST_DEPENDS+=	# TODO: factory-boy==2.12.0>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
