# $NetBSD$

DISTNAME=	go-canvas-0.12.1
GITHUB_PROJECT=	canvas
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_GITHUB:=tfriedel6/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/tfriedel6/canvas/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=	github.com/tfriedel6/canvas/
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
