# $NetBSD$

GITHUB_PROJECT=	canvas
GITHUB_TAG=	v0.12.1
DISTNAME=	v0.12.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=tfriedel6/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/tfriedel6/canvas/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/canvas-0.12.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
