# $NetBSD$

DISTNAME=	go-hidden-20201230
GITHUB_PROJECT=	hidden
GITHUB_TAG=	e66e7f8
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/kiaderouiche/hidden/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/hidden-e66e7f8787308d0d5a87a2ebe170f19d43bece78
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
