kinematics:
  incoming_momenta: [q1, q2, q3]
  outgoing_momenta: [q4]
  momentum_conservation: [q4, q1+q2+q3]
  kinematic_invariants:
    - [s, 2]
    - [t, 2]
    - [u, 2]
    - [mt2, 2]
  scalarproduct_rules:
    - [[q1,q1], 0]
    - [[q2,q2], 0]
    - [[q3,q3], 0]
    - [[q1+q2, q1+q2], s]
    - [[q1+q3, q1+q3], t]
    - [[q2+q3, q2+q3], u]
  symbol_to_replace_by_one: mt2
