# $NetBSD$

DISTNAME=	go-genny-20200409
GITHUB_PROJECT=	genny
GITHUB_TAG=	3e22f1a
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=cheekybits/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/cheekybits/genny/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}*
GO_SRCPATH=	github.com/cheekybits/genny

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
