# $NetBSD$

DISTNAME=	gsettings-qt_0.1+17.10.20170824.orig
CATEGORIES=	category
MASTER_SITES=	http://deb.debian.org/debian/pool/main/g/gsettings-qt/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://deb.debian.org/debian/pool/main/g/gsettings-qt/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR} # TODO: one of GSettings src tests examples, or leave it as-is

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
