# $NetBSD$

DISTNAME=	recola2-collier-2.2.2
PKGNAME=	${DISTNAME:S/-collier//}
CATEGORIES=	math
MASTER_SITES=	https://recola.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://jean-nicolas_l.gitlab.io/recola2/
COMMENT=	Recursive Computation of 1-Loop Amplitudes
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c c++ fortran

.include "../../mk/bsd.pkg.mk"
