# $NetBSD$

DISTNAME=	imodeljs-20210204
GITHUB_PROJECT=	imodeljs
GITHUB_TAG=	a1a04545c91319b228da5b11361c1d7237ac7b5c
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=imodeljs/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/imodeljs/imodeljs/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/imodeljs-a1a04545c91319b228da5b11361c1d7237ac7b5c
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
