# $NetBSD$

DISTNAME=	sosed-2020
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
GITHUB_PROJECT=	sosed
GITHUB_TAG=	refs/tags/ase-2020
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=JetBrains-Research/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/JetBrains-Research/sosed/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/sosed-ase-2020
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
