# $NetBSD$

GITHUB_PROJECT=	goneovim
GITHUB_TAG=	v0.4.8
DISTNAME=	v0.4.8
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	editor
MASTER_SITES=	${MASTER_SITE_GITHUB:=akiyosi/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/akiyosi/goneovim/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/goneovim-0.4.8

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
