# $NetBSD$

GITHUB_PROJECT=	gi
GITHUB_TAG=	v1.0.11
DISTNAME=	v1.0.11
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=goki/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/goki/gi/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gi-1.0.11
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
