# $NetBSD$

DISTNAME=	vprof-0.38
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ee/3e/80bebf83110f1919a876efca66d0812fde9905e926c740bb75382f2ac626/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ee/3e/80bebf83110f1919a876efca66d0812fde9905e926c740bb75382f2ac626/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
