# $NetBSD$

DISTNAME=	caer-1.9.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ba/f9/2a759ab17ca2a27cb6e9dc6dd422239bfdba5c0c2ba85e8506ab272e7029/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ba/f9/2a759ab17ca2a27cb6e9dc6dd422239bfdba5c0c2ba85e8506ab272e7029/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
