# $NetBSD$

DISTNAME=	go-afs-1.6.0
GITHUB_PROJECT=	afs
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=viant/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/viant/afs/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/afs-1.6.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
