# $NetBSD$

GITHUB_PROJECT=	index-fm
GITHUB_TAG=	v1.1.1
DISTNAME=	v1.1.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=KDE/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/KDE/index-fm/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/index-fm-1.1.1
USE_CMAKE=	yes

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
