# $NetBSD$

DISTNAME=	Vevacious-1.2.03
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	math
MASTER_SITES=	https://vevacious.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://vevacious.hepforge.org/
COMMENT=	TODO: Short description of the package
LICENSE=	gnu-gpl-v3

WRKSRC=		${WRKDIR}/Vevacious

USE_TOOLS+=	gmake
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
