# $NetBSD$

DISTNAME=	Vevacious-1.2.03
CATEGORIES=	category
MASTER_SITES=	https://vevacious.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://vevacious.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/Vevacious
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
