# $NetBSD$

DISTNAME=	msgp-1.1.3
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	msgp
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_GITHUB:=tinylib/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/tinylib/msgp/
COMMENT=	Go code generator for MessagePack / msgpack.org
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
