# $NetBSD$

DISTNAME=	downloads?f=hoppet-1.2.0
CATEGORIES=	category
MASTER_SITES=	https://hoppet.hepforge.org/
EXTRACT_SUFX=	.tgz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://hoppet.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
