# $NetBSD$

DISTNAME=	tmdlib-2.2.0-beta02
CATEGORIES=	math
MASTER_SITES=	https://tmdlib.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://tmdlib.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++ fortran

.include "../../mk/bsd.pkg.mk"
