# $NetBSD$

DISTNAME=	tmdlib-2.0.2
CATEGORIES=	category
MASTER_SITES=	https://tmdlib.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://tmdlib.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c++ fortran

.include "../../mk/bsd.pkg.mk"
