# $NetBSD$

GITHUB_PROJECT=	PDF4Teachers
GITHUB_TAG=	1.2.0
DISTNAME=	1.2.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ClementGre/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ClementGre/PDF4Teachers/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/PDF4Teachers-1.2.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
