# $NetBSD$

DISTNAME=	go-fasttemplate-1.2.1
GITHUB_PROJECT=	fasttemplate
GITHUB_TAG=	v1.2.1
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=valyala/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/valyala/fasttemplate/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/fasttemplate-1.2.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
