# $NetBSD$

DISTNAME=	testfixtures-6.15.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=t/testfixtures/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/Simplistix/testfixtures
COMMENT=	Collection of helpers and mock objects for unit tests and doc tests
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
