# $NetBSD$

DISTNAME=	testfixtures-6.15.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/8b/ef/fd6d46300b573d8f73f9b68402735fcf204483a8522389a4100f45bb43b6/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Simplistix/testfixtures
COMMENT=	A collection of helpers and mock objects for unit tests and doc tests
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
