# $NetBSD$

DISTNAME=	FormulaLab-0.1.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/37/95/b301ad2d7659a2c8ac1fd3e652a8deda36b98a5d697bf31b774dd61b1cf5/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/37/95/b301ad2d7659a2c8ac1fd3e652a8deda36b98a5d697bf31b774dd61b1cf5/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
