# $NetBSD$

DISTNAME=	nats-20210107
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	nats.go
GITHUB_TAG=	a133396829fc0e6ed00400f486a50cb434c44939
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=nats-io/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/nats-io/nats.go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/nats.go-a133396829fc0e6ed00400f486a50cb434c44939
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
