# $NetBSD$

GITHUB_PROJECT=	go-flutter
GITHUB_TAG=	v0.41.2
DISTNAME=	v0.41.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-flutter-desktop/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go-flutter-desktop/go-flutter/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=	${WRKDIR}/go-flutter-0.41.2

.include "../../mk/bsd.pkg.mk"
