# $NetBSD$

DISTNAME=	QForestML-0.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/09/18/2a08db7dc1dcaf3f6af01f09882d71053bf040486bdeb9da580d648cf4e3/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/QForestCommunity/QForestML
COMMENT=	A wrapper for machine learning models in Qiskit
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
