# $NetBSD$

DISTNAME=	giddy-2.3.3
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/51/7e/e15ce66a3d4df269fef5551df44334a3e89c750e9947789665200c44a363/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/51/7e/e15ce66a3d4df269fef5551df44334a3e89c750e9947789665200c44a363/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
