# $NetBSD$

DISTNAME=	dexcd-1.0.1
CATEGORIES=	devel
MASTER_SITES=	https://www.swag.uwaterloo.ca/dexcd/downloads/1.0.1/
EXTRACT_SUFX=	.zip

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.swag.uwaterloo.ca/dexcd/
COMMENT=	Program tries to detect potential candidate clones
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/dexcd

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
