# $NetBSD$

DISTNAME=	dexcd-1.0.1
CATEGORIES=	category
MASTER_SITES=	https://www.swag.uwaterloo.ca/dexcd/downloads/1.0.1/
EXTRACT_SUFX=	.zip

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.swag.uwaterloo.ca/dexcd/index.html
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/dexcd

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
