# $NetBSD$

GITHUB_PROJECT=	go-metrics
GITHUB_TAG=	v0.3.4
DISTNAME=	v0.3.4
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=armon/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/armon/go-metrics/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-metrics-0.3.4
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
