# $NetBSD$

DISTNAME=	gi-1.1.0
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	gi
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=goki/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/goki/gi/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)


GO_DIST_BASE=   ${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=     github.com/goki/gi

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
