# $NetBSD$

DISTNAME=	qbh-3.01
PKGNAME=	qbh-hepforge-3.01
CATEGORIES=	category
MASTER_SITES=	https://qbh.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://qbh.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
