# $NetBSD$

DISTNAME=	qbh-3.01
CATEGORIES=	category
MASTER_SITES=	https://qbh.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://qbh.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
