# $NetBSD$

DISTNAME=	FeynWeb_php-0.1.0
CATEGORIES=	category
MASTER_SITES=	https://feynweb.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://feynweb.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/FeynWeb_0_1_0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
