# $NetBSD$

DISTNAME=	turn-20210118
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	turn
GITHUB_TAG=	9f91fa4f401a4f36e8d406eaa7fa4d3d3e94a7a5
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=pion/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/pion/turn/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/turn-9f91fa4f401a4f36e8d406eaa7fa4d3d3e94a7a5
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
