# $NetBSD$

GITHUB_PROJECT=	ukui-desktop-environment
GITHUB_TAG=	v1.2.1
DISTNAME=	v1.2.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/ukui-desktop-environment/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ukui-desktop-environment-1.2.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
