# $NetBSD$

GITHUB_PROJECT=	tracerr
GITHUB_TAG=	v0.3.0
DISTNAME=	v0.3.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ztrue/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ztrue/tracerr/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/tracerr-0.3.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
