# $NetBSD$

DISTNAME=	aiosasl-0.4.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/c4/5c/6522806fd01028c3b17e2309de6e4d2a989e0bde6f888a6ec70b9e1226b0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/horazont/aiosasl
COMMENT=	Pure-python, protocol agnostic SASL library for asyncio
LICENSE=	gnu-gpl-v1 OR gnu-gpl-v2 OR gnu-gpl-v3

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
