# $NetBSD$

DISTNAME=	v0.2
PKGNAME=	${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	https://codeload.github.com/giotto-ai/giotto-tda/legacy.tar.gz/
EXTRACT_SUFX=	.2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://codeload.github.com/giotto-ai/giotto-tda/legacy.tar.gz/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
