# $NetBSD$

DISTNAME=	qubovert-1.2.3
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/12/8e/a212a6516e3eaf211c4a260ac59cfec3bfd7dc6b5926da9f91f0fb7d2b64/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/12/8e/a212a6516e3eaf211c4a260ac59cfec3bfd7dc6b5926da9f91f0fb7d2b64/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
