# $NetBSD$

DISTNAME=	go-datadog-go-20210107
GITHUB_PROJECT=	datadog-go
GITHUB_TAG=	8a12112
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=DataDog/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/DataDog/datadog-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}*
GO_SRCPATH=	github.com/DataDog/datadog-go

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
