# $NetBSD$

DISTNAME=	pip-gui-tools-0.0.5
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://files.pythonhosted.org/packages/e2/11/304cdc1db059dbfca9bbacc98ec73422a576c9cf432c0babe149e3249ba8/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/e2/11/304cdc1db059dbfca9bbacc98ec73422a576c9cf432c0babe149e3249ba8/
COMMENT=	A tool for python pip package management
LICENSE=	mit

#DEPENDS+=	${PYPKGPREFIX}-pip>=20.2.3:../../devel/py-pip
#DEPENDS+=	${PYPKGPREFIX}-flask>=1.1.2:../../www/py-flask
#DEPENDS+=	# TODO: pytest>=0
#DEPENDS+=	# TODO: wheel-inspect>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
