# $NetBSD$

GITHUB_PROJECT=	clasp
DISTNAME=	clasp-3.3.5-source
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=potassco/}
GITHUB_RELEASE=	v3.3.5

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/potassco/clasp/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/clasp-3.3.5
USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
