# $NetBSD$

DISTNAME=	spartyjet-4.0.2
CATEGORIES=	category
MASTER_SITES=	https://spartyjet.hepforge.org/releases/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://spartyjet.hepforge.org/releases/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
