# $NetBSD$

DISTNAME=	go-gizmo-1.3.6
GITHUB_PROJECT=	gizmo
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=nytimes/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/nytimes/gizmo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	flogo-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/nytimes/gizmo

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
