# $NetBSD$

GITHUB_PROJECT=	gizmo
GITHUB_TAG=	v1.3.6
DISTNAME=	v1.3.6
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=nytimes/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/nytimes/gizmo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gizmo-1.3.6
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
