# $NetBSD$

DISTNAME=	atelierb-free-4.5.1
CATEGORIES=	category
MASTER_SITES=	https://www.atelierb.eu/wp-content/uploads/2021/03/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.atelierb.eu/wp-content/uploads/2021/03/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		# none

.include "../../mk/bsd.pkg.mk"
