# $NetBSD$

GITHUB_PROJECT=	Castro
GITHUB_TAG=	20.10
DISTNAME=	20.10
PKGNAME=	${GITHUB_PROJECT:tl}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=AMReX-Astro/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/AMReX-Astro/Castro/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/Castro-20.10

USE_LANGUAGES=	c c++ fortran

.include "../../mk/bsd.pkg.mk"
