# $NetBSD$

DISTNAME=	pygtrie-2.4.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/3c/93/557455c974a21dd7ec0da309b9223952457c1999072bfe1f8f47f6091eab/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/3c/93/557455c974a21dd7ec0da309b9223952457c1999072bfe1f8f47f6091eab/
COMMENT=	Pure Python trie data structure implementation
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
