# $NetBSD$

DISTNAME=	mixmax_release_200final
CATEGORIES=	category
MASTER_SITES=	https://mixmax.hepforge.org/downloads/
EXTRACT_SUFX=	.zip

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://mixmax.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	c c++
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
