# $NetBSD$

DISTNAME=	pytest-datadir-1.3.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/f2/a0/cf0d9240a9905688c4d4269f66c17a160fc0fcfec13963e65949c3109fc0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/gabrielcnr/pytest-datadir
COMMENT=	pytest plugin for test data directories and files
LICENSE=	mit

BUILD_DEPENDS+=	py-setuptools_scm>=0:../../devel/py-setuptools_scm
DEPENDS+=	# TODO: pytest>=2.7.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
