# $NetBSD$

DISTNAME=	blackhawk_v1.2
PKGNAME=	blackhawk-1.2
CATEGORIES=	math
MASTER_SITES=	https://blackhawk.hepforge.org/downloads/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://blackhawk.hepforge.org/
COMMENT=	Calculation of the Hawking evaporation spectra of any black hole
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
