# $NetBSD$

DISTNAME=	reactive-papi-1.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/8b/89/18e654d1910d2fd7d33eaaa94677eb4f5b454a5163ac40cacf813ecf7f55/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/8b/89/18e654d1910d2fd7d33eaaa94677eb4f5b454a5163ac40cacf813ecf7f55/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

BUILD_DEPENDS+=	py-setuptools_scm>=0:../../devel/py-setuptools_scm

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
