# $NetBSD$

DISTNAME=	ukui-control-center_1.1.6.orig
CATEGORIES=	category
MASTER_SITES=	http://deb.debian.org/debian/pool/main/u/ukui-control-center/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://deb.debian.org/debian/pool/main/u/ukui-control-center/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=			${WRKDIR}/ukui-control-center
USE_PKGLOCALEDIR=	yes

.include "../../mk/bsd.pkg.mk"
