# $NetBSD$

DISTNAME=	ukui-control-center_1.1.6.orig
PKGNAME=	ukui-control-center-1.1.6
CATEGORIES=	category
MASTER_SITES=	http://deb.debian.org/debian/pool/main/u/ukui-control-center/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://deb.debian.org/debian/pool/main/u/ukui-control-center/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=			${WRKDIR}/ukui-control-center

USE_PKGLOCALEDIR=	yes

.include "../../mk/bsd.pkg.mk"
