# $NetBSD$

DISTNAME=	vivaldi-stable-3.2.1967.41-1.x86_64
PKGNAME=	vivaldi-3.2.1967.41
CATEGORIES=	www
MASTER_SITES=	https://downloads.vivaldi.com/stable/
EXTRACT_SUFX=	.rpm

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://downloads.vivaldi.com/stable/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
