# $NetBSD$

GITHUB_PROJECT=	releaseme
GITHUB_TAG=	v2.4.3
DISTNAME=	v2.4.3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=KDE/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/KDE/releaseme/
COMMENT=	Tool for software hosted on KDE infrastructure
LICENSE=	gnu-gpl-v3

WRKSRC=		${WRKDIR}/releaseme-2.4.3

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
