# $NetBSD$

DISTNAME=	nusigma-1.19-pyr
PKGNAME=	nusigma-pyr-1.19
CATEGORIES=	math
MASTER_SITES=	http://wimpsim.astroparticle.se/code/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://wimpsim.astroparticle.se/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++ fortran

.include "../../mk/bsd.pkg.mk"
