# $NetBSD$

DISTNAME=	nusigma-1.19-pyr
CATEGORIES=	category
MASTER_SITES=	http://wimpsim.astroparticle.se/code/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://wimpsim.astroparticle.se/code/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LANGUAGES=	fortran

.include "../../mk/bsd.pkg.mk"
