# $NetBSD$

DISTNAME=	kira-2.0
CATEGORIES=	math
MASTER_SITES=	https://kira.hepforge.org/downloads?f=releases/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://kira.hepforge.org/
COMMENT=	Feynman integral reduction program
LICENSE=	gnu-gpl-v3

USE_LANGUAGES=	c c++

#C++14

.include "../../devel/meson/build.mk"
.include "../../devel/zlib/buildlink3.mk"
.include "../../wip/libginac/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
