# $NetBSD$

DISTNAME=	catalogue-2.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/28/e2/fe570c613202e193ab92ad2725949bdf6c3979c5e2e84f02ef2c9af1aaec/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/28/e2/fe570c613202e193ab92ad2725949bdf6c3979c5e2e84f02ef2c9af1aaec/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
