# $NetBSD$

DISTNAME=	PyTrie3-0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/eb/5f/6fd616f7eff1f5803bc77238eac5e517f979f1cd0aeeb9ed856c9a4e023f/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/datapublica/pytrie3
COMMENT=	A pure Python implementation of the trie data structure
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
