# $NetBSD$

DISTNAME=	PyTrie3-0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/Py//tl}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=P/PyTrie3/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/datapublica/pytrie3
COMMENT=	Python implementation of the trie data structure
LICENSE=	modfiied-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/disutils.mk"
.include "../../mk/bsd.pkg.mk"
