kinematics:
  incoming_momenta: [p1,p2]
  outgoing_momenta: [q1,q2]
  momentum_conservation: [q1,p1+p2-q2]
  kinematic_invariants:
     - [s,  2]
     - [t,  2]
     - [m12,  2] # m12 = m1^2
     - [m22,  2] # m22 = m2^2
  scalarproduct_rules:
     - [[p1,p1],  0]
     - [[p2,p2],  0]
     - [[q2,q2],  0]
     - [[p1+p2, p1+p2], s]
     - [[q2-p1, q2-p1], t]
     - [[q2-p2, q2-p2], -s-t+m12] # -s-t-m1^2
  symbol_to_replace_by_one: m12

