# $NetBSD$

DISTNAME=	BertiniSource_v1.6
CATEGORIES=	category
MASTER_SITES=	https://bertini.nd.edu/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://bertini.nd.edu/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/BertiniSource_v16
GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
