# $NetBSD$

GITHUB_PROJECT=	imgui-go
GITHUB_TAG=	v2.5.0
DISTNAME=	v2.5.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=inkyblackness/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/inkyblackness/imgui-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/imgui-go-2.5.0
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
