# $NetBSD$

DISTNAME=	go-zap-1.16.0
GITHUB_PROJECT=	zap
GITHUB_TAG=	v1.16.0
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=uber-go/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/uber-go/zap/
COMMENT=	Blazing fast, structured, leveled logging in Go
#LICENSE=	# TODO: (see mk/license.mk)

EXTRACT_USING=	bsdtar

GO_SRCPATH=	github.com/uber-go/zap/
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}


.include "../../mk/bsd.pkg.mk"
