# $NetBSD$

GITHUB_PROJECT=	b2
GITHUB_TAG=	2.0alpha6
DISTNAME=	2.0alpha6
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=bertiniteam/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/bertiniteam/b2/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/b2-2.0alpha6
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
