# $NetBSD$

DISTNAME=	IoTPy-1.1.0
PKGNAME=	${PYPKGPREFIX}-ioTPy-1.1.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/96/c4/8aa416a8398732985094641e8eb8386cefdbb5ce8e06b72a19a229087044/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/96/c4/8aa416a8398732985094641e8eb8386cefdbb5ce8e06b72a19a229087044/
COMMENT=	Helps you to build applications that operate on streams of data.
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
