# $NetBSD$

DISTNAME=	aioreactive-0.14.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/03/f1/5b7218ab7ff5171f795976229d590c160b8d35e2a17289a99a4e0b405448/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/03/f1/5b7218ab7ff5171f795976229d590c160b8d35e2a17289a99a4e0b405448/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
