# $NetBSD$

GITHUB_PROJECT=	pdfcpu
GITHUB_TAG=	v0.3.4
DISTNAME=	v0.3.4
PKGNAME=	go-${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	print
MASTER_SITES=	${MASTER_SITE_GITHUB:=pdfcpu/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/pdfcpu/pdfcpu/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/pdfcpu-0.3.4

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
