# $NetBSD$

DISTNAME=	ewma-20201216
GITHUB_PROJECT=	ewma
GITHUB_TAG=	507017d748aae584fd5fa8c7448e0105598a0647
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=VividCortex/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/VividCortex/ewma/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ewma-507017d748aae584fd5fa8c7448e0105598a0647
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
