# $NetBSD$

DISTNAME=	singletonify-0.2.4
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/97/61/b297dab1cca05651aac73e93fd6e8083ae08bab7b549cb2d3f0ce7e92111/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Cologler/singletonify-python
COMMENT=	TODO: Short description of the package
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
