# $NetBSD$

DISTNAME=	efmlrs-2.1.3
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ee/f0/ab1af72bb71db7fd769a42b0bf4ffc34ebf1d8a3d1baf80abd240bc290a5/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ee/f0/ab1af72bb71db7fd769a42b0bf4ffc34ebf1d8a3d1baf80abd240bc290a5/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
