# $NetBSD$

DISTNAME=	ikpy-3.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=i/ikpy/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/9a/11/3e8276d1a105b68fba6f155f50980c48c540c046aa1ee49e5d5e7122a0fb/
COMMENT=	inverse kinematics library aiming performance and modularity
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
