# $NetBSD$

DISTNAME=	nulike-1.0.9
CATEGORIES=	math
MASTER_SITES=	https://nulike.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://nulike.hepforge.org/
COMMENT=	Likelihood calculations for neutrino telescope
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	fortran

MAKE_FILE=	makefile
.include "../../mk/bsd.pkg.mk"
