# $NetBSD$

DISTNAME=	go-flock-0.8.0
GITHUB_PROJECT=	flock
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gofrs/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gofrs/flock/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/flock-0.8.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
