# $NetBSD$

DISTNAME=	geppy-0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/51/bd/bf214364b3adc5c6d9f4ee8aaa6f01e3ceda7d1bd74b048af4bd953d6175/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ShuhuaGao/geppy
COMMENT=	A package for gene expression programming in Python
#LICENSE=	LGPL-3.0 License # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: deap>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
