# $NetBSD$

DISTNAME=	pysal-2.4.0
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pysal/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://pysal.org/
COMMENT=	Library of spatial analysis functions
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
