# $NetBSD$

DISTNAME=	ProB.linux64
CATEGORIES=	category
MASTER_SITES=	http://www3.hhu.de/stups/downloads/prob/tcltk/releases/1.10.2/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www3.hhu.de/stups/downloads/prob/tcltk/releases/1.10.2/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ProB
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
