# $NetBSD$

DISTNAME=	scramp-1.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pg8000/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/58/c6/f077e1f4fb40d7a56662dd6874527e7f9d626323a1cd7261d59abeb52789/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
