# $NetBSD$

DISTNAME=	uncertainty-wizard-0.1.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/94/d0/513f369a346e1ba0705181ba68d9b2ec46498178134f24e495a49c9ae1c4/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/94/d0/513f369a346e1ba0705181ba68d9b2ec46498178134f24e495a49c9ae1c4/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
