# $NetBSD$

DISTNAME=	uncertainty-wizard-0.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=u/uncertainty-wizard/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/94/d0/513f369a346e1ba0705181ba68d9b2ec46498178134f24e495a49c9ae1c4/
 COMMENT=	Quick access to uncertainty and confidence of Keras networks
LICENSE=	mit

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
