# $NetBSD$

DISTNAME=	arramooz_pysqlite-0.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/9b/d3/f54c62a4af4590f8c9b952df341f74469355973c0f44e80644498ecb235f/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://arramooz-pysqlite.sourceforge.net/
COMMENT=	Arramooz: Arabic Dictionary for Morphological analysis - python + sqlite
LICENSE=	gnu-gpl-v1 OR gnu-gpl-v2 OR gnu-gpl-v3

DEPENDS+=	# TODO: pyarabic>=0.6.2

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
