# $NetBSD$

GITHUB_PROJECT=	ukui-window-switch
GITHUB_TAG=	v2.0.3
DISTNAME=	v2.0.3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/ukui-window-switch/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ukui-window-switch-2.0.3
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
