# $NetBSD$

DISTNAME=	transport-20210118
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	transport
GITHUB_TAG=	0a5b43e8f694a364434c30f30d7495ee13ab7e6a
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=pion/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/pion/transport/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/transport-0a5b43e8f694a364434c30f30d7495ee13ab7e6a
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
