# $NetBSD$

DISTNAME=	jewel-2.2.0
CATEGORIES=	category
MASTER_SITES=	https://jewel.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://jewel.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	fortran

.include "../../mk/bsd.pkg.mk"
