# $NetBSD$

DISTNAME=	lbmpy-0.2.12
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://files.pythonhosted.org/packages/b8/99/caa3575a2015da807db49bab11eebdc7f898e3cf94b5baf2e1ba434449b8/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/b8/99/caa3575a2015da807db49bab11eebdc7f898e3cf94b5baf2e1ba434449b8/
COMMENT=	Code Generation for Lattice Boltzmann Methods
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
