name: CI
on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.12.x"
          - "1.13.x"
          - "1.14.x"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Download modules
        env:
          GOPROXY: https://proxy.golang.org
        run: go mod download
      - name: Run tests
        run: ./ci/test.sh
        shell: bash

  bench:
    name: Benchmarks
    needs: test
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.14.x"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Download modules
        env:
          GOPROXY: https://proxy.golang.org
        run: go mod download
      - name: Install tools
        env:
          GOPROXY: https://proxy.golang.org
        run: go get golang.org/x/perf/cmd/benchstat
      - name: Run benchmarks
        run: ./ci/bench.sh
      - name: Upload statistics
        uses: actions/upload-artifact@v1
        with:
          name: Benchstat-Go${{ matrix.go }}
          path: benchstats
