# $NetBSD$

DISTNAME=	beniget-0.3.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/50/b9/7d864a50d5d2821686d4374400de45c8e0678e553657343f5f0ea6aff98d/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/serge-sans-paille/beniget/
COMMENT=	Extract semantic information about static Python code
#LICENSE=	BSD 3-Clause # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: gast~=0.4.0>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
