# $NetBSD$

DISTNAME=	JetVHeto-3.0.0
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	category
MASTER_SITES=	https://jetvheto.hepforge.org/downloads/
EXTRACT_SUFX=	.tgz

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://jetvheto.hepforge.org/
COMMENT=	Ast program to perform NNLL resummation for jet-veto 
LICENSE=	gnu-gpl-v3

USE_LANGUAGES=	# none
USE_TOOLS+=	gmake

.include "../../math/py-numpy/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
