# $NetBSD$

DISTNAME=	pysbd-0.3.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/py//}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pysbd/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://nipunsadvilkar.github.io/
COMMENT=	pysbd (Python Sentence Boundary Disambiguation) is a rule-based sentence boundary detection that works out-of-the-box across many languages
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
