# $NetBSD$

GITHUB_PROJECT=	spectacle
GITHUB_TAG=	v20.08.1
DISTNAME=	v20.08.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=KDE/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/KDE/spectacle/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/spectacle-20.08.1
USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
