# $NetBSD$

DISTNAME=	segregation-1.5.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/5b/5a/c576982de17acfc6ec836dbaae6be334fb0aaffa6c18776001d454116d35/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/5b/5a/c576982de17acfc6ec836dbaae6be334fb0aaffa6c18776001d454116d35/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
