# $NetBSD$

DISTNAME=	stdeb-0.10.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/13/7e/bd2cfda795d84e4445305cd53c4be4a3ec6fad2546ad2a2b79cc7906b6d7/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/astraw/stdeb
COMMENT=	Python to Debian source package conversion utility
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
