# $NetBSD$

DISTNAME=	streamlit-0.70.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/3a/99/1b3a82fb89c7d16dcba4bfbca6fbff5849a6f3e091f516c67a0761e69cc0/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/3a/99/1b3a82fb89c7d16dcba4bfbca6fbff5849a6f3e091f516c67a0761e69cc0/
COMMENT=	The fastest way to build data apps in Python
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
