# $NetBSD$

DISTNAME=	streamlit-0.70.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/3a/99/1b3a82fb89c7d16dcba4bfbca6fbff5849a6f3e091f516c67a0761e69cc0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/3a/99/1b3a82fb89c7d16dcba4bfbca6fbff5849a6f3e091f516c67a0761e69cc0/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
