# $NetBSD$

DISTNAME=	v0.0
PKGNAME=	${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go101/go-skia/releases/tag/}
EXTRACT_SUFX=	.2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go101/go-skia/releases/tag/ # TODO: check
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none


.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
