# $NetBSD$

DISTNAME=	giotto-tda-0.5.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
GITHUB_PROJECT=	giotto-tda
GITHUB_TAG=	refs/tags/v0.5.1
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=giotto-ai/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/giotto-ai/giotto-tda/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
