# $NetBSD$

DISTNAME=	allure-pytest-2.8.18
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/0c/3f/04b2b0b072c922158eb86c9f72fe09a51aea2521ae95888fd9c289c5e1ae/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/0c/3f/04b2b0b072c922158eb86c9f72fe09a51aea2521ae95888fd9c289c5e1ae/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
