integralfamilies:
  - name: F1
    loop_momenta: [p1,p2]
    top_level_sectors: [511]
    magic_relations: true
    propagators:
      - ["p1", 0]
      - ["p2", "m2"]
      - ["p1-p2", "m2"]
      - ["p1+k1", 0]
      - ["p2+k1", "m2"]
      - ["p1-k3", 0] 
      - ["p2-k3", "m2"]
      - ["p1-k2-k3", 0] 
      - ["p2-k2-k3", "m2"]
  
  - name: F2
    loop_momenta: [p1,p2]
    top_level_sectors: [511]
    magic_relations: true
    propagators:
      - ["p1", "m2"]
      - ["p2", "m2"] 
      - ["p1-p2", 0]
      - ["p1+k3", "m2"]
      - ["p2+k3", "m2"]
      - ["p1-k2", "m2"]
      - ["p2-k2", "m2"] 
      - ["p1-p2+k1", 0]
      - ["p2-k2-k1", "m2"]
