# $NetBSD$

GITHUB_PROJECT=	go-sciter
GITHUB_TAG=	go-1.9
DISTNAME=	go-1.9
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=sciter-sdk/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/sciter-sdk/go-sciter/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=	${WRKDIR}/go-sciter-go-1.9

.include "../../mk/bsd.pkg.mk"
