# $NetBSD$

DISTNAME=	archspec-0.1.2
GITHUB_PROJECT=	archspec
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=archspec/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/archspec/archspec/
COMMENT=	Library for detecting, labeling, and reasoning about microarchitectures
LICENSE=	apache-2.0 OR mit

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
