# $NetBSD$

DISTNAME=	archspec-0.1.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=a/archspec/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/archspec/archspec/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/application.mk"
.include "../../mk/bsd.pkg.mk"
