# $NetBSD$

DISTNAME=	bc-python-hcl2-0.3.11
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/2e/dd/4f826a3aaa2f6b64f055e9294c797f6b1a9b8035ac07b6fd943684c1dd55/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/amplify-education/python-hcl2
COMMENT=	Parser for HCL2
LICENSE=	mit

DEPENDS+=	py-lark-parser>=0.7.8,<0.8.0:../../wip/py-lark-parser

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
