# $NetBSD$

DISTNAME=	bc-python-hcl2-0.3.18
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/88/3b/864cc7c4793ec8874a02f293d40f36371b6dbcff414e108a72c95069fd79/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/amplify-education/python-hcl2
COMMENT=	A parser for HCL2
LICENSE=	mit

DEPENDS+=	# TODO: lark-parser>=0.10.0,<0.11.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
