# $NetBSD$

DISTNAME=	cps-state-replication-0.0.1
GITHUB_PROJECT=	cps-state-replication
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	sysutils cad python
MASTER_SITES=	${MASTER_SITE_GITHUB:=sbaresearch/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/sbaresearch/cps-state-replication/
COMMENT=	Replicating States of Cyber-physical Systems to Digital Twins
LICENSE=	mit


.include "../../mk/bsd.pkg.mk"
