# $NetBSD$

DISTNAME=	purpose-master
CATEGORIES=	category
MASTER_SITES=	https://invent.kde.org/frameworks/purpose/-/archive/master/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://invent.kde.org/frameworks/purpose/-/archive/master/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
