# $NetBSD$

DISTNAME=	tstl-1.2.29.macosx-10.14-x86_64
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/55/2b/d248e3b7fb3e84c153c79d63a474fab14d89a827d271d82948719beec5ed/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/55/2b/d248e3b7fb3e84c153c79d63a474fab14d89a827d271d82948719beec5ed/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/opt
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
