# $NetBSD$

GITHUB_PROJECT=	ukui-notification-daemon
DISTNAME=	ukui-notification-daemon_1.0.1.orig
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
GITHUB_RELEASE=	v1.0.1

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/ukui-notification-daemon/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ukui-notification-daemon
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
