# $NetBSD$

DISTNAME=	msolve-v0.1.0
PKGNAME=	${DISTNAME:S,-v,-,}
CATEGORIES=	category
MASTER_SITES=	https://msolve.lip6.fr/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://msolve.lip6.fr/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/msolve_beta
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
