# $NetBSD$

DISTNAME=	msolve-v0.1.0
PKGNAME=	${DISTNAME:S,-v,-,}
CATEGORIES=	math
MASTER_SITES=	https://msolve.lip6.fr/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://msolve.lip6.fr/downloads/
COMMENT=	Library for solving multivariate polynomial systems
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/msolve_beta

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
