# $NetBSD$

DISTNAME=	git_code_debt-1.1.0
PKGNAME=	${PYPKGPREFIX}-git-code-debt-1.1.0
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=g/git_code_debt/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/c3/e7/7b3159983aadc2372e71236e62bee35eb4f76f4c9da7b79e068c8fd10048/
OMMENT=	Dashboard for monitoring code debt in a git repository
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
