# $NetBSD$

DISTNAME=	git_code_debt-1.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/c3/e7/7b3159983aadc2372e71236e62bee35eb4f76f4c9da7b79e068c8fd10048/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/c3/e7/7b3159983aadc2372e71236e62bee35eb4f76f4c9da7b79e068c8fd10048/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
