# $NetBSD$

DISTNAME=	Expression-0.45.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:tl}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=E/Expression/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/cognitedata/expression
COMMENT=	Practical functional programming for Python 3.8+
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
