# $NetBSD$

DISTNAME=	Expression-0.45.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/f2/13/8b5872765c8c11d1b9e37c1c76dacc334da9fd6ae8aaa2e7efb9899053a6/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/f2/13/8b5872765c8c11d1b9e37c1c76dacc334da9fd6ae8aaa2e7efb9899053a6/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
