# $NetBSD$

DISTNAME=	spherical_geometry-1.2.19
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/5c/0e/30048883b7d02ee9432011d5b6861b17d93cd3c81da6179c7e20489cefa4/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/5c/0e/30048883b7d02ee9432011d5b6861b17d93cd3c81da6179c7e20489cefa4/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
