# $NetBSD$

DISTNAME=	spherical_geometry-1.2.19
PKGNAME=	${PYPKGPREFIX}-spherical-geometry-1.2.19
CATEGORIES=	math
MASTER_SITES=	https://files.pythonhosted.org/packages/5c/0e/30048883b7d02ee9432011d5b6861b17d93cd3c81da6179c7e20489cefa4/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/spacetelescope
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../math/py-numpy/buildlink3.mk"
.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
