# $NetBSD$

DISTNAME=	vcl-2.0.9
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	govcl
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ying32/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ying32/govcl/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/govcl-2.0.9
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
