# $NetBSD$

DISTNAME=	parameterizedtestcase-0.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/99/14/4b82711b0c6a377c1e63f44641d3f4c63ec1f3acc6cc5e2d37109fd711ca/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/msabramo/python_unittest_parameterized_test_case
COMMENT=	Parameterized tests for Python's unittest module
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
