# $NetBSD$

DISTNAME=	pymatgen-2020.7.18
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	biology
MASTER_SITES=	https://files.pythonhosted.org/packages/3f/5a/dc2fcff466021d3200ff84e045ef8b8d94bd176d417c869f6357233ceef4/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://pymatgen.org/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
