# $NetBSD$

DISTNAME=	go-pcidb-0.5.0
GITHUB_PROJECT=	pcidb
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=jaypipes/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/jaypipes/pcidb/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/pcidb-0.5.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
