# $NetBSD$

DISTNAME=	samurai-2.1.1
CATEGORIES=	category
MASTER_SITES=	http://www.hepforge.org/archive/samurai/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.hepforge.org/archive/samurai/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_TOOLS+=	pkg-config
USE_LANGUAGES=	fortran

PKGCONFIG_OVERRIDE+=	samurai.pc.in

.include "../../mk/bsd.pkg.mk"
