# $NetBSD$

DISTNAME=	alsa-1.0.27.2-3.2.1.x86_64
CATEGORIES=	category
MASTER_SITES=	http://ftp5.gwdg.de/pub/opensuse/discontinued/distribution/13.1/repo/oss/suse/x86_64/
EXTRACT_SUFX=	.rpm

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ftp5.gwdg.de/pub/opensuse/discontinued/distribution/13.1/repo/oss/suse/x86_64/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
