# $NetBSD$

DISTNAME=	PackageKit-1.2.0
CATEGORIES=	category
MASTER_SITES=	https://www.freedesktop.org/software/PackageKit/releases/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.freedesktop.org/software/PackageKit/releases/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		c c++

.include "../../devel/meson/build.mk"
.include "../../mk/bsd.pkg.mk"
