# $NetBSD$

DISTNAME=	sdm-1.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
GITHUB_PROJECT=	PySDM
GITHUB_TAG=	refs/tags/v1.2
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=atmos-cloud-sim-uj/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/atmos-cloud-sim-uj/PySDM/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
