# $NetBSD$

DISTNAME=	proVBFH-inclusive-2.0.2
PKGNAME=	${DISTNAME:tl:S/-inclusive//}
CATEGORIES=	math
MASTER_SITES=	https://provbfh.hepforge.org/downloads/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://provbfh.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

HAS_CONFIGURE=	yes
USE_LANGUAGES=	fortran

.include "../../mk/bsd.pkg.mk"
