# $NetBSD$

DISTNAME=	blis-0.7.4
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=b/blis/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/b1/54/b0de9905ee80aebd64c333bc112cacfe06849a9b5a7230a02dfde73e7aad/
COMMENT=	BLAS-like linear algebra library, as a self-contained C-extension
LICENSE=	mit

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
