# $NetBSD$

DISTNAME=	flexiblesusy-2.5.0
GITHUB_PROJECT=	FlexibleSUSY
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=FlexibleSUSY/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/FlexibleSUSY/FlexibleSUSY/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/FlexibleSUSY-2.5.0
GNU_CONFIGURE=	yes
USE_LANGUAGES=	c++ fortran

.include "../../mk/bsd.pkg.mk"
