# $NetBSD$

GITHUB_PROJECT=	min
GITHUB_TAG=	v1.15.0
DISTNAME=	v1.15.0
PKGNAME=	minbrowser-${DISTNAME:S,^v,,}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=minbrowser/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/minbrowser/min/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/min-1.15.0

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
