# $NetBSD$

DISTNAME=	voila-0.2.10
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/01/95/2f7ab2b1ed417b61d3f20873e61e94fd9f2c5ba1d16e197fffff527cd2be/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/01/95/2f7ab2b1ed417b61d3f20873e61e94fd9f2c5ba1d16e197fffff527cd2be/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
