# $NetBSD$

DISTNAME=	debian-distro-info-0.24.0.45a5
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/cb/d2/e06ae901988f1900122815bbb67be36b73176cd396c38bd8c11448a8380a/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/cb/d2/e06ae901988f1900122815bbb67be36b73176cd396c38bd8c11448a8380a/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
