# $NetBSD$

DISTNAME=	idyntree-3.0.0
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=i/idyntree/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/32/d3/c13799c10e5c3e7ad5cedab3ec1c64d1a8f97a8a7f88fd07d1ecaf565381/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)


.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
