# $NetBSD$

DISTNAME=	idyntree-3.0.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/32/d3/c13799c10e5c3e7ad5cedab3ec1c64d1a8f97a8a7f88fd07d1ecaf565381/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/32/d3/c13799c10e5c3e7ad5cedab3ec1c64d1a8f97a8a7f88fd07d1ecaf565381/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
