# $NetBSD$

DISTNAME=	dist-20190702
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	go-dist
GITHUB_TAG=	2acdd84d3dfb194bb39f6e0582dd4de9668303eb
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=200sc/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/200sc/go-dist/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-dist-2acdd84d3dfb194bb39f6e0582dd4de9668303eb
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
