# $NetBSD$

DISTNAME=	CASPy3-1.2.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/7d/32/e1e71579bf24178638eef41454f3d75472fb782770dcbdd04bad2bc81ce3/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Secozzi/CASPy
COMMENT=	A program that provides a GUI and a CLI to a symbolic computation and computer algebra system python library, SymPy
#LICENSE=	GPLv3+ # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: P>=0
DEPENDS+=	# TODO: y>=0
DEPENDS+=	# TODO: Q>=0
DEPENDS+=	# TODO: t>=0
DEPENDS+=	# TODO: 5>=0
DEPENDS+=	# TODO: =>=0
DEPENDS+=	# TODO: 5>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 1>=0
DEPENDS+=	# TODO: 4>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 0>=0
DEPENDS+=	# TODO: P>=0
DEPENDS+=	# TODO: y>=0
DEPENDS+=	# TODO: Q>=0
DEPENDS+=	# TODO: t>=0
DEPENDS+=	# TODO: W>=0
DEPENDS+=	# TODO: e>=0
DEPENDS+=	# TODO: b>=0
DEPENDS+=	# TODO: E>=0
DEPENDS+=	# TODO: n>=0
DEPENDS+=	# TODO: g>=0
DEPENDS+=	# TODO: i>=0
DEPENDS+=	# TODO: n>=0
DEPENDS+=	# TODO: e>=0
DEPENDS+=	# TODO: =>=0
DEPENDS+=	# TODO: 5>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 1>=0
DEPENDS+=	# TODO: 4>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 0>=0
DEPENDS+=	# TODO: s>=0
DEPENDS+=	# TODO: y>=0
DEPENDS+=	# TODO: m>=0
DEPENDS+=	# TODO: p>=0
DEPENDS+=	# TODO: y>=0
DEPENDS+=	# TODO: =>=0
DEPENDS+=	# TODO: 1>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 5>=0
DEPENDS+=	# TODO: p>=0
DEPENDS+=	# TODO: y>=0
DEPENDS+=	# TODO: p>=0
DEPENDS+=	# TODO: e>=0
DEPENDS+=	# TODO: r>=0
DEPENDS+=	# TODO: c>=0
DEPENDS+=	# TODO: l>=0
DEPENDS+=	# TODO: i>=0
DEPENDS+=	# TODO: p>=0
DEPENDS+=	# TODO: =>=0
DEPENDS+=	# TODO: 1>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 7>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 0>=0
DEPENDS+=	# TODO: c>=0
DEPENDS+=	# TODO: l>=0
DEPENDS+=	# TODO: i>=0
DEPENDS+=	# TODO: c>=0
DEPENDS+=	# TODO: k>=0
DEPENDS+=	# TODO: =>=0
DEPENDS+=	# TODO: 7>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 1>=0
DEPENDS+=	# TODO: .>=0
DEPENDS+=	# TODO: 1>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
