jobs:
 - kira2math:
    target:
#     - {topologies: [topo4], sectors: [127], r: 7, s: 2, d: 0}
#     - {topologies: [topo4], sectors: [127], r: 8, s: 1, d: 1}
 - kira2math:
    target:
     - {topologies: [topo4], sectors: [127], r: 7, s: 3, d: 0}
