# $NetBSD$

DISTNAME=	gota-20200120
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	gota
GITHUB_TAG=	d8f1f578e815b4c252eeed30db80bcd271c7d92c
PKGVERSION=	1
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-gota/}

MAINTAINER=     kamelderouiche@yahoo.com
HOMEPAGE=       https://github.com/go-gota/gota/
COMMENT=        DataFrames and data wrangling in Go
LICENSE=        apache-2.0

GO_DIST_BASE=   gota-${GITHUB_TAG}
GO_SRCPATH=     github.com/go-gota/gota

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
