# $NetBSD$

DISTNAME=	elegent-1.3.0
PKGNAME=	elegent-hepforge-1.3.0
GITHUB_PROJECT=	elegent
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=jan-kaspar/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/jan-kaspar/elegent/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
