# $NetBSD$

DISTNAME=	elegent-1.3.0
GITHUB_PROJECT=	elegent
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=jan-kaspar/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/jan-kaspar/elegent/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
