# $NetBSD$

DISTNAME=	go-easyjson-0.7.4.1
GITHUB_PROJECT=	easyjson
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=mailru/}
GITHUB_TAG=	${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/mailru/easyjson/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/easyjson-0.7.4.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
