# $NetBSD$

DISTNAME=	thinc-8.0.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ac/15/282edb3e44d67c64d77dd94af9542e26fe7e5256fda8f2242b169bb146b0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ac/15/282edb3e44d67c64d77dd94af9542e26fe7e5256fda8f2242b169bb146b0/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
