# $NetBSD$

DISTNAME=	thinc-8.0.2
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc
MASTER_SITES=	${MASTER_SITE_PYPI:=t/thinc/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/explosion/thinc
COMMENT=	Refreshing functional take on deep learning
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
