# $NetBSD$

DISTNAME=	plottr-0.2.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/41/d5/36bd15aa3fbd82273c0b2ce3f65a281d0c1f06126e389a917f3cd5be8787/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/41/d5/36bd15aa3fbd82273c0b2ce3f65a281d0c1f06126e389a917f3cd5be8787/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
