# $NetBSD$

DISTNAME=	go-dbus-5.0.3
GITHUB_PROJECT=	dbus
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=godbus/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/godbus/dbus/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=	github.com/godbus/dbus
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
