# $NetBSD$

DISTNAME=	go-eris-0.5.0
GITHUB_PROJECT=	eris
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=rotisserie/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/rotisserie/eris/
COMMENT=	Provides a better way to handle trace and log errors in Go
LICENSE=	mit

GO_DIST_BASE=	eris-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/rotisserie/eris

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
