# $NetBSD$

GITHUB_PROJECT=	eris
GITHUB_TAG=	v0.4.1
DISTNAME=	v0.4.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=rotisserie/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/rotisserie/eris/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/eris-0.4.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
