# $NetBSD$

DISTNAME=	tobler-0.7.0
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc
MASTER_SITES=	${MASTER_SITE_PYPI:=t/tobler/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/e1/c6/5dcd4945b4bd28a26df1ea9da9a4cafb27ed48393d8095447a488a635f22/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
