# $NetBSD$

DISTNAME=	tobler-0.7.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/e1/c6/5dcd4945b4bd28a26df1ea9da9a4cafb27ed48393d8095447a488a635f22/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/e1/c6/5dcd4945b4bd28a26df1ea9da9a4cafb27ed48393d8095447a488a635f22/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
