# $NetBSD$

GITHUB_PROJECT=	Pale-Moon
GITHUB_TAG=	28.13.0_Release
DISTNAME=	28.13.0_Release
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=MoonchildProductions/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/MoonchildProductions/Pale-Moon/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/Pale-Moon-28.13.0_Release

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
