# $NetBSD$

DISTNAME=	panel-0.10.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/91/c0/8227f85084e0adf28009703e34409a59df97605f584ecd1fca870c86a217/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/91/c0/8227f85084e0adf28009703e34409a59df97605f584ecd1fca870c86a217/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
