# $NetBSD$

DISTNAME=	srsly-2.4.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/fd/63/a9240c5e37b08e2fd9fc68a1ff30175f586d9d31a5f21529c4022ddcfc90/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/fd/63/a9240c5e37b08e2fd9fc68a1ff30175f586d9d31a5f21529c4022ddcfc90/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
