# $NetBSD$

DISTNAME=	constructive_geometries-0.7
PKGNAME=	${PYPKGPREFIX}-constructive-geometries-0.7
CATEGORIES=	math python
MASTER_SITES=	${MASTER_SITE_PYPI:=c/constructive_geometries/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/cmutel/constructive_geometries
COMMENT=	Simple tools to define world locations from a set of topological faces and set algebra
#LICENSE=	Copyright (c) 2016, Chris Mutel and Paul Scherrer Institute

DEPENDS+=	# TODO: country_converter>=0
DEPENDS+=	py-wrapt>=0:../../devel/py-wrapt

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
