# $NetBSD$

DISTNAME=	testing.common.database-2.0.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	databases python
MASTER_SITES=	${MASTER_SITE_PYPI:=t/testing.common.database/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/tk0miya/testing.common.database
COMMENT=	utilities for testing.* packages
LICENSE=	apache-2.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
