# $NetBSD$

DISTNAME=	dask-2020.12.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	parallel python
MASTER_SITES=	${MASTER_SITE_PYPI:=d/dask/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/dask/dask/
COMMENT=	Parallel PyData with Task Scheduling
LICENSE=	modified-bsd

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
