# $NetBSD$

DISTNAME=	notifiers-1.2.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	sysutils python
MASTER_SITES=	https://files.pythonhosted.org/packages/4f/36/4c300f55949b9be84284d51253ae48d564dc2c4f2bffb94f26c8c1485f07/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/notifiers/notifiers
COMMENT=	The easy way to send notifications
LICENSE=	mit

BUILD_DEPENDS+=	# TODO: alabaster==0.7.11#viasphinx>=0
BUILD_DEPENDS+=	# TODO: aspy.yaml==1.1.1#viapre-commit>=0
BUILD_DEPENDS+=	# TODO: atomicwrites==1.1.5#viapytest>=0
BUILD_DEPENDS+=	# TODO: attrs==18.1.0#viahypothesis,pytest>=0
BUILD_DEPENDS+=	# TODO: babel==2.6.0#viasphinx>=0
BUILD_DEPENDS+=	# TODO: bumpversion==0.5.3>=0
BUILD_DEPENDS+=	# TODO: certifi==2018.4.16#viarequests>=0
BUILD_DEPENDS+=	# TODO: cfgv==2.0.0#viapre-commit>=0
BUILD_DEPENDS+=	# TODO: chardet==3.0.4#viarequests>=0
BUILD_DEPENDS+=	# TODO: click==6.7#viapip-tools>=0
BUILD_DEPENDS+=	# TODO: codecov==2.0.15>=0
BUILD_DEPENDS+=	# TODO: coverage==4.5.1#viacodecov,pytest-cov>=0
BUILD_DEPENDS+=	# TODO: docutils==0.14#viasphinx>=0
BUILD_DEPENDS+=	# TODO: hypothesis==4.32.3>=0
BUILD_DEPENDS+=	# TODO: identify==1.1.4#viapre-commit>=0
BUILD_DEPENDS+=	# TODO: idna==2.7#viarequests>=0
BUILD_DEPENDS+=	# TODO: imagesize==1.0.0#viasphinx>=0
BUILD_DEPENDS+=	# TODO: importlib-metadata==0.18#viapluggy,pre-commit,pytest>=0
BUILD_DEPENDS+=	# TODO: jinja2==2.10.1#viasphinx>=0
BUILD_DEPENDS+=	# TODO: markupsafe==1.0#viajinja2>=0
BUILD_DEPENDS+=	# TODO: more-itertools==4.2.0#viapytest>=0
BUILD_DEPENDS+=	# TODO: nodeenv==1.3.2#viapre-commit>=0
BUILD_DEPENDS+=	# TODO: packaging==17.1#viapytest,sphinx>=0
BUILD_DEPENDS+=	# TODO: pip-tools==4.0.0>=0
BUILD_DEPENDS+=	# TODO: pluggy==0.12.0#viapytest>=0
BUILD_DEPENDS+=	# TODO: pre-commit==1.18.2>=0
BUILD_DEPENDS+=	# TODO: py==1.5.4#viapytest>=0
BUILD_DEPENDS+=	# TODO: pygments==2.2.0#viasphinx>=0
BUILD_DEPENDS+=	# TODO: pyparsing==2.2.0#viapackaging>=0
BUILD_DEPENDS+=	# TODO: pytest-cov==2.7.1>=0
BUILD_DEPENDS+=	# TODO: pytest==5.0.1>=0
BUILD_DEPENDS+=	# TODO: pytz==2018.5#viababel>=0
BUILD_DEPENDS+=	# TODO: pyyaml==5.1#viaaspy.yaml,pre-commit>=0
BUILD_DEPENDS+=	# TODO: requests==2.22.0#viacodecov,sphinx>=0
BUILD_DEPENDS+=	# TODO: six==1.11.0#viacfgv,more-itertools,packaging,pip-tools,pre-commit>=0
BUILD_DEPENDS+=	# TODO: snowballstemmer==1.2.1#viasphinx>=0
BUILD_DEPENDS+=	# TODO: sphinx-autodoc-annotation==1.0.post1>=0
BUILD_DEPENDS+=	# TODO: sphinx-rtd-theme==0.4.3>=0
BUILD_DEPENDS+=	# TODO: sphinx==2.2.0>=0
BUILD_DEPENDS+=	# TODO: sphinxcontrib-applehelp==1.0.1#viasphinx>=0
BUILD_DEPENDS+=	# TODO: sphinxcontrib-devhelp==1.0.1#viasphinx>=0
BUILD_DEPENDS+=	# TODO: sphinxcontrib-htmlhelp==1.0.2#viasphinx>=0
BUILD_DEPENDS+=	# TODO: sphinxcontrib-jsmath==1.0.1#viasphinx>=0
BUILD_DEPENDS+=	# TODO: sphinxcontrib-qthelp==1.0.2#viasphinx>=0
BUILD_DEPENDS+=	# TODO: sphinxcontrib-serializinghtml==1.1.3#viasphinx>=0
BUILD_DEPENDS+=	# TODO: toml==0.9.4#viapre-commit>=0
BUILD_DEPENDS+=	# TODO: urllib3==1.24.2#viarequests>=0
BUILD_DEPENDS+=	# TODO: virtualenv==16.0.0#viapre-commit>=0
BUILD_DEPENDS+=	# TODO: wcwidth==0.1.7#viapytest>=0
BUILD_DEPENDS+=	# TODO: zipp==0.5.1#viaimportlib-metadata>=0
DEPENDS+=	${PYPKGPREFIX}-requests>=2.21.0:../../devel/py-requests
DEPENDS+=	${PYPKGPREFIX}-jsonschema>=3.0.0:../../textproc/py-jsonschema
DEPENDS+=	${PYPKGPREFIX}-click>=7.0:../../devel/py-click
DEPENDS+=	# TODO: rfc3987>=1.3.8
TEST_DEPENDS+=	# TODO: pytest>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
