# $NetBSD$

GITHUB_PROJECT=	bluemonday
GITHUB_TAG=	v1.0.4
DISTNAME=	v1.0.4
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=microcosm-cc/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/microcosm-cc/bluemonday/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/bluemonday-1.0.4
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
