# $NetBSD$

DISTNAME=	fsspec-0.8.4
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/db/eb/934c2412e71785499f9fc888e5e3b72667d434dbb71631c3b0bd016c6597/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/db/eb/934c2412e71785499f9fc888e5e3b72667d434dbb71631c3b0bd016c6597/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
