# $NetBSD$

DISTNAME=	LoopTools-2.15
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	math
MASTER_SITES=	http://www.feynarts.de/looptools/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://www.feynarts.de/looptools/
COMMENT=	Package for evaluation of scalar and tensor one-loop integrals 
LICENSE=	gnu-gpl-v3

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++ fortran
MAKE_FILE=	makefile

.include "../../mk/bsd.pkg.mk"
