# $NetBSD$

DISTNAME=	LoopTools-2.15
CATEGORIES=	category
MASTER_SITES=	http://www.feynarts.de/looptools/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.feynarts.de/looptools/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
