# $NetBSD$

DISTNAME=	go-metrics-0.3.6
GITHUB_PROJECT=	go-metrics
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=armon/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/armon/go-metrics/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/armon/go-metrics

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
