# $NetBSD$

DISTNAME=	go-sockaddr-1.0.2
GITHUB_PROJECT=	go-sockaddr
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=hashicorp/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/hashicorp/go-sockaddr/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../mk/bsd.pkg.mk"
