# $NetBSD$

DISTNAME=	datashader-0.11.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/14/7a/2729f4210977e15b0c47e583fc3ef0cbfa53d91651fe8e55b36782ea3405/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/14/7a/2729f4210977e15b0c47e583fc3ef0cbfa53d91651fe8e55b36782ea3405/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
