integralfamilies:
  - name: "topo4"
    loop_momenta: [k1, k2]
    top_level_sectors: [127]
    propagators:
      - [ "k1", 0]                #1
      - [ "k2", 0]                #2
      - [ "p1-k1", 0]             #3
      - [ "p2-k2", 0]             #4
      - [ "p1+p2-q2-k1", "m12"]   #5
      - [ "p1-k1+k2", 0]          #6
      - [ "p1-q2-k1+k2", "m22"]   #7
      - [ "k1-q2", 0]             #8
      - [ "k2-p1-p2", 0]          #9
