# $NetBSD$

DISTNAME=	verboselogs-1.7
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://files.pythonhosted.org/packages/29/15/90ffe9bdfdd1e102bc6c21b1eea755d34e69772074b6e706cab741b9b698/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://verboselogs.readthedocs.io
COMMENT=	Verbose logging level for Python's logging module
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
