# $NetBSD$

DISTNAME=	go-goquery-1.6.0
GITHUB_PROJECT=	goquery
GITHUB_TAG=	v1.6.0
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=PuerkitoBio/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/PuerkitoBio/goquery/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=	github.com/uber-go/zap/
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
