# $NetBSD$

DISTNAME=	go-goquery-1.6.0
GITHUB_PROJECT=	goquery
GITHUB_TAG=	v1.6.0
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_GITHUB:=PuerkitoBio/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/PuerkitoBio/goquery/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/goquery-1.6.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
