# $NetBSD$

DISTNAME=	go-paho-mqtt-golang-1.3.1
GITHUB_PROJECT=	paho.mqtt.golang
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=eclipse/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/eclipse/paho.mqtt.golang/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/paho.mqtt.golang-1.3.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
