# $NetBSD$

DISTNAME=	wsaccel-0.6.2
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=w/wsaccel/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/52/46/9ef0744b434ac723ae3aeddcb92ab29af14f8912f53f47590b5a0db0b9d6/
COMMENT=	Accelerator for ws4py and AutobahnPython
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
