# $NetBSD$

DISTNAME=	palemoon-unstable-latest.linux-x86_64
CATEGORIES=	category
MASTER_SITES=	http://linux.palemoon.org/datastore/release/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://linux.palemoon.org/datastore/release/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/palemoon
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
