# $NetBSD$

DISTNAME=	kaleido-0.2.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
GITHUB_PROJECT=	Kaleido
GITHUB_TAG=	v0.2.1
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=plotly/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/plotly/Kaleido/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/Kaleido-0.2.1
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
