# $NetBSD$

DISTNAME=	kaleido-0.1.0
PKGNAME=	${PYPKGRPEFIX}-${DISTNAME}
GITHUB_PROJECT=	Kaleido
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_GITHUB:=plotly/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/plotly/Kaleido/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/Kaleido-0.1.0

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
