# $NetBSD$

DISTNAME=	rigidbodysimulator-0.2.5
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/c8/b4/7525395470cd0cb5af62dd99274f2f9b33359f4fcb0d6713dc45fad490d1/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/c8/b4/7525395470cd0cb5af62dd99274f2f9b33359f4fcb0d6713dc45fad490d1/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
