# $NetBSD$

GITHUB_PROJECT=	julia
DISTNAME=	julia-1.5.1
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=JuliaLang/}
GITHUB_RELEASE=	v1.5.1

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/JuliaLang/julia/
COMMENT=	Julia Language: A fresh approach to technical computing
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
