# $NetBSD$

GITHUB_PROJECT=	julia
DISTNAME=	julia-1.5.1
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=JuliaLang/}
GITHUB_RELEASE=	v1.5.1

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/JuliaLang/julia/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
