# $NetBSD$

GITHUB_PROJECT=	go-gtk
GITHUB_TAG=	release-0.1
DISTNAME=	release-0.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=mattn/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/mattn/go-gtk/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-gtk-release-0.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
