# $NetBSD$

DISTNAME=	eclipse-parallel-2020-06-R-linux-gtk-x86_64
CATEGORIES=	category
MASTER_SITES=	http://mirror.ufs.ac.za/eclipse/technology/epp/downloads/release/2020-06/R/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://mirror.ufs.ac.za/eclipse/technology/epp/downloads/release/2020-06/R/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
