# $NetBSD$

GITHUB_PROJECT=	gods
GITHUB_TAG=	v1.12.0
DISTNAME=	v1.12.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=emirpasic/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/emirpasic/gods/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gods-1.12.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
