# $NetBSD$

GITHUB_PROJECT=	konfig
GITHUB_TAG=	v0.8.3
DISTNAME=	v0.8.3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=lalamove/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/lalamove/konfig/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/konfig-0.8.3
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
