# $NetBSD$

GITHUB_PROJECT=	konfig
GITHUB_TAG=	v0.8.3
DISTNAME=	v0.8.3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=lalamove/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/lalamove/konfig/
COMMENT=	Composable, observable and performant config handling for Go
LICENSE=	mit

WRKSRC=		${WRKDIR}/konfig-0.8.3

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
