# $NetBSD$

DISTNAME=	SeismicMesh-3.0.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/f6/90/a8fc27ef48096a96fd962725bb9ae39f4b8d26ab87aa4450413d99ad6e72/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/f6/90/a8fc27ef48096a96fd962725bb9ae39f4b8d26ab87aa4450413d99ad6e72/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c c++

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
