# $NetBSD$

DISTNAME=	logging-20201216
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	logging
GITHUB_TAG=	f86d3277e5bc6376c4331ba848b332086e53f06e
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=pion/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/pion/logging/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/logging-f86d3277e5bc6376c4331ba848b332086e53f06e
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
