# $NetBSD$

DISTNAME=	qiskit-terra-0.15.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/7a/5b/3a26a3c2ce08bc6eed380874b7e33f6cb7d7c2b9699340486b08b3f9f18c/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/7a/5b/3a26a3c2ce08bc6eed380874b7e33f6cb7d7c2b9699340486b08b3f9f18c/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
