# $NetBSD$

DISTNAME=	libpysal-4.4.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/b7/77/64cdccc8502fb0b022fa0c651971ac520a81b0b1b1dc41db86a17ed1e50b/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/b7/77/64cdccc8502fb0b022fa0c651971ac520a81b0b1b1dc41db86a17ed1e50b/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
