# $NetBSD$

DISTNAME=	libpysal-4.4.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/b7/77/64cdccc8502fb0b022fa0c651971ac520a81b0b1b1dc41db86a17ed1e50b/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/b7/77/64cdccc8502fb0b022fa0c651971ac520a81b0b1b1dc41db86a17ed1e50b/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
