# $NetBSD$

DISTNAME=	maskouk_pysqlite-0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/44/18/83609798b9c94b25bb98a347d6c7b0dde6f3de62a08db5908a755cc387e6/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://maskouk.sourceforge.net/
COMMENT=	maskouk: Arabic Dictionary for Collocations - python + sqlite
LICENSE=	gnu-gpl-v1 OR gnu-gpl-v2 OR gnu-gpl-v3

DEPENDS+=	# TODO: pyarabic>=0.6.2

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
