# Module dependencies
amp8.o: mtopo8.o vars.o
amp8.lo: mtopo8.lo vars.lo
amp8.obj: mtopo8.obj vars.obj
mtopo8.o: vars.o
mtopo8.lo: vars.lo
mtopo8.obj: vars.obj
process.o: amp8.o rambo.o vars.o
process.lo: amp8.lo rambo.lo vars.lo
process.obj: amp8.obj rambo.obj vars.obj
