# $NetBSD$

DISTNAME=	requirementslib-1.5.15
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=r/requirementslib/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/sarugaku/requirementslib/
COMMENT=	Tool for converting between pip-style and pipfile requirements
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
