# $NetBSD$

GITHUB_PROJECT=	go-python
GITHUB_TAG=	v0.1.0
DISTNAME=	v0.1.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=sbinet/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/sbinet/go-python/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-python-0.1.0
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
