# $NetBSD$

DISTNAME=	n1ql-20160215
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	go_n1ql
GITHUB_TAG=	6cf4e348b127e21f56e53eb8c3faaea56afdc588
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/go_n1ql/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go_n1ql-6cf4e348b127e21f56e53eb8c3faaea56afdc588
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
