# $NetBSD$

GITHUB_PROJECT=	checkmake
GITHUB_TAG=	0.1.0
DISTNAME=	{GITHUB_TAG}
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=mrtazz/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/mrtazz/checkmake/
COMMENT=	Experimental linter/analyzer for Makefiles
LICENSE=	mit

WRKSRC=		${WRKDIR}/checkmake-0.1.0

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
