# $NetBSD$

DISTNAME=	pymodbus-2.4.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/py//}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pymodbus/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/riptideio/pymodbus/
COMMENT=	Fully featured modbus protocol stack in python
LICENSE=	modified-bsd

DEPENDS+=       ${PYPKGPREFIX}-six>=1.15.0:../../lang/py-six
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #ifwanttousethepymodbusserialstack,uncommentthese>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #pyserial>=3.4
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #ifyouwanttorunthetestsandcodecoverage,uncommentthese>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #coverage==4.4>=0
DEPENDS+=	# TODO: #mock==2.0.0>=0
DEPENDS+=	# TODO: #nose==1.3.7>=0
DEPENDS+=	# TODO: #pep8==1.7.0>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #ifyouwanttousetheTwistedasynchronousversion,uncommentthese>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #Twisted==17.1.0>=0
DEPENDS+=	# TODO: #zope.interface==4.4.0>=0
DEPENDS+=	# TODO: #pyasn1==0.2.3>=0
DEPENDS+=	# TODO: #wsgiref==0.1.2>=0
DEPENDS+=	# TODO: #cryptography==1.8.1>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #ifyouwanttousetheTornadoasynchronousversion,uncommentthese>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #tornado==4.5.2>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #ifyouwanttousetheAsyncioasynchronousversion,uncommentthese>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #pyserial-asyncio==0.4.0;python_version>="3.4"
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #ifyouwanttobuildthedocumentation,uncommentthese>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #Jinja2==2.9.6>=0
DEPENDS+=	# TODO: #Pygments==2.2.0>=0
DEPENDS+=	# TODO: #Sphinx==1.5.5>=0
DEPENDS+=	# TODO: #docutils==0.13.1>=0
DEPENDS+=	# TODO: #pydoctor==16.3.0>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #ifyouwanttousepymodbusREPL>=0
DEPENDS+=	# TODO: #------------------------------------------------------------------->=0
DEPENDS+=	# TODO: #click>=6.7
DEPENDS+=	# TODO: #prompt-toolkit==2.0.4>=0
DEPENDS+=	# TODO: pyserial>=3.4

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
