# $NetBSD$

GITHUB_PROJECT=	gotk3
GITHUB_TAG=	v0.4.0
DISTNAME=	v0.4.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=gotk3/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/gotk3/gotk3/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gotk3-0.4.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
