# $NetBSD$

DISTNAME=	qtwebengine-opensource-src_5.14.2+dfsg1.orig
CATEGORIES=	category
MASTER_SITES=	http://deb.debian.org/debian/pool/main/q/qtwebengine-opensource-src/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://deb.debian.org/debian/pool/main/q/qtwebengine-opensource-src/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
