# $NetBSD$

GITHUB_PROJECT=	robotgo
GITHUB_TAG=	v0.90.3
DISTNAME=	v0.90.3
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-vgo/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go-vgo/robotgo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=	${WRKDIR}/robotgo-0.90.3

.include "../../mk/bsd.pkg.mk"
