# $NetBSD$

GITHUB_PROJECT=	go-parameters
GITHUB_TAG=	v0.2.0
DISTNAME=	v0.2.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=mrz1836/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/mrz1836/go-parameters/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-parameters-0.2.0
USE_LANGUAGES=	# none
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
