# $NetBSD$

DISTNAME=	notify_py-0.2.3
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/dd/e7/d769d2cfd468bc6add04cdd1cc8a15163b3fc2196c5d4b8b6d02cd714751/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/dd/e7/d769d2cfd468bc6add04cdd1cc8a15163b3fc2196c5d4b8b6d02cd714751/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
