# $NetBSD$

DISTNAME=	go-client_model-0.2.0
GITHUB_PROJECT=	client_model
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=prometheus/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/prometheus/client_model/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/client_model-0.2.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
