# $NetBSD$

GITHUB_PROJECT=	gota
GITHUB_TAG=	v0.10.1
DISTNAME=	v0.10.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-gota/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go-gota/gota/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gota-0.10.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
