# $NetBSD$

DISTNAME=	lsb-4.0-22.3.1.x86_64
CATEGORIES=	category
MASTER_SITES=	http://ftp5.gwdg.de/pub/opensuse/discontinued/distribution/13.1/repo/oss/suse/x86_64/
EXTRACT_SUFX=	.rpm

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ftp5.gwdg.de/pub/opensuse/discontinued/distribution/13.1/repo/oss/suse/x86_64/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR} # TODO: one of etc lib lib64, or leave it as-is
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
