# $NetBSD$

DISTNAME=	bash2py-3.6
CATEGORIES=	devel
MASTER_SITES=	https://www.swag.uwaterloo.ca/bash2py/downloads/3.6/
EXTRACT_SUFX=	.zip

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.swag.uwaterloo.ca/bash2py
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_PKGLOCALEDIR=	yes

.include "../../lang/python/application.mk"
.include "../../mk/bsd.pkg.mk"
