# $NetBSD$

GITHUB_PROJECT=	perks
GITHUB_TAG=	v1.0.1
DISTNAME=	v1.0.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=beorn7/}
DIST_SUBDIR=	${GITHUB_PROJECT}


DISTNAME=	go-jira-1.0.26
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-jira/}
GITHUB_PROJECT=	jira
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/beorn7/perks/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

WRKSRC=		${WRKDIR}/perks-1.0.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
