# $NetBSD$

DISTNAME=	pytket-projectq-0.3.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/a7/ba/6484a4c687bedf96355cbde2697fe318892854cb9a320bd18399484eb8d0/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/CQCL/pytket
COMMENT=	Extension for pytket, providing translation to and from the ProjectQ framework
#LICENSE=	CQC Non-Commercial Use Software Licence # TODO: from setup.py; needs to be adjusted

DEPENDS+=	# TODO: pytket~=0.5>=0
DEPENDS+=	# TODO: projectq==0.5>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
