.\"	$NetBSD: buildoptions.8,v 0.2 2020/11/20 17:48:37 jihbed Exp $
.\"
.\"
.Dd October 20, 2020
.Dt BUILDOPTIONS 8
.Os
.Sh NAME
.Nm buildoptions
.Nd automatic pkgsrc options.mk generator
.Sh SYNOPSIS
.Nm
.Op Fl p
.Sh DESCRIPTION
.Nm
reads in the
.Pa Makefile
and
.Pa PLIST
of a package and creates
an initial
.Pa options.mk
file on stdout.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl p
Create PRINT_PLIST_AWK substitution patterns for directories created
and removed by this package.
This is useful for base packages that create a directory structure
for a number of dependent packages.
.El
.Pp
While
.Nm
is supposed to help starting create a options file
for a package, it is not intended to fly on autopilot.
That means that while the script makes some simplistic attempts
to interpret some elements of the
.Pa Makefile
and the
.Pa PLIST
such as the contents of the include and lib subdirectories or
package config scripts, the results should not be put into a
package directory without some scrutiny.
.Pp
Using
.Nm
helps maneuver through the initial process of creating a options
file for a package to be included by depending packages.
Using
.Nm
is less error-prone than copying an existing options file
as a template and renaming the entries in there.
.Sh SEE ALSO
.Xr packages 7 ,
.Xr url2pkg 8  ,
.Xr createbuildlink 8  ,
.Sh AUTHORS
.Nm
was written by
.An K.I.A.Derouiche Aq Mt kamel.derouiche@gmail.com .
