# $NetBSD$

DISTNAME=	waterfox-current-2020.07.1.en-US.linux-x86_64
CATEGORIES=	www
MASTER_SITES=	https://cdn.waterfox.net/releases/linux64/installer/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://cdn.waterfox.net/releases/linux64/installer/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/waterfox
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
