# $NetBSD$

GITHUB_PROJECT=	curlie
GITHUB_TAG=	v1.6.0
DISTNAME=	v1.6.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=rs/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/rs/curlie/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/curlie-1.6.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
