# Module dependencies
color.o: model.o
color.lo: model.lo
color.obj: model.obj
config.o: color.o
config.lo: color.lo
config.obj: color.obj
dipoles.o: color.o kinematics.o model.o
dipoles.lo: color.lo kinematics.lo model.lo
dipoles.obj: color.obj kinematics.obj model.obj
functions.o: model.o
functions.lo: model.lo
functions.obj: model.obj
kinematics.o: model.o
kinematics.lo: model.lo
kinematics.obj: model.obj
