# $NetBSD$

GITHUB_PROJECT=	flogo
GITHUB_TAG=	v0.5.8
DISTNAME=	v0.5.8
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=TIBCOSoftware/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/TIBCOSoftware/flogo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/flogo-0.5.8
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
