# $NetBSD$

DISTNAME=	jupyter_vtk-0.3.1.dev0-py2.py3-none-any
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/3f/4c/82920bec19be18e9ddcf69cf0d7667e70bec9f18f7fb8eb06aa2d26b64bd/
EXTRACT_SUFX=	.whl

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/3f/4c/82920bec19be18e9ddcf69cf0d7667e70bec9f18f7fb8eb06aa2d26b64bd/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
