# $NetBSD$

GITHUB_PROJECT=	golangci-lint
GITHUB_TAG=	v1.30.0
DISTNAME=	v1.30.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/golangci-lint/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/golangci-lint-1.30.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
