# $NetBSD$

DISTNAME=	go-benthos-3.36.0
GITHUB_PROJECT=	benthos
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=Jeffail/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.benthos.dev/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/benthos-3.36.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
