# $NetBSD$

DISTNAME=	go-benthos-3.36.0
GITHUB_PROJECT=	benthos
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=Jeffail/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.benthos.dev/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	benthos-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/Jeffail/benthos

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
