# $NetBSD$

DISTNAME=	pyBKT-1.3
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/fb/60/c8cdb60a0c89c3f50da3d31f72616092bb81a45fa0941e88aa8269b7604d/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/fb/60/c8cdb60a0c89c3f50da3d31f72616092bb81a45fa0941e88aa8269b7604d/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
