# $NetBSD$

DISTNAME=	projectq-0.5.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/e1/5d/d470b8f15f933587efbc38d4202662bae69eccfa69e2b82c2c420afd44fa/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/e1/5d/d470b8f15f933587efbc38d4202662bae69eccfa69e2b82c2c420afd44fa/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
