# $NetBSD$

DISTNAME=	htmlmin-0.1.12
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	www python
MASTER_SITES=	${MASTER_SITE_PYPI:=h/htmlmin/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://htmlmin.readthedocs.io/en/latest/
COMMENT=	HTML Minifier
#LICENSE=	BSD # TODO: from setup.py; needs to be adjusted

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
