# $NetBSD$

DISTNAME=	x2j-20131220
PKGANME=	go-${DISTNAME}
GITHUB_PROJECT=	x2j
GITHUB_TAG=	a0352aa
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/x2j/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/x2j-a0352aadc5420072ebe692481a5d6913d77f8cf0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
