# $NetBSD$

DISTNAME=	mapclassify-2.4.2
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/5f/52/18c208f448102eb6272fcf46d1a33e85a49e9f53cadf2d147f1a59bdcc93/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/5f/52/18c208f448102eb6272fcf46d1a33e85a49e9f53cadf2d147f1a59bdcc93/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
