# $NetBSD$

DISTNAME=	scikit-ci-addons-0.25.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/44/68/2a18f84887b3f8ea0bbbe32f14032a05912e96636d245d7c3ca4c69661ab/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/44/68/2a18f84887b3f8ea0bbbe32f14032a05912e96636d245d7c3ca4c69661ab/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
