# $NetBSD$

DISTNAME=	go-scany-0.2.7
GITHUB_PROJECT=	scany
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=georgysavva/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/georgysavva/scany/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/scany-0.2.7
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
