# $NetBSD$

DISTNAME=	flatbuffers-1.12
EGG_INFODIR=	flatbuffers-20201129142929-py${PYVERSSUFFIX}.egg-info
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=f/flatbuffers/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://google.github.io/flatbuffers/
COMMENT=	The FlatBuffers serialization format for Python
LICENSE=	apache-2.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
