# $NetBSD$

DISTNAME=	flatbuffers-1.12
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://files.pythonhosted.org/packages/4d/c4/7b995ab9bf0c7eaf10c386d29a03408dfcf72648df4102b1f18896c3aeea/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://google.github.io/flatbuffers/
COMMENT=	The FlatBuffers serialization format for Python
LICENSE=	apache-2.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
