# $NetBSD$

DISTNAME=	faiss-cpu-1.7.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	https://files.pythonhosted.org/packages/59/54/b4d5e08b558aca33e5ec5ad51bdf4ab722116700c48074e2560426fb1bdd/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/59/54/b4d5e08b558aca33e5ec5ad51bdf4ab722116700c48074e2560426fb1bdd/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
