# $NetBSD$

DISTNAME=	faiss-cpu-1.7.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/59/54/b4d5e08b558aca33e5ec5ad51bdf4ab722116700c48074e2560426fb1bdd/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/59/54/b4d5e08b558aca33e5ec5ad51bdf4ab722116700c48074e2560426fb1bdd/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
