# $NetBSD$

GITHUB_PROJECT=	jwt-go
GITHUB_TAG=	v3.2.0
DISTNAME=	v3.2.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=dgrijalva/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/dgrijalva/jwt-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/jwt-go-3.2.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
