# $NetBSD$

DISTNAME=	swh.scanner-0.2.0
PKGNAME=	${PYPKGPREFIX}-swh-scanner-0.2.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=s/swh.scanner/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/39/cb/9eeda46c84645ce598fe600d051b7c143c3e89e903a9f52a8de67af82ab9/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
