# $NetBSD$

DISTNAME=	bw2io-0.8.3.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/e8/98/08cde871d4dbad7d3f67d47ca99374fa20fee6085ab915d43eef0de67cff/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/e8/98/08cde871d4dbad7d3f67d47ca99374fa20fee6085ab915d43eef0de67cff/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
