# $NetBSD$

DISTNAME=	gota-0.0.0.20191108
PKGNAME=	go-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-gota/}
GITHUB_PROJECT=	gota
GITHUB_TAG=	34e54ced8992ba08c4a6cc14a94859b4dfef3dd4

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/go-gota/gota/
COMMENT=	DataFrames and data wrangling in Go
#LICENSE=	# TODO: (see mk/license.mk)

GO_DIST_BASE=	gota-${GITHUB_TAG}
GO_SRCPATH=	github.com/go-gota/gota

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
