# $NetBSD$

DISTNAME=	gota-0.0.0.20191108
PKGNAME=	go-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=go-gota/}
GITHUB_PROJECT=	gota
GITHUB_TAG=	34e54ced8992ba08c4a6cc14a94859b4dfef3dd4

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/go-gota/gota/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gota-34e54ced8992ba08c4a6cc14a94859b4dfef3dd4
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
