# $NetBSD$

DISTNAME=	go-osstat-0.1.0
GITHUB_PROJECT=	go-osstat
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=mackerelio/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/mackerelio/go-osstat/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
