integralfamilies:
  - name: "TennisCourt"
    loop_momenta: [l1, l2, l3]
    top_level_sectors: [2047]
    propagators:
      - [ "l1-l3",    0 ]
      - [ "l1+p1",    0 ]
      - [ "l1+p1+p2", 0 ]
      - [ "l2+p1+p2", 0 ]
      - [ "l2+p3",    0 ]
      - [ "l2-l3",    0 ]
      - [ "l1-l2",    0 ]
      - [ "l3",       0 ]
      - [ "l3+p1",    0 ]
      - [ "l3+p3",    0 ]
      - [ "l3+p1+p2", 0 ]
      - [ "l2+p1",    0 ]
      - [ "l1+p3",    0 ]
      - [ "l1",       0 ]
      - [ "l2",       0 ]
