# $NetBSD$

GITHUB_PROJECT=	perks
GITHUB_TAG=	v1.0.1
DISTNAME=	v1.0.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=beorn7/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/beorn7/perks/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/perks-1.0.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
