# $NetBSD$

DISTNAME=	swh.loader.core-0.15.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/bb/53/7357ef3a7293e56fdca064d728af9fd033f999305860dd83b1d1e7d3054d/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/bb/53/7357ef3a7293e56fdca064d728af9fd033f999305860dd83b1d1e7d3054d/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
