# $NetBSD$

DISTNAME=	kdevelop-5.5.2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_KDE:=kdevelop/5.5.2/src/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.kdevelop.org/
COMMENT=	Integrated Development Environment for Unix/X11/KDE
LICENSE=	gnu-gpl-v2

USE_CMAKE=		yes
USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		c c++


.include "../../mk/bsd.pkg.mk"
