# $NetBSD$

DISTNAME=	kdevelop-5.5.2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_KDE:=kdevelop/5.5.2/src/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://www.kdevelop.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=		yes
USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		c c++

.include "../../mk/bsd.pkg.mk"
