# $NetBSD$

DISTNAME=	anyconfig-0.9.11
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/6f/93/0749cca282f0bd772b17a218315009da89546f9c9ff1f5f88e6c8f9bc230/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/6f/93/0749cca282f0bd772b17a218315009da89546f9c9ff1f5f88e6c8f9bc230/
COMMENT=	Library provides common APIs to load and dump configuration files in various formats
LICENSE=	mit

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
