# $NetBSD$

GITHUB_PROJECT=	RxGo
GITHUB_TAG=	v2.4.0
DISTNAME=	${GITHUB_TAG}
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_GITHUB:=ReactiveX/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/ReactiveX/RxGo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/RxGo-2.4.0

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
