# $NetBSD$

DISTNAME=	go-ps-20201120
GITHUB_PROJECT=	go-ps
GITHUB_TAG=	ddafa75
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=mitchellh/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/mitchellh/go-ps/
COMMENT=	mit
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/go-ps-ddafa7589c607e0e81a7436520ccdbac913665a2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
