# $NetBSD$

DISTNAME=	beebeep-5.8.2-qt5-amd64
CATEGORIES=	category
MASTER_SITES=	https://deac-ams.dl.sourceforge.net/project/beebeep/Linux/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://deac-ams.dl.sourceforge.net/project/beebeep/Linux/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
