# $NetBSD$

DISTNAME=	pySpecData-0.9.5.3.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/e2/2e/86411e6d086caea73d050c7ead529d73555b65153d194e2092fd1197c8df/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/e2/2e/86411e6d086caea73d050c7ead529d73555b65153d194e2092fd1197c8df/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
