# $NetBSD$

GITHUB_PROJECT=	xurls
GITHUB_TAG=	v2.2.0
DISTNAME=	v2.2.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=mvdan/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/mvdan/xurls/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/xurls-2.2.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
