# $NetBSD$

DISTNAME=	go-bindata-4.0.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=shuLhan/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/shuLhan/go-bindata/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
