# $NetBSD$

DISTNAME=	kenv-0.1.9.31
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/a5/75/316ce14e86bd6ab681ab0f1e14c9a2484cfbda7f6e6822a2b45e6959acbc/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/a5/75/316ce14e86bd6ab681ab0f1e14c9a2484cfbda7f6e6822a2b45e6959acbc/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
