# $NetBSD$

DISTNAME=	downloads?f=softsusy-4.1.10
CATEGORIES=	category
MASTER_SITES=	https://softsusy.hepforge.org/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://softsusy.hepforge.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
