# $NetBSD$

DISTNAME=	BondGraphTools-0.3.9
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/04/f5/62de1ab406abcd61d8c2b2300566e27aec02b231ec37d08c129d67eede6c/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/04/f5/62de1ab406abcd61d8c2b2300566e27aec02b231ec37d08c129d67eede6c/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
