# $NetBSD$

DISTNAME=	google-cloud-core-1.4.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/8d/8d/175a2657a51d51203c4137fe1257fdfffac4eb63786f1ee4a9d66cfedf48/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/googleapis/python-cloud-core
COMMENT=	Google Cloud API client core library
LICENSE=	apache-2.0

DEPENDS+=	py-google-api-core>=1.19.0,<2.0.0dev:../../devel/py-google-api-core

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
