# $NetBSD$

GITHUB_PROJECT=	ginkgo
GITHUB_TAG=	v1.14.1
DISTNAME=	v1.14.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=onsi/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/onsi/ginkgo/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ginkgo-1.14.1
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
