# $NetBSD$

DISTNAME=	klausen-0.1.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/fa/c9/efb9ce9613be048c6cfaa9b680491e646477c5006abd6ff434f41a88b888/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/cmutel/klausen
COMMENT=	Parameterized model framework in Python
#LICENSE=	BSD 3-Clause License

DEPENDS+=	# TODO: numpy>=0
DEPENDS+=	# TODO: scipy>=0
DEPENDS+=	# TODO: stats_arrays>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
