# $NetBSD$

DISTNAME=	klausen-0.1.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=k/klausen/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/cmutel/klausen
COMMENT=	Parameterized model framework in Python
#LICENSE=	BSD 3-Clause License

DEPENDS+=	# TODO: numpy>=0
DEPENDS+=	# TODO: scipy>=0
DEPENDS+=	# TODO: stats_arrays>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
