# $NetBSD$

DISTNAME=	gg-20200515
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	gg
GITHUB_TAG=	ad4d1eafac46916fde6a6b375f7389e555f7e040
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_GITHUB:=fogleman/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/fogleman/gg/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gg-ad4d1eafac46916fde6a6b375f7389e555f7e040
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
