# $NetBSD$

DISTNAME=	sqlite-fts4-1.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/62/30/63e64b7b8fa69aabf97b14cbc204cb9525eb2132545f82231c04a6d40d5c/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/simonw/sqlite-fts4
COMMENT=	Python functions for working with SQLite FTS4 search
#LICENSE=	Apache License, Version 2.0 # TODO: from setup.py; needs to be adjusted

TEST_DEPENDS+=	# TODO: sqlite-fts4[test]>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
