# $NetBSD$

DISTNAME=	swh.objstorage.replayer-0.2.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/f5/b8/fdd6cf443ed7f0f1b9ca41db47d0855a536173f756354fb01a0efe334c24/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://forge.softwareheritage.org/diffusion/swh-objstorage-replayer
COMMENT=	Software Heritage content replayer
#LICENSE=	# TODO: (see mk/license.mk)

BUILD_DEPENDS+=	py-setuptools_scm>=0:../../devel/py-setuptools_scm
DEPENDS+=	# TODO: swh.core[http]>=0.3
DEPENDS+=	# TODO: swh.objstorage>=0.2.2
DEPENDS+=	# TODO: swh.journal>=0.4.2
TEST_DEPENDS+=	# TODO: pytest>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
