# $NetBSD$

DISTNAME=	go-pio-0.0.10
GITHUB_PROJECT=	pio
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=kataras/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/kataras/pio/
COMMENT=	TODO: Short description of the package
LICENSE=	2-clause-bsd

GO_SRCPATH=	github.com/kataras/pio
GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
