# $NetBSD$

DISTNAME=	arabic_reshaper-2.1.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/0a/1e/b78cacd22bd55c43f2711115d67ece3ed9616ba82d2d0e0914db2a6db985/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/mpcabd/python-arabic-reshaper/
COMMENT=	Reconstruct Arabic sentences to be used in applications that don't support Arabic
LICENSE=	mit

DEPENDS+=	# TODO: configparser;python_version<"3">=0
DEPENDS+=	py-future>=0:../../devel/py-future
DEPENDS+=	py-setuptools>=0:../../devel/py-setuptools

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
