# $NetBSD$

DISTNAME=	go-clir-1.0.2
GITHUB_PROJECT=	clir
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=leaanthony/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/leaanthony/clir/
COMMENT=	Simple and Clear CLI library
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=     github.com/leaanthony/clir
GO_DIST_BASE=   ${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
