# $NetBSD$

DISTNAME=	google-cloud-bigquery-2.2.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/d5/12/40b130e1bded0c3ab0836a974ba39f3ee0fc7fe8492a25c50818a01e8b47/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/d5/12/40b130e1bded0c3ab0836a974ba39f3ee0fc7fe8492a25c50818a01e8b47/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
