# $NetBSD$

DISTNAME=	google-cloud-bigquery-2.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	databases python
MASTER_SITES=	https://files.pythonhosted.org/packages/d5/12/40b130e1bded0c3ab0836a974ba39f3ee0fc7fe8492a25c50818a01e8b47/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://files.pythonhosted.org/packages/d5/12/40b130e1bded0c3ab0836a974ba39f3ee0fc7fe8492a25c50818a01e8b47/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
