# $NetBSD$

DISTNAME=	pg8000-1.16.6
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/24/1b/584dda6665ce38535c8892b42d458c24e517d139a5baa172bf43bf4c4dfb/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/24/1b/584dda6665ce38535c8892b42d458c24e517d139a5baa172bf43bf4c4dfb/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
