# $NetBSD$

DISTNAME=	optimesh-0.7.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ec/b9/7f4326ea891a46e1bb712a5b5f521d7601cca580e147e2f8c930477a9f8e/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ec/b9/7f4326ea891a46e1bb712a5b5f521d7601cca580e147e2f8c930477a9f8e/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
