# $NetBSD$

GITHUB_PROJECT=	systray
GITHUB_TAG=	v1.0.4
DISTNAME=	v1.0.4
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=getlantern/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/getlantern/systray/
COMMENT=	TODO: Short description of the package
LICENSE=	apache-2.0

WRKSRC=	${WRKDIR}/systray-1.0.4

USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
