# $NetBSD$

DISTNAME=	go-systray-1.1.0
GITHUB_PROJECT=	systray
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=getlantern/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/getlantern/systray/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=	${WRKDIR}/systray-1.1.0

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
