# $NetBSD$

DISTNAME=	solvespace
PKGNAME=	solvespace-3.0
GITHUB_PROJECT=	solvespace
GITHUB_TAG=	refs/tags/v3.0
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=solvespace/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/solvespace/solvespace/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=			${WRKDIR}/solvespace-3.0
USE_CMAKE=		yes
USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		c c++

.include "../../mk/bsd.pkg.mk"
