# $NetBSD$

DISTNAME=	galgebra-0.5.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/87/b2/49632430f6b49c37a5e95bcca04f809e49447c836e68f7e35bb09f90ba67/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/pygae/galgebra
COMMENT=	Symbolic Geometric Algebra/Calculus package for SymPy
#LICENSE=	BSD # TODO: from setup.py; needs to be adjusted

DEPENDS+=	py-sympy>=0:../../math/py-sympy

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
