# $NetBSD$

DISTNAME=	meshzoo-0.6.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/e1/c6/e1e69d89badfb902885f44b803663106f74a1e84fddc68546b43207be99c/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/e1/c6/e1e69d89badfb902885f44b803663106f74a1e84fddc68546b43207be99c/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
