# $NetBSD$

DISTNAME=	klatexformula-4.1.0
CATEGORIES=	print
MASTER_SITES=	https://netix.dl.sourceforge.net/project/klatexformula/klatexformula/klatexformula-4.1.0/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://netix.dl.sourceforge.net/project/klatexformula/klatexformula/klatexformula-4.1.0/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
