# $NetBSD$

DISTNAME=	dash-bootstrap-components-0.10.7
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/4f/de/f365781218310a1cd0f29bebc39375d38fede812c47ef9f2ef7188d33964/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://dash-bootstrap-components.opensource.faculty.ai
COMMENT=	Bootstrap themed components for use in Plotly Dash
#LICENSE=	# TODO: (see mk/license.mk)

DEPENDS+=	py-dash>=1.9.0:../../devel/py-dash

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
