# $NetBSD$

DISTNAME=	symlens-0.2.4
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category python
MASTER_SITES=	https://files.pythonhosted.org/packages/4a/ad/5e9ff0d09a9f51dc04ba6f37a65edada0b36bd6fc8fa91f549968d51016f/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/simonsobs/symlens
COMMENT=	Symbolic Mode Coupling
#LICENSE=	BSD license # TODO: from setup.py; needs to be adjusted

BUILD_DEPENDS+=	# TODO: pytest-runner>=0
TEST_DEPENDS+=	# TODO: pytest>=0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
