# $NetBSD$

DISTNAME=	boost_histogram-0.11.1
PKGNAME=	${PYPKGPREFIX}-boost-histogram-0.11.1
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=b/boost_histogram/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/scikit-hep/boost-histogram
COMMENT=	Python bindings for the C++14 Boost::Histogram library
LICENSE=	modified-bsd

.include "../../devel/py-pybind11/buildlink3.mk"
.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
