# $NetBSD$

DISTNAME=	diver-1.0.5
CATEGORIES=	category
MASTER_SITES=	https://diver.hepforge.org/downloads/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://diver.hepforge.org/downloads/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/Diver-1.0.5
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
