# $NetBSD$

DISTNAME=	py-ubjson-0.16.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/py-//}
CATEGORIES=	converters python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/py-ubjson/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/Iotic-Labs/py-ubjson
COMMENT=	Universal Binary JSON encoder/decoder
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
