jobs:
 - reduce_sectors:
    reduce:
     - {sectors: [2047], r: 11, s: 1}
    select_integrals:
     select_mandatory_recursively:
      - {sectors: [2047], r: 11, s: 1, d: 0}
    run_initiate: true
    run_triangular: true
    run_back_substitution: true
