# $NetBSD$

GITHUB_PROJECT=	client_golang
GITHUB_TAG=	v1.9.0
DISTNAME=	v1.9.0
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=prometheus/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/prometheus/client_golang/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/client_golang-1.9.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
