# $NetBSD$

DISTNAME=	cyksuid-1.0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/c2/cb/6b9a53e04b1bf8145b1557298a09c92174c0b5e62c4426baa094067bd4c0/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/timonwong/cyksuid
COMMENT=	TODO: Short description of the package
LICENSE=	modified-bsd

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
