# $NetBSD$

DISTNAME=	go-libvlc-3.0.8
GITHUB_PROJECT=	libvlc-go
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	multimedia
MASTER_SITES=	${MASTER_SITE_GITHUB:=adrg/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/adrg/libvlc-go/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GO_SRCPATH=     github.com/adrg/libvlc-go
GO_DIST_BASE=   ${GITHUB_PROJECT}-${PKGVERSION_NOREV}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
