# $NetBSD$

DISTNAME=	qiskit-aqua-0.7.5
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/a2/a3/1faadc428c2c2a1404c3b86b16369b7ddc5037429e6cb7926c57489e6e86/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/a2/a3/1faadc428c2c2a1404c3b86b16369b7ddc5037429e6cb7926c57489e6e86/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
