# $NetBSD$

DISTNAME=	qiskit-aqua-0.7.5
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://files.pythonhosted.org/packages/a2/a3/1faadc428c2c2a1404c3b86b16369b7ddc5037429e6cb7926c57489e6e86/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/Qiskit/qiskit-aqua/
COMMENT=	Qiskit Aqua: An extensible library of quantum computing algorithms
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
