# $NetBSD$

DISTNAME=	go-micro-2.9.1
GITHUB_PROJECT=	go-micro
GITHUB_TAG=	v${PKGVERSION_NOREV}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=asim/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/asim/go-micro/
COMMENT=	Go Micro is a framework for distributed systems development
LICENSE=	apache-2.0

GO_DIST_BASE=	${GITHUB_PROJECT}-${PKGVERSION_NOREV}
GO_SRCPATH=	github.com/asim/go-micro

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
