# $NetBSD$

GITHUB_PROJECT=	ukui-themes
DISTNAME=	ukui-themes_1.4.0.orig
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
GITHUB_RELEASE=	v1.4.0

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/ukui-themes/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/ukui-themes
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
