# $NetBSD$

GITHUB_PROJECT=	beego
GITHUB_TAG=	v1.12.2
DISTNAME=	v1.12.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=astaxie/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/astaxie/beego/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/beego-1.12.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
