# $NetBSD$

DISTNAME=	crowdsec-1.0.2
GITHUB_PROJECT=	crowdsec
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_GITHUB:=crowdsecurity/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/crowdsecurity/crowdsec/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

USE_TOOLS+=	bash gmake

.include "../../mk/bsd.pkg.mk"
