# $NetBSD$

GITHUB_PROJECT=	crowdsec
GITHUB_TAG=	v0.3.6
DISTNAME=	v0.3.6
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_GITHUB:=crowdsecurity/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/crowdsecurity/crowdsec/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
