# $NetBSD$

DISTNAME=	stripansi-20180116
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	stripansi
GITHUB_TAG=	5a71ef0e047df0427e87a79f27009029921f1f9b
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=acarl005/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/acarl005/stripansi/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/stripansi-5a71ef0e047df0427e87a79f27009029921f1f9b
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
