# $NetBSD$

DISTNAME=	go-gabs-2.6.0
GITHUB_PROJECT=	gabs
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=Jeffail/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/Jeffail/gabs/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/gabs-2.6.0
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
