# $NetBSD$

DISTNAME=	pysfg-0.1.1
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/e9/53/ced13d8783c634e9b34ca0076045dba79c35832e63636aaa177870ac7326/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/e9/53/ced13d8783c634e9b34ca0076045dba79c35832e63636aaa177870ac7326/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
