# $NetBSD$

DISTNAME=	vivaldi-stable-3.4.2066.86-1.x86_64
CATEGORIES=	www
MASTER_SITES=	https://downloads.vivaldi.com/stable/
EXTRACT_SUFX=	.rpm

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://downloads.vivaldi.com/stable/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR} # TODO: one of etc opt usr, or leave it as-is
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
