# $NetBSD$

DISTNAME=	atd-2.2.1
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ahrefs/atd/releases/download/2.2.1/}
EXTRACT_SUFX=	.tbz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ahrefs/atd/releases/download/2.2.1/ # TODO: check
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
