# $NetBSD$

DISTNAME=	miniaudio-20210118
PKGNAME=	lib${DISTNAME}
GITHUB_PROJECT=	miniaudio
GITHUB_TAG=	53512c39b79ee284058e139604f358fd8a3489cd
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_GITHUB:=kiaderouiche/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kiaderouiche/miniaudio/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}-${GITHUB_TAG}

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
