# $NetBSD$

DISTNAME=	pandas-gbq-0.14.0
CATEGORIES=	category
MASTER_SITES=	https://files.pythonhosted.org/packages/ae/a5/2d2acc5d454ec96c758cf034bd35a680fdeb509cb02454526122953449dd/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://files.pythonhosted.org/packages/ae/a5/2d2acc5d454ec96c758cf034bd35a680fdeb509cb02454526122953449dd/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
