# $NetBSD$

GITHUB_PROJECT=	peony-extensions
GITHUB_TAG=	v2.0.1
DISTNAME=	v2.0.1
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME:S,^v,,}
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_GITHUB:=ukui/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ukui/peony-extensions/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/peony-extensions-2.0.1
USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
